/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.sys.posix.sys.stat;

version(Posix):

import rtld.sys.posix.sys.types;

version(linux)
{
    struct stat_t
    {
        ulong st_dev;
        ulong st_ino;
        ulong st_nlink;
        uint  st_mode;
        uint  st_uid;
        uint  st_gid;
        int   __pad0;
        ulong st_rdev;
        long  st_size;
        long  st_blksize;
        long  st_blocks;
        long  st_atime; ulong st_atime_nsec;
        long  st_mtime; ulong st_mtime_nsec;
        long  st_ctime; ulong st_ctime_nsec;
        long[3] __unused;
    }
}
version(OSX)
{
    struct stat_t
    {
        int      st_dev;
        uint     st_mode;
        ushort   st_nlink;
        ulong    st_ino;
        uint     st_uid;
        uint     st_gid;
        int      st_rdev;
        long     st_atime; ulong st_atime_nsec;
        long     st_mtime; ulong st_mtime_nsec;
        long     st_ctime; ulong st_ctime_nsec;
        long     st_birthtime; ulong st_birthtime_nsec;
        long     st_size;
        long     st_blocks;
        int      st_blksize;
        uint     st_flags;
        uint     st_gen;
        int      st_lspare;
        long[2]  st_qspare;
    }
}

extern(C) @nogc nothrow
{
    int fstat(int fd, stat_t* buf);
}
