/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.sys.windows.windows;

version(Windows):

pragma(lib, "kernel32");
pragma(lib, "user32");
pragma(lib, "gdi32");

alias VOID = void;
alias HANDLE = void*;
alias HMODULE = void*;
alias BYTE = ubyte;
alias WORD = ushort;
alias WCHAR = wchar;
alias BOOL = int;
alias DWORD = uint;
alias UINT = uint;
alias LONG = int;
alias ULONG = uint;
alias LONGLONG = long;
alias LPVOID = void*;
alias FLOAT = float;

alias LONG_PTR = ptrdiff_t;
alias ULONG_PTR = size_t;

alias LPCSTR = const(char)*;
alias LPCWSTR = const(wchar)*;

alias LRESULT = LONG_PTR;
alias LPARAM  = LONG_PTR;
alias WPARAM  = ULONG_PTR;

alias ATOM = ushort;

alias HWND = HANDLE;

alias HGLRC = void*;
alias HDC   = void*;

alias HINSTANCE = void*;
alias HMENU     = void*;
alias HICON     = void*;
alias HCURSOR   = void*;
alias HBRUSH    = void*;

alias COLORREF = uint;

enum TRUE = 1;
enum FALSE = 0;

enum BLACK_BRUSH = 4;

enum STD_INPUT_HANDLE = cast(DWORD)-10;
enum STD_OUTPUT_HANDLE = cast(DWORD)-11;
enum STD_ERROR_HANDLE = cast(DWORD)-12;
enum HANDLE INVALID_HANDLE_VALUE = cast(HANDLE)-1;

alias PROC = extern(Windows) void function();
alias FARPROC = extern(Windows) void function();
alias WNDPROC = extern(Windows) LRESULT function(HWND, UINT, WPARAM, LPARAM);

union LARGE_INTEGER
{
    struct
    {
        DWORD LowPart;
        LONG HighPart;
    };
    
    LONGLONG QuadPart;
}

struct LIST_ENTRY
{
    LIST_ENTRY* Flink;
    LIST_ENTRY* Blink;
}

alias PLIST_ENTRY = LIST_ENTRY*;
alias PRKLST_ENTRY = LIST_ENTRY*;

struct SECURITY_ATTRIBUTES
{
    uint nLength;
    void* lpSecurityDescriptor;
    int bInheritHandle;
}

alias LPTHREAD_START_ROUTINE = extern(Windows) uint function(const(void)*);

enum INFINITE = uint.max;
enum STILL_ACTIVE = 259;

struct RTL_CRITICAL_SECTION_DEBUG
{
    WORD Type;
    WORD CreatorBackTraceIndex;
    RTL_CRITICAL_SECTION* CriticalSection;
    LIST_ENTRY ProcessLocksList;
    ULONG EntryCount;
    ULONG ContentionCount;
    ULONG Flags;
    WORD CreatorBackTraceIndexHigh;
    WORD SpareUSHORT;
}

alias PRTL_CRITICAL_SECTION_DEBUG = RTL_CRITICAL_SECTION_DEBUG*;

struct RTL_CRITICAL_SECTION
{
    PRTL_CRITICAL_SECTION_DEBUG DebugInfo;
    LONG LockCount;
    LONG RecursionCount;
    HANDLE OwningThread;
    HANDLE LockSemaphore;
    ULONG_PTR SpinCount;
}

alias PRTL_CRITICAL_SECTION = RTL_CRITICAL_SECTION*;
alias CRITICAL_SECTION = RTL_CRITICAL_SECTION;
alias LPCRITICAL_SECTION = PRTL_CRITICAL_SECTION;

enum TLS_OUT_OF_INDEXES = 0xffffffff;

enum DWORD GENERIC_READ  = 0x80000000;
enum DWORD GENERIC_WRITE = 0x40000000;
enum DWORD FILE_SHARE_READ = 0x00000001;
enum DWORD CREATE_NEW        = 1;
enum DWORD CREATE_ALWAYS     = 2;
enum DWORD OPEN_EXISTING     = 3;
enum DWORD OPEN_ALWAYS       = 4;
enum DWORD TRUNCATE_EXISTING = 5;
enum DWORD FILE_ATTRIBUTE_NORMAL = 0x00000080;
enum DWORD FILE_BEGIN   = 0;
enum DWORD FILE_CURRENT = 1;
enum DWORD FILE_END     = 2;

struct WIN32_FILE_ATTRIBUTE_DATA
{
    DWORD dwFileAttributes;
    uint ftCreationTime_dwLowDateTime;
    uint ftCreationTime_dwHighDateTime;
    uint ftLastAccessTime_dwLowDateTime;
    uint ftLastAccessTime_dwHighDateTime;
    uint ftLastWriteTime_dwLowDateTime;
    uint ftLastWriteTime_dwHighDateTime;
    DWORD nFileSizeHigh;
    DWORD nFileSizeLow;
}

enum int GetFileExInfoStandard = 0;
enum DWORD FILE_ATTRIBUTE_READONLY = 0x00000001;
enum DWORD FILE_ATTRIBUTE_DIRECTORY = 0x00000010;

enum CP_UTF8 = 65001;

struct POINT
{
    LONG x;
    LONG y;
}

struct POINTFLOAT
{
    FLOAT x;
    FLOAT y;
}

struct RECT
{
    int left;
    int top;
    int right;
    int bottom;
}

enum WM_QUIT     = 0x0012;
enum WM_NCCREATE = 0x0081;
enum WM_DESTROY  = 0x0002;
enum WM_SIZE     = 0x0005;

enum GWLP_USERDATA      = -21;

enum IDC_ARROW = cast(LPCWSTR)32512;
enum COLOR_WINDOW       = 5;

enum WS_OVERLAPPEDWINDOW = 0x00CF0000;
enum WS_VISIBLE          = 0x10000000;
enum WS_CLIPSIBLINGS     = 0x04000000;
enum WS_CLIPCHILDREN     = 0x02000000;

enum PM_REMOVE           = 0x0001;

struct MSG
{
    HWND    hwnd;
    UINT    message;
    WPARAM  wParam;
    LPARAM  lParam;
    DWORD   time;
    POINT   pt;
    DWORD   lPrivate;
}

struct CREATESTRUCT
{
    void*  lpCreateParams;
    HINSTANCE hInstance;
    HMENU  hMenu;
    HWND   hwndParent;
    int    cy;
    int    cx;
    int    y;
    int    x;
    LONG   style;
    LPCSTR lpszName;
    LPCSTR lpszClass;
    DWORD  dwExStyle;
}

struct WNDCLASS
{
    UINT      style;
    WNDPROC   lpfnWndProc;
    int       cbClsExtra;
    int       cbWndExtra;
    HINSTANCE hInstance;
    HICON     hIcon;
    HCURSOR   hCursor;
    HBRUSH    hbrBackground;
    LPCSTR    lpszMenuName;
    LPCSTR    lpszClassName;
}

struct WNDCLASSW
{
    UINT      style;
    WNDPROC   lpfnWndProc;
    int       cbClsExtra;
    int       cbWndExtra;
    HINSTANCE hInstance;
    HICON     hIcon;
    HCURSOR   hCursor;
    HBRUSH    hbrBackground;
    LPCWSTR   lpszMenuName;
    LPCWSTR   lpszClassName;
}

struct LAYERPLANEDESCRIPTOR
{
    WORD  nSize;
    WORD  nVersion;
    DWORD dwFlags;
    BYTE  iPixelType;
    BYTE  cColorBits;
    BYTE  cRedBits;
    BYTE  cRedShift;
    BYTE  cGreenBits;
    BYTE  cGreenShift;
    BYTE  cBlueBits;
    BYTE  cBlueShift;
    BYTE  cAlphaBits;
    BYTE  cAlphaShift;
    BYTE  cAccumBits;
    BYTE  cAccumRedBits;
    BYTE  cAccumGreenBits;
    BYTE  cAccumBlueBits;
    BYTE  cAccumAlphaBits;
    BYTE  cDepthBits;
    BYTE  cStencilBits;
    BYTE  cAuxBuffers;
    BYTE  iLayerType;
    BYTE  bReserved;
    COLORREF crTransparent;
}

alias LPLAYERPLANEDESCRIPTOR = LAYERPLANEDESCRIPTOR*;

struct PIXELFORMATDESCRIPTOR
{
    WORD  nSize;
    WORD  nVersion;
    DWORD dwFlags;
    BYTE  iPixelType;
    BYTE  cColorBits;
    BYTE  cRedBits;
    BYTE  cRedShift;
    BYTE  cGreenBits;
    BYTE  cGreenShift;
    BYTE  cBlueBits;
    BYTE  cBlueShift;
    BYTE  cAlphaBits;
    BYTE  cAlphaShift;
    BYTE  cAccumBits;
    BYTE  cAccumRedBits;
    BYTE  cAccumGreenBits;
    BYTE  cAccumBlueBits;
    BYTE  cAccumAlphaBits;
    BYTE  cDepthBits;
    BYTE  cStencilBits;
    BYTE  cAuxBuffers;
    BYTE  iLayerType;
    BYTE  bReserved;
    DWORD dwLayerMask;
    DWORD dwVisibleMask;
    DWORD dwDamageMask;
}

alias LPPIXELFORMATDESCRIPTOR = PIXELFORMATDESCRIPTOR*;

enum PFD_DRAW_TO_WINDOW = 0x00000004;
enum PFD_SUPPORT_OPENGL = 0x00000020;
enum PFD_DOUBLEBUFFER   = 0x00000001;

enum PFD_TYPE_RGBA      = 0;
enum PFD_MAIN_PLANE     = 0;

struct GLYPHMETRICSFLOAT
{
    FLOAT gmfBlackBoxX;
    FLOAT gmfBlackBoxY;
    POINTFLOAT gmfptGlyphOrigin;
    FLOAT gmfCellIncX;
    FLOAT gmfCellIncY;
}

alias LPGLYPHMETRICSFLOAT = GLYPHMETRICSFLOAT*;

enum SM_CXSCREEN = 0;
enum SM_CYSCREEN = 1;

extern(Windows) nothrow @nogc
{
    // Errors
    DWORD GetLastError();
    
    // Process
    DWORD GetCurrentProcessId();
    VOID ExitProcess(uint uExitCode);
    
    // Dynamic libraries
    HMODULE LoadLibraryA(LPCSTR lpLibFileName);
    HMODULE LoadLibraryW(LPCWSTR lpLibFileName);
    FARPROC GetProcAddress(HMODULE hModule, LPCSTR lpProcName);
    BOOL FreeLibrary(HMODULE hModule);
    
    // Timer
    BOOL QueryPerformanceCounter(LARGE_INTEGER* lpPerformanceCount);
    BOOL QueryPerformanceFrequency(LARGE_INTEGER* lpFrequency);
    VOID Sleep(DWORD dwMilliseconds);
    
    // Threads
    void* CreateThread(
        const(SECURITY_ATTRIBUTES)* lpThreadAttributes,
        size_t dwStackSize,
        LPTHREAD_START_ROUTINE lpStartAddress,
        void* lpParameter,
        uint dwCreationFlags,
        uint* lpThreadId
    );
    uint WaitForMultipleObjects(
        uint nCount,
        const(HANDLE)* lpHandles,
        int bWaitAll,
        uint dwMilliseconds
    );
    int TerminateThread(const(void)* hThread, uint dwExitCode);
    int GetExitCodeThread(const(void)* hThread, uint* lpExitCode);
    VOID InitializeCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
    VOID EnterCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
    BOOL TryEnterCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
    VOID LeaveCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
    VOID DeleteCriticalSection(LPCRITICAL_SECTION lpCriticalSection);
    uint TlsAlloc();
    int TlsSetValue(uint index, void* value);
    void* TlsGetValue(uint index);
    int TlsFree(uint index);
    
    // Files
    HANDLE GetStdHandle(DWORD nStdHandle);
    BOOL CloseHandle(HANDLE hObject);
    HANDLE CreateFileW(
        const(WCHAR)* lpFileName,
        DWORD dwDesiredAccess,
        DWORD dwShareMode,
        void* lpSecurityAttributes,
        DWORD dwCreationDisposition,
        DWORD dwFlagsAndAttributes,
        HANDLE hTemplateFile);
    BOOL ReadFile(
        HANDLE hFile,
        void* lpBuffer,
        DWORD nNumberOfBytesToRead,
        DWORD* lpNumberOfBytesRead,
        void* lpOverlapped);
    BOOL WriteFile(
        HANDLE hFile,
        const(void)* lpBuffer,
        DWORD nNumberOfBytesToWrite,
        DWORD* lpNumberOfBytesWritten,
        void* lpOverlapped);
    BOOL SetFilePointerEx(
        HANDLE hFile,
        long liDistanceToMove,
        long* lpNewFilePointer,
        DWORD dwMoveMethod);
    BOOL FlushFileBuffers(HANDLE hFile);
    BOOL GetFileSizeEx(HANDLE hFile, long* lpFileSize);
    BOOL GetFileAttributesExW(const(wchar)* lpFileName, int fInfoLevelId, void* lpFileInformation);
    
    // Console
    BOOL SetConsoleCP(UINT wCodePageID);
    BOOL SetConsoleOutputCP(UINT wCodePageID);
    
    // Display and windows
    LONG_PTR SetWindowLongPtrW(HWND hWnd, int nIndex, LONG_PTR dwNewLong);
    LONG_PTR GetWindowLongPtrW(HWND hWnd, int nIndex);

    LRESULT DefWindowProcW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
    
    void PostQuitMessage(int nExitCode);

    HINSTANCE GetModuleHandleW(LPCWSTR lpModuleName);
    
    HCURSOR LoadCursorW(HINSTANCE hInstance, LPCWSTR lpCursorName);

    ATOM RegisterClass(const(WNDCLASS)* lpWndClass);
    ATOM RegisterClassW(const(WNDCLASSW)* lpWndClass);

    HWND CreateWindowExW(
        DWORD dwExStyle,
        LPCWSTR lpClassName,
        LPCWSTR lpWindowName,
        DWORD dwStyle,
        int X,
        int Y,
        int nWidth,
        int nHeight,
        HWND hWndParent,
        HMENU hMenu,
        HINSTANCE hInstance,
        void* lpParam
    );
    
    BOOL PeekMessageW(
        MSG* lpMsg,
        HWND hWnd,
        UINT wMsgFilterMin,
        UINT wMsgFilterMax,
        UINT wRemoveMsg
    );

    BOOL TranslateMessage(const(MSG)* lpMsg);

    LRESULT DispatchMessageW(const(MSG)* lpMsg);
    
    int ChoosePixelFormat(HDC hdc, const(PIXELFORMATDESCRIPTOR)* ppfd);
    BOOL SetPixelFormat(HDC hdc, int format, const(PIXELFORMATDESCRIPTOR)* ppfd);
    
    HDC GetDC(HWND hWnd);
    BOOL SwapBuffers(HDC unnamedParam1);
    
    uint GetStockObject(int fnObject);
    
    bool AdjustWindowRectEx(RECT* lpRect, uint dwStyle, bool bMenu, uint dwExStyle);
    
    int GetSystemMetrics(int nIndex);
}

alias LoadLibrary = LoadLibraryW;
alias GetFileAttributesEx = GetFileAttributesExW;
alias SetWindowLongPtr = SetWindowLongPtrW;
alias GetWindowLongPtr = GetWindowLongPtrW;
alias DefWindowProc = DefWindowProcW;
alias GetModuleHandle = GetModuleHandleW;
alias LoadCursor = LoadCursorW;
alias PeekMessage = PeekMessageW;
alias DispatchMessage = DispatchMessageW;
