/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.gl.gles20;

import rtld.gl.signatures;

__gshared
{
    f_glActiveTexture glActiveTexture;
    f_glAttachShader glAttachShader;
    f_glBindAttribLocation glBindAttribLocation;
    f_glBindBuffer glBindBuffer;
    f_glBindFramebuffer glBindFramebuffer;
    f_glBindRenderbuffer glBindRenderbuffer;
    f_glBindTexture glBindTexture;
    f_glBlendColor glBlendColor;
    f_glBlendEquation glBlendEquation;
    f_glBlendEquationSeparate glBlendEquationSeparate;
    f_glBlendFunc glBlendFunc;
    f_glBlendFuncSeparate glBlendFuncSeparate;
    f_glBufferData glBufferData;
    f_glBufferSubData glBufferSubData;
    f_glCheckFramebufferStatus glCheckFramebufferStatus;
    f_glClear glClear;
    f_glClearColor glClearColor;
    f_glClearDepthf glClearDepthf;
    f_glClearStencil glClearStencil;
    f_glColorMask glColorMask;
    f_glCompileShader glCompileShader;
    f_glCompressedTexImage2D glCompressedTexImage2D;
    f_glCompressedTexSubImage2D glCompressedTexSubImage2D;
    f_glCopyTexImage2D glCopyTexImage2D;
    f_glCopyTexSubImage2D glCopyTexSubImage2D;
    f_glCreateProgram glCreateProgram;
    f_glCreateShader glCreateShader;
    f_glCullFace glCullFace;
    f_glDeleteBuffers glDeleteBuffers;
    f_glDeleteFramebuffers glDeleteFramebuffers;
    f_glDeleteProgram glDeleteProgram;
    f_glDeleteRenderbuffers glDeleteRenderbuffers;
    f_glDeleteShader glDeleteShader;
    f_glDeleteTextures glDeleteTextures;
    f_glDepthFunc glDepthFunc;
    f_glDepthMask glDepthMask;
    f_glDepthRangef glDepthRangef;
    f_glDetachShader glDetachShader;
    f_glDisable glDisable;
    f_glDisableVertexAttribArray glDisableVertexAttribArray;
    f_glDrawArrays glDrawArrays;
    f_glDrawElements glDrawElements;
    f_glEnable glEnable;
    f_glEnableVertexAttribArray glEnableVertexAttribArray;
    f_glFinish glFinish;
    f_glFlush glFlush;
    f_glFramebufferRenderbuffer glFramebufferRenderbuffer;
    f_glFramebufferTexture2D glFramebufferTexture2D;
    f_glFrontFace glFrontFace;
    f_glGenBuffers glGenBuffers;
    f_glGenerateMipmap glGenerateMipmap;
    f_glGenFramebuffers glGenFramebuffers;
    f_glGenRenderbuffers glGenRenderbuffers;
    f_glGenTextures glGenTextures;
    f_glGetActiveAttrib glGetActiveAttrib;
    f_glGetActiveUniform glGetActiveUniform;
    f_glGetAttachedShaders glGetAttachedShaders;
    f_glGetAttribLocation glGetAttribLocation;
    f_glGetBooleanv glGetBooleanv;
    f_glGetBufferParameteriv glGetBufferParameteriv;
    f_glGetError glGetError;
    f_glGetFloatv glGetFloatv;
    f_glGetFramebufferAttachmentParameteriv glGetFramebufferAttachmentParameteriv;
    f_glGetIntegerv glGetIntegerv;
    f_glGetProgramiv glGetProgramiv;
    f_glGetProgramInfoLog glGetProgramInfoLog;
    f_glGetRenderbufferParameteriv glGetRenderbufferParameteriv;
    f_glGetShaderiv glGetShaderiv;
    f_glGetShaderInfoLog glGetShaderInfoLog;
    f_glGetShaderPrecisionFormat glGetShaderPrecisionFormat;
    f_glGetShaderSource glGetShaderSource;
    f_glGetString glGetString;
    f_glGetTexParameterfv glGetTexParameterfv;
    f_glGetTexParameteriv glGetTexParameteriv;
    f_glGetUniformfv glGetUniformfv;
    f_glGetUniformiv glGetUniformiv;
    f_glGetUniformLocation glGetUniformLocation;
    f_glGetVertexAttribfv glGetVertexAttribfv;
    f_glGetVertexAttribiv glGetVertexAttribiv;
    f_glGetVertexAttribPointerv glGetVertexAttribPointerv;
    f_glHint glHint;
    f_glIsBuffer glIsBuffer;
    f_glIsEnabled glIsEnabled;
    f_glIsFramebuffer glIsFramebuffer;
    f_glIsProgram glIsProgram;
    f_glIsRenderbuffer glIsRenderbuffer;
    f_glIsShader glIsShader;
    f_glIsTexture glIsTexture;
    f_glLineWidth glLineWidth;
    f_glLinkProgram glLinkProgram;
    f_glPixelStorei glPixelStorei;
    f_glPolygonOffset glPolygonOffset;
    f_glReadPixels glReadPixels;
    f_glReleaseShaderCompiler glReleaseShaderCompiler;
    f_glRenderbufferStorage glRenderbufferStorage;
    f_glSampleCoverage glSampleCoverage;
    f_glScissor glScissor;
    f_glShaderBinary glShaderBinary;
    f_glShaderSource glShaderSource;
    f_glStencilFunc glStencilFunc;
    f_glStencilFuncSeparate glStencilFuncSeparate;
    f_glStencilMask glStencilMask;
    f_glStencilMaskSeparate glStencilMaskSeparate;
    f_glStencilOp glStencilOp;
    f_glStencilOpSeparate glStencilOpSeparate;
    f_glTexImage2D glTexImage2D;
    f_glTexParameterf glTexParameterf;
    f_glTexParameterfv glTexParameterfv;
    f_glTexParameteri glTexParameteri;
    f_glTexParameteriv glTexParameteriv;
    f_glTexSubImage2D glTexSubImage2D;
    f_glUniform1f glUniform1f;
    f_glUniform1fv glUniform1fv;
    f_glUniform1i glUniform1i;
    f_glUniform1iv glUniform1iv;
    f_glUniform2f glUniform2f;
    f_glUniform2fv glUniform2fv;
    f_glUniform2i glUniform2i;
    f_glUniform2iv glUniform2iv;
    f_glUniform3f glUniform3f;
    f_glUniform3fv glUniform3fv;
    f_glUniform3i glUniform3i;
    f_glUniform3iv glUniform3iv;
    f_glUniform4f glUniform4f;
    f_glUniform4fv glUniform4fv;
    f_glUniform4i glUniform4i;
    f_glUniform4iv glUniform4iv;
    f_glUniformMatrix2fv glUniformMatrix2fv;
    f_glUniformMatrix3fv glUniformMatrix3fv;
    f_glUniformMatrix4fv glUniformMatrix4fv;
    f_glUseProgram glUseProgram;
    f_glValidateProgram glValidateProgram;
    f_glVertexAttrib1f glVertexAttrib1f;
    f_glVertexAttrib1fv glVertexAttrib1fv;
    f_glVertexAttrib2f glVertexAttrib2f;
    f_glVertexAttrib2fv glVertexAttrib2fv;
    f_glVertexAttrib3f glVertexAttrib3f;
    f_glVertexAttrib3fv glVertexAttrib3fv;
    f_glVertexAttrib4f glVertexAttrib4f;
    f_glVertexAttrib4fv glVertexAttrib4fv;
    f_glVertexAttribPointer glVertexAttribPointer;
    f_glViewport glViewport;
}
