/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.gl.gles30;

import rtld.gl.signatures;

__gshared
{
    f_glReadBuffer glReadBuffer;
    f_glDrawRangeElements glDrawRangeElements;
    f_glTexImage3D glTexImage3D;
    f_glTexSubImage3D glTexSubImage3D;
    f_glCopyTexSubImage3D glCopyTexSubImage3D;
    f_glCompressedTexImage3D glCompressedTexImage3D;
    f_glCompressedTexSubImage3D glCompressedTexSubImage3D;
    f_glGenQueries glGenQueries;
    f_glDeleteQueries glDeleteQueries;
    f_glIsQuery glIsQuery;
    f_glBeginQuery glBeginQuery;
    f_glEndQuery glEndQuery;
    f_glGetQueryiv glGetQueryiv;
    f_glGetQueryObjectuiv glGetQueryObjectuiv;
    f_glUnmapBuffer glUnmapBuffer;
    f_glGetBufferPointerv glGetBufferPointerv;
    f_glDrawBuffers glDrawBuffers;
    f_glUniformMatrix2x3fv glUniformMatrix2x3fv;
    f_glUniformMatrix3x2fv glUniformMatrix3x2fv;
    f_glUniformMatrix2x4fv glUniformMatrix2x4fv;
    f_glUniformMatrix4x2fv glUniformMatrix4x2fv;
    f_glUniformMatrix3x4fv glUniformMatrix3x4fv;
    f_glUniformMatrix4x3fv glUniformMatrix4x3fv;
    f_glBlitFramebuffer glBlitFramebuffer;
    f_glRenderbufferStorageMultisample glRenderbufferStorageMultisample;
    f_glFramebufferTextureLayer glFramebufferTextureLayer;
    f_glMapBufferRange glMapBufferRange;
    f_glFlushMappedBufferRange glFlushMappedBufferRange;
    f_glBindVertexArray glBindVertexArray;
    f_glDeleteVertexArrays glDeleteVertexArrays;
    f_glGenVertexArrays glGenVertexArrays;
    f_glIsVertexArray glIsVertexArray;
    f_glGetIntegeri_v glGetIntegeri_v;
    f_glBeginTransformFeedback glBeginTransformFeedback;
    f_glEndTransformFeedback glEndTransformFeedback;
    f_glBindBufferRange glBindBufferRange;
    f_glBindBufferBase glBindBufferBase;
    f_glTransformFeedbackVaryings glTransformFeedbackVaryings;
    f_glGetTransformFeedbackVarying glGetTransformFeedbackVarying;
    f_glVertexAttribIPointer glVertexAttribIPointer;
    f_glGetVertexAttribIuiv glGetVertexAttribIuiv;
    f_glVertexAttribI4i glVertexAttribI4i;
    f_glVertexAttribI4ui glVertexAttribI4ui;
    f_glVertexAttribI4iv glVertexAttribI4iv;
    f_glVertexAttribI4uiv glVertexAttribI4uiv;
    f_glGetUniformuiv glGetUniformuiv;
    f_glGetFragDataLocation glGetFragDataLocation;
    f_glUniform1ui glUniform1ui;
    f_glUniform2ui glUniform2ui;
    f_glUniform3ui glUniform3ui;
    f_glUniform4ui glUniform4ui;
    f_glUniform1uiv glUniform1uiv;
    f_glUniform2uiv glUniform2uiv;
    f_glUniform3uiv glUniform3uiv;
    f_glUniform4uiv glUniform4uiv;
    f_glClearBufferiv glClearBufferiv;
    f_glClearBufferuiv glClearBufferuiv;
    f_glClearBufferfv glClearBufferfv;
    f_glClearBufferfi glClearBufferfi;
    f_glGetStringi glGetStringi;
    f_glCopyBufferSubData glCopyBufferSubData;
    f_glGetUniformIndices glGetUniformIndices;
    f_glGetActiveUniformsiv glGetActiveUniformsiv;
    f_glGetUniformBlockIndex glGetUniformBlockIndex;
    f_glGetActiveUniformBlockiv glGetActiveUniformBlockiv;
    f_glGetActiveUniformBlockName glGetActiveUniformBlockName;
    f_glUniformBlockBinding glUniformBlockBinding;
    f_glDrawArraysInstanced glDrawArraysInstanced;
    f_glDrawElementsInstanced glDrawElementsInstanced;
    f_glFenceSync glFenceSync;
    f_glIsSync glIsSync;
    f_glDeleteSync glDeleteSync;
    f_glClientWaitSync glClientWaitSync;
    f_glWaitSync glWaitSync;
    f_glGetInteger64v glGetInteger64v;
    f_glGetSynciv glGetSynciv;
    f_glGetInteger64i_v glGetInteger64i_v;
    f_glGetBufferParameteri64v glGetBufferParameteri64v;
    f_glGenSamplers glGenSamplers;
    f_glDeleteSamplers glDeleteSamplers;
    f_glIsSampler glIsSampler;
    f_glBindSampler glBindSampler;
    f_glSamplerParameteri glSamplerParameteri;
    f_glSamplerParameteriv glSamplerParameteriv;
    f_glSamplerParameterf glSamplerParameterf;
    f_glSamplerParameterfv glSamplerParameterfv;
    f_glGetSamplerParameteriv glGetSamplerParameteriv;
    f_glGetSamplerParameterfv glGetSamplerParameterfv;
    f_glVertexAttribDivisor glVertexAttribDivisor;
    f_glBindTransformFeedback glBindTransformFeedback;
    f_glDeleteTransformFeedbacks glDeleteTransformFeedbacks;
    f_glGenTransformFeedbacks glGenTransformFeedbacks;
    f_glIsTransformFeedback glIsTransformFeedback;
    f_glPauseTransformFeedback glPauseTransformFeedback;
    f_glResumeTransformFeedback glResumeTransformFeedback;
    f_glGetProgramBinary glGetProgramBinary;
    f_glProgramBinary glProgramBinary;
    f_glProgramParameteri glProgramParameteri;
    f_glInvalidateFramebuffer glInvalidateFramebuffer;
    f_glTexStorage2D glTexStorage2D;
    f_glTexStorage3D glTexStorage3D;
    f_glGetInternalformativ glGetInternalformativ;
}
