/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.gl.signatures;

import rtld.gl.types;

extern(System) @nogc nothrow:

// GLES 2.0

alias f_glActiveTexture = void function(GLenum texture);
alias f_glAttachShader = void function(GLuint program, GLuint shader);
alias f_glBindAttribLocation = void function(GLuint program, GLuint index, const(GLchar)* name);
alias f_glBindBuffer = void function(GLenum target, GLuint buffer);
alias f_glBindFramebuffer = void function(GLenum target, GLuint framebuffer);
alias f_glBindRenderbuffer = void function(GLenum target, GLuint renderbuffer);
alias f_glBindTexture = void function(GLenum target, GLuint texture);
alias f_glBlendColor = void function(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
alias f_glBlendEquation = void function(GLenum mode);
alias f_glBlendEquationSeparate = void function(GLenum modeRGB, GLenum modeAlpha);
alias f_glBlendFunc = void function(GLenum sfactor, GLenum dfactor);
alias f_glBlendFuncSeparate = void function(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
alias f_glBufferData = void function(GLenum target, GLsizeiptr size, const(void)* data, GLenum usage);
alias f_glBufferSubData = void function(GLenum target, GLintptr offset, GLsizeiptr size, const(void)* data);
alias f_glCheckFramebufferStatus = GLenum function(GLenum target);
alias f_glClear = void function(GLenum mask);
alias f_glClearColor = void function(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
alias f_glClearDepthf = void function(GLfloat d);
alias f_glClearStencil = void function(GLint s);
alias f_glColorMask = void function(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
alias f_glCompileShader = void function(GLuint shader);
alias f_glCompressedTexImage2D = void function(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const(void)* data);
alias f_glCompressedTexSubImage2D = void function(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const(void)* data);
alias f_glCopyTexImage2D = void function(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
alias f_glCopyTexSubImage2D = void function(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
alias f_glCreateProgram = GLuint function();
alias f_glCreateShader = GLuint function(GLenum type);
alias f_glCullFace = void function(GLenum mode);
alias f_glDeleteBuffers = void function(GLsizei n, const(GLuint)* buffers);
alias f_glDeleteFramebuffers = void function(GLsizei n, const(GLuint)* framebuffers);
alias f_glDeleteProgram = void function(GLuint program);
alias f_glDeleteRenderbuffers = void function(GLsizei n, const(GLuint)* renderbuffers);
alias f_glDeleteShader = void function(GLuint shader);
alias f_glDeleteTextures = void function(GLsizei n, const(GLuint)* textures);
alias f_glDepthFunc = void function(GLenum func);
alias f_glDepthMask = void function(GLboolean flag);
alias f_glDepthRangef = void function(GLfloat n, GLfloat f);
alias f_glDetachShader = void function(GLuint program, GLuint shader);
alias f_glDisable = void function(GLenum cap);
alias f_glDisableVertexAttribArray = void function(GLuint index);
alias f_glDrawArrays = void function(GLenum mode, GLint first, GLsizei count);
alias f_glDrawElements = void function(GLenum mode, GLsizei count, GLenum type, const(void)* indices);
alias f_glEnable = void function(GLenum cap);
alias f_glEnableVertexAttribArray = void function(GLuint index);
alias f_glFinish = void function();
alias f_glFlush = void function();
alias f_glFramebufferRenderbuffer = void function(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
alias f_glFramebufferTexture2D = void function(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
alias f_glFrontFace = void function(GLenum mode);
alias f_glGenBuffers = void function(GLsizei n, GLuint* buffers);
alias f_glGenerateMipmap = void function(GLenum target);
alias f_glGenFramebuffers = void function(GLsizei n, GLuint* framebuffers);
alias f_glGenRenderbuffers = void function(GLsizei n, GLuint* renderbuffers);
alias f_glGenTextures = void function(GLsizei n, GLuint* textures);
alias f_glGetActiveAttrib = void function(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
alias f_glGetActiveUniform = void function(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
alias f_glGetAttachedShaders = void function(GLuint program, GLsizei maxCount, GLsizei* count, GLuint* shaders);
alias f_glGetAttribLocation = GLint function(GLuint program, const(GLchar)* name);
alias f_glGetBooleanv = void function(GLenum pname, GLboolean* data);
alias f_glGetBufferParameteriv = void function(GLenum target, GLenum pname, GLint* params);
alias f_glGetError = GLenum function();
alias f_glGetFloatv = void function(GLenum pname, GLfloat* data);
alias f_glGetFramebufferAttachmentParameteriv = void function(GLenum target, GLenum attachment, GLenum pname, GLint* params);
alias f_glGetIntegerv = void function(GLenum pname, GLint* data);
alias f_glGetProgramiv = void function(GLuint program, GLenum pname, GLint* params);
alias f_glGetProgramInfoLog = void function(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
alias f_glGetRenderbufferParameteriv = void function(GLenum target, GLenum pname, GLint* params);
alias f_glGetShaderiv = void function(GLuint shader, GLenum pname, GLint* params);
alias f_glGetShaderInfoLog = void function(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
alias f_glGetShaderPrecisionFormat = void function(GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision);
alias f_glGetShaderSource = void function(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* source);
alias f_glGetString = const(GLubyte)* function(GLenum name);
alias f_glGetTexParameterfv = void function(GLenum target, GLenum pname, GLfloat* params);
alias f_glGetTexParameteriv = void function(GLenum target, GLenum pname, GLint* params);
alias f_glGetUniformfv = void function(GLuint program, GLint location, GLfloat* params);
alias f_glGetUniformiv = void function(GLuint program, GLint location, GLint* params);
alias f_glGetUniformLocation = GLint function(GLuint program, const(GLchar)* name);
alias f_glGetVertexAttribfv = void function(GLuint index, GLenum pname, GLfloat* params);
alias f_glGetVertexAttribiv = void function(GLuint index, GLenum pname, GLint* params);
alias f_glGetVertexAttribPointerv = void function(GLuint index, GLenum pname, void** pointer);
alias f_glHint = void function(GLenum target, GLenum mode);
alias f_glIsBuffer = GLboolean function(GLuint buffer);
alias f_glIsEnabled = GLboolean function(GLenum cap);
alias f_glIsFramebuffer = GLboolean function(GLuint framebuffer);
alias f_glIsProgram = GLboolean function(GLuint program);
alias f_glIsRenderbuffer = GLboolean function(GLuint renderbuffer);
alias f_glIsShader = GLboolean function(GLuint shader);
alias f_glIsTexture = GLboolean function(GLuint texture);
alias f_glLineWidth = void function(GLfloat width);
alias f_glLinkProgram = void function(GLuint program);
alias f_glPixelStorei = void function(GLenum pname, GLint param);
alias f_glPolygonOffset = void function(GLfloat factor, GLfloat units);
alias f_glReadPixels = void function(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels);
alias f_glReleaseShaderCompiler = void function();
alias f_glRenderbufferStorage = void function(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
alias f_glSampleCoverage = void function(GLfloat value, GLboolean invert);
alias f_glScissor = void function(GLint x, GLint y, GLsizei width, GLsizei height);
alias f_glShaderBinary = void function(GLsizei count, const(GLuint)* shaders, GLenum binaryFormat, const(void)* binary, GLsizei length);
alias f_glShaderSource = void function(GLuint shader, GLsizei count, const(const(GLchar)*)* str, const(GLint)* length);
alias f_glStencilFunc = void function(GLenum func, GLint refValue, GLuint mask);
alias f_glStencilFuncSeparate = void function(GLenum face, GLenum func, GLint refValue, GLuint mask);
alias f_glStencilMask = void function(GLuint mask);
alias f_glStencilMaskSeparate = void function(GLenum face, GLuint mask);
alias f_glStencilOp = void function(GLenum fail, GLenum zfail, GLenum zpass);
alias f_glStencilOpSeparate = void function(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
alias f_glTexImage2D = void function(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const(void)* pixels);
alias f_glTexParameterf = void function(GLenum target, GLenum pname, GLfloat param);
alias f_glTexParameterfv = void function(GLenum target, GLenum pname, const(GLfloat)* params);
alias f_glTexParameteri = void function(GLenum target, GLenum pname, GLint param);
alias f_glTexParameteriv = void function(GLenum target, GLenum pname, const(GLint)* params);
alias f_glTexSubImage2D = void function(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const(void)* pixels);
alias f_glUniform1f = void function(GLint location, GLfloat v0);
alias f_glUniform1fv = void function(GLint location, GLsizei count, const(GLfloat)* value);
alias f_glUniform1i = void function(GLint location, GLint v0);
alias f_glUniform1iv = void function(GLint location, GLsizei count, const(GLint)* value);
alias f_glUniform2f = void function(GLint location, GLfloat v0, GLfloat v1);
alias f_glUniform2fv = void function(GLint location, GLsizei count, const(GLfloat)* value);
alias f_glUniform2i = void function(GLint location, GLint v0, GLint v1);
alias f_glUniform2iv = void function(GLint location, GLsizei count, const(GLint)* value);
alias f_glUniform3f = void function(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
alias f_glUniform3fv = void function(GLint location, GLsizei count, const(GLfloat)* value);
alias f_glUniform3i = void function(GLint location, GLint v0, GLint v1, GLint v2);
alias f_glUniform3iv = void function(GLint location, GLsizei count, const(GLint)* value);
alias f_glUniform4f = void function(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
alias f_glUniform4fv = void function(GLint location, GLsizei count, const(GLfloat)* value);
alias f_glUniform4i = void function(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
alias f_glUniform4iv = void function(GLint location, GLsizei count, const(GLint)* value);
alias f_glUniformMatrix2fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUniformMatrix3fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUniformMatrix4fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUseProgram = void function(GLuint program);
alias f_glValidateProgram = void function(GLuint program);
alias f_glVertexAttrib1f = void function(GLuint index, GLfloat x);
alias f_glVertexAttrib1fv = void function(GLuint index, const(GLfloat)* v);
alias f_glVertexAttrib2f = void function(GLuint index, GLfloat x, GLfloat y);
alias f_glVertexAttrib2fv = void function(GLuint index, const(GLfloat)* v);
alias f_glVertexAttrib3f = void function(GLuint index, GLfloat x, GLfloat y, GLfloat z);
alias f_glVertexAttrib3fv = void function(GLuint index, const(GLfloat)* v);
alias f_glVertexAttrib4f = void function(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
alias f_glVertexAttrib4fv = void function(GLuint index, const(GLfloat)* v);
alias f_glVertexAttribPointer = void function(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const(void)* pointer);
alias f_glViewport = void function(GLint x, GLint y, GLsizei width, GLsizei height);

// GLES 3.0

alias f_glReadBuffer = void function(GLenum src);
alias f_glDrawRangeElements = void function(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const(void)* indices);
alias f_glTexImage3D = void function(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const(void)* pixels);
alias f_glTexSubImage3D = void function(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const(void)* pixels);
alias f_glCopyTexSubImage3D = void function(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
alias f_glCompressedTexImage3D = void function(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const(void)* data);
alias f_glCompressedTexSubImage3D = void function(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const(void)* data);
alias f_glGenQueries = void function(GLsizei n, GLuint* ids);
alias f_glDeleteQueries = void function(GLsizei n, const(GLuint)* ids);
alias f_glIsQuery = GLboolean function(GLuint id);
alias f_glBeginQuery = void function(GLenum target, GLuint id);
alias f_glEndQuery = void function(GLenum target);
alias f_glGetQueryiv = void function(GLenum target, GLenum pname, GLint* params);
alias f_glGetQueryObjectuiv = void function(GLuint id, GLenum pname, GLuint* params);
alias f_glUnmapBuffer = GLboolean function(GLenum target);
alias f_glGetBufferPointerv = void function(GLenum target, GLenum pname, void** params);
alias f_glDrawBuffers = void function(GLsizei n, const(GLenum)* bufs);
alias f_glUniformMatrix2x3fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUniformMatrix3x2fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUniformMatrix2x4fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUniformMatrix4x2fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUniformMatrix3x4fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glUniformMatrix4x3fv = void function(GLint location, GLsizei count, GLboolean transpose, const(GLfloat)* value);
alias f_glBlitFramebuffer = void function(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
alias f_glRenderbufferStorageMultisample = void function(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
alias f_glFramebufferTextureLayer = void function(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
alias f_glMapBufferRange = void function(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
alias f_glFlushMappedBufferRange = void function(GLenum target, GLintptr offset, GLsizeiptr length);
alias f_glBindVertexArray = void function(GLuint array);
alias f_glDeleteVertexArrays = void function(GLsizei n, const(GLuint)* arrays);
alias f_glGenVertexArrays = void function(GLsizei n, GLuint* arrays);
alias f_glIsVertexArray = GLboolean function(GLuint array);
alias f_glGetIntegeri_v = void function(GLenum target, GLuint index, GLint* data);
alias f_glBeginTransformFeedback = void function(GLenum primitiveMode);
alias f_glEndTransformFeedback = void function();
alias f_glBindBufferRange = void function(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
alias f_glBindBufferBase = void function(GLenum target, GLuint index, GLuint buffer);
alias f_glTransformFeedbackVaryings = void function(GLuint program, GLsizei count, const(GLchar*)* varyings, GLenum bufferMode);
alias f_glGetTransformFeedbackVarying = void function(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLsizei* size, GLenum* type, GLchar* name);
alias f_glVertexAttribIPointer = void function(GLuint index, GLint size, GLenum type, GLsizei stride, const(void)* pointer);
alias f_glGetVertexAttribIiv = void function(GLuint index, GLenum pname, GLint* params);
alias f_glGetVertexAttribIuiv = void function(GLuint index, GLenum pname, GLuint* params);
alias f_glVertexAttribI4i = void function(GLuint index, GLint x, GLint y, GLint z, GLint w);
alias f_glVertexAttribI4ui = void function(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
alias f_glVertexAttribI4iv = void function(GLuint index, const(GLint)* v);
alias f_glVertexAttribI4uiv = void function(GLuint index, const(GLuint)* v);
alias f_glGetUniformuiv = void function(GLuint program, GLint location, GLuint* params);
alias f_glGetFragDataLocation = GLint function(GLuint program, const(GLchar)* name);
alias f_glUniform1ui = void function(GLint location, GLuint v0);
alias f_glUniform2ui = void function(GLint location, GLuint v0, GLuint v1);
alias f_glUniform3ui = void function(GLint location, GLuint v0, GLuint v1, GLuint v2);
alias f_glUniform4ui = void function(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
alias f_glUniform1uiv = void function(GLint location, GLsizei count, const(GLuint)* value);
alias f_glUniform2uiv = void function(GLint location, GLsizei count, const(GLuint)* value);
alias f_glUniform3uiv = void function(GLint location, GLsizei count, const(GLuint)* value);
alias f_glUniform4uiv = void function(GLint location, GLsizei count, const(GLuint)* value);
alias f_glClearBufferiv = void function(GLenum buffer, GLint drawbuffer, const(GLint)* value);
alias f_glClearBufferuiv = void function(GLenum buffer, GLint drawbuffer, const(GLuint)* value);
alias f_glClearBufferfv = void function(GLenum buffer, GLint drawbuffer, const(GLfloat)* value);
alias f_glClearBufferfi = void function(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
alias f_glGetStringi = const(GLubyte)* function(GLenum name, GLuint index);
alias f_glCopyBufferSubData = void function(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
alias f_glGetUniformIndices = void function(GLuint program, GLsizei uniformCount, const(GLchar*)* uniformNames, GLuint* uniformIndices);
alias f_glGetActiveUniformsiv = void function(GLuint program, GLsizei uniformCount, const(GLuint)* uniformIndices, GLenum pname, GLint* params);
alias f_glGetUniformBlockIndex = void function(GLuint program, const(GLchar)* uniformBlockName);
alias f_glGetActiveUniformBlockiv = void function(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint* params);
alias f_glGetActiveUniformBlockName = void function(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei* length, GLchar* uniformBlockName);
alias f_glUniformBlockBinding = void function(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
alias f_glDrawArraysInstanced = void function(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
alias f_glDrawElementsInstanced = void function(GLenum mode, GLsizei count, GLenum type, const(void)* indices, GLsizei instancecount);
alias f_glFenceSync = GLsync function(GLenum condition, GLbitfield flags);
alias f_glIsSync = GLboolean function(GLsync sync);
alias f_glDeleteSync = void function(GLsync sync);
alias f_glClientWaitSync = GLenum function(GLsync sync, GLbitfield flags, GLuint64 timeout);
alias f_glWaitSync = void function(GLsync sync, GLbitfield flags, GLuint64 timeout);
alias f_glGetInteger64v = void function(GLenum pname, GLint64* data);
alias f_glGetSynciv = void function(GLsync sync, GLenum pname, GLsizei count, GLsizei* length, GLint* values);
alias f_glGetInteger64i_v = void function(GLenum target, GLuint index, GLint64* data);
alias f_glGetBufferParameteri64v = void function(GLenum target, GLenum pname, GLint64* params);
alias f_glGenSamplers = void function(GLsizei count, GLuint* samplers);
alias f_glDeleteSamplers = void function(GLsizei count, const(GLuint)* samplers);
alias f_glIsSampler = GLboolean function(GLuint sampler);
alias f_glBindSampler = void function(GLuint unit, GLuint sampler);
alias f_glSamplerParameteri = void function(GLuint sampler, GLenum pname, GLint param);
alias f_glSamplerParameteriv = void function(GLuint sampler, GLenum pname, const(GLint)* param);
alias f_glSamplerParameterf = void function(GLuint sampler, GLenum pname, GLfloat param);
alias f_glSamplerParameterfv = void function(GLuint sampler, GLenum pname, const(GLfloat)* param);
alias f_glGetSamplerParameteriv = void function(GLuint sampler, GLenum pname, GLint* params);
alias f_glGetSamplerParameterfv = void function(GLuint sampler, GLenum pname, GLfloat* params);
alias f_glVertexAttribDivisor = void function(GLuint index, GLuint divisor);
alias f_glBindTransformFeedback = void function(GLenum target, GLuint id);
alias f_glDeleteTransformFeedbacks = void function(GLsizei n, const(GLuint)* ids);
alias f_glGenTransformFeedbacks = void function(GLsizei n, GLuint* ids);
alias f_glIsTransformFeedback = GLboolean function(GLuint id);
alias f_glPauseTransformFeedback = void function();
alias f_glResumeTransformFeedback = void function();
alias f_glGetProgramBinary = void function(GLuint program, GLsizei bufSize, GLsizei* length, GLenum* binaryFormat, void* binary);
alias f_glProgramBinary = void function(GLuint program, GLenum binaryFormat, const(void)* binary, GLsizei length);
alias f_glProgramParameteri = void function(GLuint program, GLenum pname, GLint value);
alias f_glInvalidateFramebuffer = void function(GLenum target, GLsizei numAttachments, const(GLenum)* attachments);
alias f_glInvalidateSubFramebuffer = void function(GLenum target, GLsizei numAttachments, const(GLenum)* attachments, GLint x, GLint y, GLsizei width, GLsizei height);
alias f_glTexStorage2D = void function(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
alias f_glTexStorage3D = void function(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
alias f_glGetInternalformativ = void function(GLenum target, GLenum internalformat, GLenum pname, GLsizei count, GLint* params);
