/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module object;

import rtld.core.io;
import rtld.core.traits;
import rtld.core.process;
import rtld.core.errors;
import rtld.core.memory;
import rtld.hash.xxhash64;

version(GNU)
{
}
else version(X86_64)
{
    version(DigitalMars) version = WithArgTypes;
    else version(Windows) { }
    else version = WithArgTypes;
}
else version(AArch64)
{
    version(DigitalMars) version = WithArgTypes;
    else version(OSX) {}
    else version(iOS) {}
    else version(TVOS) {}
    else version(WatchOS) {}
    else version = WithArgTypes;
}

alias size_t = typeof(int.init.sizeof);
alias ptrdiff_t = typeof(cast(void*)0 - cast(void*)0);
alias string = immutable(char)[];
alias wstring = immutable(wchar)[];
alias noreturn = typeof(*null);

enum immutable(void)* rtinfoNoPointers  = null;
enum immutable(void)* rtinfoHasPointers = cast(void*)1;

struct Interface
{
    TypeInfo_Class classinfo;
    void*[] vtbl;
    size_t offset;
}

struct OffsetTypeInfo
{
    size_t offset;
    TypeInfo ti;
}

class Object
{
    string toString()
    {
        return typeid(this).name;
    }
    
    size_t toHash() nothrow
    {
        return cast(size_t)cast(void*)this; // address-based
    }
    
    int opCmp(Object o)
    {
        return 0;
    }
    
    bool opEquals(Object o)
    {
        return this is o;
    }
}

class TypeInfo
{
    override string toString() const @safe nothrow
    {
        return typeid(this).name;
    }

    override size_t toHash() const nothrow
    {
        return xxHash64(this.toString(), 0);
    }

    override int opCmp(Object rhs)
    {
        return 0;
    }

    override bool opEquals(Object o)
    {
        return opEquals(cast(TypeInfo) o);
    }

    bool opEquals(const TypeInfo ti) @safe nothrow const
    {
        if (this is ti)
            return true;
        return ti && this.toString() == ti.toString();
    }

    size_t getHash(scope const void* p) @trusted nothrow const
    {
        return 0;
    }

    bool equals(in void* p1, in void* p2) const { return p1 == p2; }

    int compare(in void* p1, in void* p2) const { return _xopCmp(p1, p2); }

    @property size_t tsize() nothrow pure const @safe @nogc { return 0; }

    void swap(void* p1, void* p2) const
    {
        size_t remaining = tsize;
        if ((cast(size_t) p1 | cast(size_t) p2) % (void*).alignof == 0)
        {
            while (remaining >= (void*).sizeof)
            {
                void* tmp = *cast(void**) p1;
                *cast(void**) p1 = *cast(void**) p2;
                *cast(void**) p2 = tmp;
                p1 += (void*).sizeof;
                p2 += (void*).sizeof;
                remaining -= (void*).sizeof;
            }
        }
        for (size_t i = 0; i < remaining; i++)
        {
            byte t = (cast(byte *)p1)[i];
            (cast(byte*)p1)[i] = (cast(byte*)p2)[i];
            (cast(byte*)p2)[i] = t;
        }
    }

    @property inout(TypeInfo) next() nothrow pure inout @nogc { return null; }

    version (LDC)
    {
        const(void)[] initializer() nothrow pure const @trusted @nogc
        {
            return (cast(const(void)*) null)[0 .. typeof(null).sizeof];
        }
    }
    else
    {
        abstract const(void)[] initializer() nothrow pure const @safe @nogc;
    }

    @property uint flags() nothrow pure const @safe @nogc { return 0; }

    const(OffsetTypeInfo)[] offTi() const { return null; }
    void destroy(void* p) const {}
    void postblit(void* p) const {}

    @property size_t talign() nothrow pure const @safe @nogc { return tsize; }

    version(WithArgTypes) int argTypes(out TypeInfo arg1, out TypeInfo arg2) @safe nothrow
    {
        arg1 = this;
        return 0;
    }

    @property immutable(void)* rtInfo() nothrow pure const @trusted @nogc
    {
        return rtinfoHasPointers;
    }
}

class TypeInfo_Const : TypeInfo
{
    TypeInfo base;
}

class TypeInfo_Invariant : TypeInfo_Const {}   // immutable(T)
class TypeInfo_Shared    : TypeInfo_Const {}   // shared(T)
class TypeInfo_Inout     : TypeInfo_Const {}   // inout(T)

class TypeInfo_Class: TypeInfo
{
    byte[] m_init;
    string name;
    void*[] vtbl;
    Interface[] interfaces;
    TypeInfo_Class base;
    void* destructor;
    void function(Object) classInvariant;
    enum ClassFlags: ushort
    {
        isCOMclass = 0x1,
        noPointers = 0x2,
        hasOffTi = 0x4,
        hasCtor = 0x8,
        hasGetMembers = 0x10,
        hasTypeInfo = 0x20,
        isAbstract = 0x40,
        isCPPclass = 0x80,
        hasDtor = 0x100,
        hasNameSig = 0x200,
    }
    ClassFlags m_flags;
    ushort depth;
    void* deallocator;
    OffsetTypeInfo[] m_offTi;
    void function(Object) defaultConstructor;
    immutable(void)* m_RTInfo;
    override @property immutable(void)* rtInfo() const { return m_RTInfo; }
    uint[4] nameSig;
}

class TypeInfo_Interface : TypeInfo
{
    TypeInfo_Class info;
}

alias ClassInfo = TypeInfo_Class;

class TypeInfoGeneric(T, Base = T): TypeInfo
{
    override @property size_t tsize() nothrow pure const @safe @nogc
    {
        return T.sizeof;
    }
    
    override @property inout(TypeInfo) next() nothrow pure inout @nogc
    {
        return cast(inout)typeid(T);
    }
}

class TypeInfo_v : TypeInfoGeneric!ubyte
{
    const nothrow pure @trusted:

    override string toString() const @safe { return "void"; }

    override size_t getHash(scope const void* p)
    {
        return 0;
    }

    override @property uint flags()
    {
        return 1;
    }
}
class TypeInfo_h : TypeInfoGeneric!ubyte {}
class TypeInfo_b: TypeInfoGeneric!(bool, ubyte) {}
class TypeInfo_g: TypeInfoGeneric!(byte, ubyte) {}
class TypeInfo_a: TypeInfoGeneric!(char, ubyte) {}
class TypeInfo_t: TypeInfoGeneric!ushort {}
class TypeInfo_s: TypeInfoGeneric!(short, ushort) {}
class TypeInfo_u: TypeInfoGeneric!(wchar, ushort) {}
class TypeInfo_w: TypeInfoGeneric!(dchar, uint) {}
class TypeInfo_k: TypeInfoGeneric!uint {}
class TypeInfo_i: TypeInfoGeneric!(int, uint) {}
class TypeInfo_m: TypeInfoGeneric!ulong {}
class TypeInfo_l: TypeInfoGeneric!(long, ulong) {}
static if (is(cent)) class TypeInfo_zi: TypeInfoGeneric!cent {}
static if (is(ucent)) class TypeInfo_zk: TypeInfoGeneric!ucent {}
class TypeInfo_f: TypeInfoGeneric!float {}
class TypeInfo_d: TypeInfoGeneric!double {}
class TypeInfo_e: TypeInfoGeneric!real {}

class TypeInfo_Array: TypeInfo
{
    override string toString() const { return "[]"; }

    /*
    // TODO
    override bool opEquals(Object o)
    {
        if (this is o)
            return true;
        auto c = cast(const TypeInfo_Array)o;
        return c && this.value == c.value;
    }
    */
    
    /*
    // TODO
    override size_t getHash(scope const void* p) @trusted const
    {
        void[] a = *cast(void[]*)p;
        return getArrayHash(value, a.ptr, a.length);
    }
    */

    override bool equals(in void* p1, in void* p2) const
    {
        void[] a1 = *cast(void[]*)p1;
        void[] a2 = *cast(void[]*)p2;
        if (a1.length != a2.length)
            return false;
        size_t sz = value.tsize;
        for (size_t i = 0; i < a1.length; i++)
        {
            if (!value.equals(a1.ptr + i * sz, a2.ptr + i * sz))
                return false;
        }
        return true;
    }

    override int compare(in void* p1, in void* p2) const
    {
        void[] a1 = *cast(void[]*)p1;
        void[] a2 = *cast(void[]*)p2;
        size_t sz = value.tsize;
        size_t len = a1.length;

        if (a2.length < len)
            len = a2.length;
        for (size_t u = 0; u < len; u++)
        {
            immutable int result = value.compare(a1.ptr + u * sz, a2.ptr + u * sz);
            if (result)
                return result;
        }
        return (a1.length > a2.length) - (a1.length < a2.length);
    }

    override @property size_t tsize() nothrow pure const
    {
        return (void[]).sizeof;
    }

    override const(void)[] initializer() const @trusted
    {
        return (cast(void *)null)[0 .. (void[]).sizeof];
    }

    override void swap(void* p1, void* p2) const
    {
        void[] tmp = *cast(void[]*)p1;
        *cast(void[]*)p1 = *cast(void[]*)p2;
        *cast(void[]*)p2 = tmp;
    }

    TypeInfo value;

    override @property uint flags() nothrow pure const { return 1; }

    override @property size_t talign() nothrow pure const
    {
        return (void[]).alignof;
    }

    version(WithArgTypes) override int argTypes(out TypeInfo arg1, out TypeInfo arg2)
    {
        arg1 = typeid(size_t);
        arg2 = typeid(void*);
        return 0;
    }

    //override @property immutable(void)* rtInfo() nothrow pure const @safe { return RTInfo!(void[]); }
}

class TypeInfoArrayGeneric(T, Base = T): TypeInfo_Array
{
    override @property inout(TypeInfo) next() nothrow pure inout @nogc
    {
        return cast(inout)typeid(T);
    }
}

class TypeInfo_Ah: TypeInfoArrayGeneric!ubyte {}
class TypeInfo_Ab: TypeInfoArrayGeneric!(bool, ubyte) {}
class TypeInfo_Ag: TypeInfoArrayGeneric!(byte, ubyte) {}
class TypeInfo_Aa: TypeInfoArrayGeneric!(char, ubyte) {}
class TypeInfo_Axa: TypeInfoArrayGeneric!(const char) {}
class TypeInfo_Aya: TypeInfoArrayGeneric!(immutable char)
{
    override string toString() const { return "immutable(char)[]"; }
}
class TypeInfo_At: TypeInfoArrayGeneric!ushort {}
class TypeInfo_As: TypeInfoArrayGeneric!(short, ushort) {}
class TypeInfo_Au: TypeInfoArrayGeneric!(wchar, ushort) {}
class TypeInfo_Ak: TypeInfoArrayGeneric!uint {}
class TypeInfo_Ai: TypeInfoArrayGeneric!(int, uint) {}
class TypeInfo_Aw: TypeInfoArrayGeneric!(dchar, uint) {}
class TypeInfo_Am: TypeInfoArrayGeneric!ulong {}
class TypeInfo_Al: TypeInfoArrayGeneric!(long, ulong) {}
class TypeInfo_Af: TypeInfoArrayGeneric!float {}
class TypeInfo_Ad: TypeInfoArrayGeneric!double {}
class TypeInfo_Ae: TypeInfoArrayGeneric!real {}

class TypeInfo_Av: TypeInfo_Ah
{
    override string toString() const { return "void[]"; }

    override @property inout(TypeInfo) next() inout
    {
        return cast(inout) typeid(void);
    }

    unittest
    {
        assert(typeid(void[]).toString == "void[]");
        assert(typeid(void[]).next == typeid(void));
    }
}

class TypeInfo_n : TypeInfo
{
    const: pure: @nogc: nothrow: @safe:
    override string toString() { return "typeof(null)"; }
    override size_t getHash(scope const void*) { return 0; }
    override bool equals(in void*, in void*) { return true; }
    override int compare(in void*, in void*) { return 0; }
    override @property size_t tsize() { return typeof(null).sizeof; }
    override const(void)[] initializer() @trusted { return (cast(void*)null)[0..size_t.sizeof]; }
    override void swap(void*, void*) {}
    override @property immutable(void)* rtInfo() { return rtinfoNoPointers; }
}

class TypeInfo_Pointer: TypeInfo
{
    TypeInfo m_next;
}

class TypeInfo_StaticArray: TypeInfo
{
    TypeInfo value;
    size_t len;
}

class TypeInfo_Struct: TypeInfo
{
    override string toString() const { return name; }

    override size_t toHash() const
    {
        return xxHash64(this.mangledName, 0);
    }

    override bool opEquals(Object o)
    {
        if (this is o)
            return true;
        auto s = cast(const TypeInfo_Struct)o;
        return s && this.mangledName == s.mangledName;
    }

    override size_t getHash(scope const void* p) @trusted pure nothrow const
    {
        assert(p);
        if (xtoHash)
        {
            return (*xtoHash)(p);
        }
        else
        {
            return xxHash64(p[0..initializer().length], 0);
        }
    }

    override bool equals(in void* p1, in void* p2) @trusted pure nothrow const
    {
        import core.stdc.string : memcmp;

        if (!p1 || !p2)
            return false;
        else if (xopEquals)
        {
            const dg = _memberFunc(p1, xopEquals);
            return dg.xopEquals(p2);
        }
        else if (p1 == p2)
            return true;
        else
            return memcmp(p1, p2, initializer().length) == 0;
    }

    override int compare(in void* p1, in void* p2) @trusted pure nothrow const
    {
        import core.stdc.string : memcmp;

        if (p1 != p2)
        {
            if (p1)
            {
                if (!p2)
                    return true;
                else if (xopCmp)
                {
                    const dg = _memberFunc(p1, xopCmp);
                    return dg.xopCmp(p2);
                }
                else
                    return memcmp(p1, p2, initializer().length);
            }
            else
                return -1;
        }
        return 0;
    }

    override @property size_t tsize() nothrow pure const
    {
        return initializer().length;
    }

    override const(void)[] initializer() nothrow pure const @safe
    {
        return m_init;
    }

    override @property uint flags() nothrow pure const { return m_flags; }

    override @property size_t talign() nothrow pure const { return m_align; }

    final override void destroy(void* p) const
    {
        if (xdtor)
        {
            if (m_flags & StructFlags.isDynamicType)
                (*xdtorti)(p, this);
            else
                (*xdtor)(p);
        }
    }

    override void postblit(void* p) const
    {
        if (xpostblit)
            (*xpostblit)(p);
    }

    string mangledName;
    
    final @property string name() pure nothrow const @trusted
    {
        /*
        import core.demangle : demangleType;

        if (mangledName is null) // e.g., opaque structs
            return null;

        const key = cast(const void*) this; // faster lookup than TypeInfo_Struct, at the cost of potential duplicates per binary
        static string[typeof(key)] demangledNamesCache; // per thread

        // not nothrow:
        //return demangledNamesCache.require(key, cast(string) demangleType(mangledName));

        if (auto pDemangled = key in demangledNamesCache)
            return *pDemangled;

        const demangled = cast(string) demangleType(mangledName);
        demangledNamesCache[key] = demangled;
        return demangled;
        */
        
        return mangledName;
    }

    void[] m_init;

    @safe pure nothrow
    {
        size_t   function(in void*)           xtoHash;
        bool     function(in void*, in void*) xopEquals;
        int      function(in void*, in void*) xopCmp;
        string   function(in void*)           xtoString;

        enum StructFlags : uint
        {
            hasPointers = 0x1,
            isDynamicType = 0x2,
        }
        StructFlags m_flags;
    }
    union
    {
        void function(void*)                xdtor;
        void function(void*, const TypeInfo_Struct ti) xdtorti;
    }
    void function(void*)                    xpostblit;

    uint m_align;

    override @property immutable(void)* rtInfo() nothrow pure const @safe { return m_RTInfo; }

    version (WithArgTypes)
    {
        override int argTypes(out TypeInfo arg1, out TypeInfo arg2)
        {
            arg1 = m_arg1;
            arg2 = m_arg2;
            return 0;
        }
        TypeInfo m_arg1;
        TypeInfo m_arg2;
    }
    immutable(void)* m_RTInfo;

    private struct _memberFunc
    {
        union
        {
            struct // delegate
            {
                const void* ptr;
                const void* funcptr;
            }
            @safe pure nothrow
            {
                bool delegate(in void*) xopEquals;
                int delegate(in void*) xopCmp;
            }
        }
    }
}

class TypeInfo_AssociativeArray: TypeInfo
{
    TypeInfo value;
    TypeInfo key;
}

class TypeInfo_Vector: TypeInfo
{
    TypeInfo base;
}

class TypeInfo_Function: TypeInfo
{
    TypeInfo next;
    string deco;
}

class TypeInfo_Delegate: TypeInfo
{
    TypeInfo next;
    string deco;
}

class TypeInfo_Enum: TypeInfo
{
    TypeInfo base;
    string name;
    void[] m_init;
}

class TypeInfo_Tuple: TypeInfo
{
    TypeInfo[] elements;
}

extern(C)
{
    bool _xopEquals(const(void)* p1, const(void)* p2) @nogc nothrow { return p1 == p2; }
    int _xopCmp(const(void)* p1, const(void)* p2) @nogc nothrow { return 0; }
    
    int _adEq2(void[] a1, void[] a2, TypeInfo ti)
    {
        if (a1.length != a2.length)
            return 0;

        import rtld.libc.string: memcmp;
        return memcmp(a1.ptr, a2.ptr, a1.length * ti.tsize()) == 0;
    }
    
    void[] _d_newarrayU(const TypeInfo ti, size_t length)
    {
        auto tiArray = cast(TypeInfo_Array)ti;
        auto elem_ti = ti.next;
        const size_t totalSize = length * elem_ti.tsize;

        if (totalSize == 0)
            return [];

        void[] result = New(totalSize);
        result = result.ptr[0..length];
        return result;
    }
    
    // TODO: _d_newarrayT
    
    void _d_array_slice_copy(void* dst, size_t dstlen, void* src, size_t srclen, size_t elemsz) nothrow @nogc
    {
        if (dstlen != srclen)
            sliceLengthMismatchError(dstlen, srclen);

        if (dstlen == 0 || dst is src)
            return;

        size_t totalSize = dstlen * elemsz;

        ubyte* d = cast(ubyte*) dst;
        const(ubyte)* s = cast(const(ubyte)*) src;

        if ((totalSize & (size_t.sizeof - 1)) == 0)
        {
            size_t* dW = cast(size_t*) dst;
            const(size_t)* sW = cast(const(size_t)*) src;
            size_t words = totalSize / size_t.sizeof;
            for (size_t i = 0; i < words; i++)
                dW[i] = sW[i];
        }
        else
        {
            for (size_t i = 0; i < totalSize; i++)
                d[i] = s[i];
        }
    }
    
    bool _d_enter_cleanup(void* exceptionObject) pure @nogc nothrow @trusted
    {
        return true;
    }
    
    void _d_leave_cleanup(void* cleanupContext) pure @nogc nothrow @trusted
    {
    }

    void _d_callinterfacector(void* p) @nogc nothrow {}
    void _d_callinterfacedtor(void* p) @nogc nothrow {}
    
    To _d_cast(To, From)(From o) @trusted
        if ((is(From == class) || is(From == interface)) &&
            (is(To   == class) || is(To   == interface)))
    {
        if (o is null)
            return null;

        Object obj = cast(Object) o;

        alias U = Unqual!To;
        static if (is(U == interface))
            auto target = (cast(TypeInfo_Interface) cast(void*) typeid(U)).info;
        else
            auto target = cast(TypeInfo_Class) cast(void*) typeid(U);

        size_t offset = 0;
        if (_d_isbaseof2(typeid(obj), target, offset))
            return cast(To)(cast(void*) obj + offset);
        return null;
    }
    
    Object _d_class_cast(Object o, ClassInfo c)
    {
        if (!o)
            return null;

        ClassInfo ci = o.classinfo;
        
        while (ci)
        {
            if (ci is c)
                return o;
            ci = ci.base;
        }
        
        return null;
    }
    
    TTo[] __ArrayCast(TFrom, TTo)(return scope TFrom[] from) nothrow @nogc @trusted
    {
        if (from.length == 0)
            return null;

        size_t fromSize = from.length * TFrom.sizeof;

        if (fromSize % TTo.sizeof != 0)
            error("Array cast size mismatch: total bytes do not divide evenly by target type size");

        size_t toLength = fromSize / TTo.sizeof;

        auto ptr = cast(TTo*)from.ptr;
        return ptr[0..toLength];
    }

    void _d_assert(string file, uint line) @nogc nothrow
    {
        assertionError(file, line);
    }
    
    void _d_assertp(immutable(char)* pfile, uint line) @nogc nothrow
    {
        import rtld.libc.string: strlen;
        string file;
        if (pfile !is null)
            file = pfile[0..strlen(pfile)];
        else
            file = "unknown";
        assertionError(file, line);
    }

    void _d_assert_msg(string msg, string file, uint line) @nogc nothrow
    {
        assertionErrorMsg(file, line, msg);
    }
    
    void __switch_error()(string file = __FILE__, size_t line = __LINE__) @trusted
    {
        switchError(file, line);
    }

    void _d_arraybounds(string file, uint line) @nogc nothrow
    {
        arrayBoundsSimpleError(file, line);
    }

    void _d_arrayboundsp(immutable(char*) pfile, uint line) @nogc nothrow
    {
        import rtld.libc.string: strlen;
        string file;
        if (pfile !is null)
            file = pfile[0..strlen(pfile)];
        else
            file = "unknown";
        arrayBoundsSimpleError(file, line);
    }

    void _d_arraybounds_index(string file, uint line, size_t index, size_t length) @nogc nothrow
    {
        exit(1);
        arrayIndexError(file, line, index, length);
    }
    
    void _d_arraybounds_indexp(immutable(char*) pfile, uint line, size_t index, size_t length) @nogc nothrow
    {
        import rtld.libc.string: strlen;
        string file;
        if (pfile !is null)
            file = pfile[0..strlen(pfile)];
        else
            file = "unknown";
        arrayIndexError(file, line, index, length);
    }
    
    void _d_arraybounds_slice(string file, uint line, size_t lower, size_t upper, size_t length) @nogc nothrow
    {
        arrayBoundsSliceError(file, line, lower, upper, length);
    }
    
    void _d_arraybounds_slicep(immutable(char*) pfile, uint line, size_t lower, size_t upper, size_t length) @nogc nothrow
    {
        import rtld.libc.string: strlen;
        string file;
        if (pfile !is null)
            file = pfile[0..strlen(pfile)];
        else
            file = "unknown";
        arrayBoundsSliceError(file, line, lower, upper, length);
    }
    
    void* _d_eh_personality = null;
    
    void _Unwind_Resume(void* exception_object) @nogc nothrow
    {
        exit(1);
    }

    void* _memsetFloat(void* p, float value, size_t count)
    {
        float* fp = cast(float*)p;
        for (size_t i = 0; i < count; i++)
        {
            fp[i] = value;
        }
        return p;
    }

    void* _memset128ii(void* p, ulong qword_value, size_t count)
    {
        ulong* lp = cast(ulong*)p;
        for (size_t i = 0; i < count * 2; i += 2)
        {
            lp[i] = qword_value;
            lp[i + 1] = qword_value;
        }
        return p;
    }
}

void* _d_arrayliteralTX(T)(size_t length)
{
    const size_t allocsize = length * T.sizeof;
    if (allocsize == 0)
        return null;
    void[] buffer = New(allocsize);
    return buffer.ptr;
}

template __supportsClassInfo(T)
{
    static if (is(T == class))
        enum __supportsClassInfo = true;
    else
        enum __supportsClassInfo = false;
}

private bool _d_isbaseof2(scope TypeInfo_Class oc, scope const TypeInfo_Class c,
                          scope ref size_t offset) @safe pure nothrow @nogc
{
    if (oc is c)
        return true;

    do
    {
        if (oc.base is c)
            return true;

        foreach (iface; oc.interfaces)
        {
            if (iface.classinfo is c || _d_isbaseof2(iface.classinfo, c, offset))
            {
                offset += iface.offset;
                return true;
            }
        }
        oc = oc.base;
    }
    while (oc !is null);

    return false;
}

bool __equals(T)(in T[] a, in T[] b)
{
    if (a.length != b.length)
        return false;
        
    for (size_t i = 0; i < a.length; i++)
    {
        if (a[i] != b[i])
            return false;
    }
    return true;
}
