/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.sys.posix.dlfcn;

version(Posix):

version(linux)
{
    enum int RTLD_LAZY     = 0x00001;
    enum int RTLD_NOW      = 0x00002;
    enum int RTLD_NOLOAD   = 0x00004;
    enum int RTLD_DEEPBIND = 0x00008;
    enum int RTLD_GLOBAL   = 0x00100;
    enum int RTLD_LOCAL    = 0x00000;
    enum int RTLD_NODELETE = 0x01000;

    enum void* RTLD_DEFAULT = cast(void*)0;
    enum void* RTLD_NEXT    = cast(void*)-1;
}
else version(Android)
{
    enum int RTLD_LAZY     = 0x00001;
    enum int RTLD_NOW      = 0x00002;
    enum int RTLD_NOLOAD   = 0x00004;
    enum int RTLD_GLOBAL   = 0x00100;
    enum int RTLD_LOCAL    = 0x00000;
    enum int RTLD_NODELETE = 0x01000;

    enum void* RTLD_DEFAULT = cast(void*)0;
    enum void* RTLD_NEXT    = cast(void*)-1;
}
else version(OSX)
{
    enum int RTLD_LAZY     = 0x1;
    enum int RTLD_NOW      = 0x2;
    enum int RTLD_LOCAL    = 0x4;
    enum int RTLD_GLOBAL   = 0x8;
    enum int RTLD_NOLOAD   = 0x10;
    enum int RTLD_NODELETE = 0x80;
    enum int RTLD_FIRST    = 0x100;

    enum void* RTLD_NEXT      = cast(void*) -1;
    enum void* RTLD_DEFAULT   = cast(void*) -2;
    enum void* RTLD_SELF      = cast(void*) -3;
    enum void* RTLD_MAIN_ONLY = cast(void*) -5;
}
else version(FreeBSD)
{
    enum int RTLD_LAZY     = 1;
    enum int RTLD_NOW      = 2;
    enum int RTLD_GLOBAL   = 0x100;
    enum int RTLD_LOCAL    = 0;
    enum int RTLD_TRACE    = 0x200;
    enum int RTLD_NODELETE = 0x01000;
    enum int RTLD_NOLOAD   = 0x02000;

    enum void* RTLD_DEFAULT = cast(void*) -2;
    enum void* RTLD_NEXT    = cast(void*) -1;
}
else version (Posix) 
{
    enum int RTLD_LAZY     = 1;
    enum int RTLD_NOW      = 2;
    enum int RTLD_GLOBAL   = 0x100;
    enum int RTLD_LOCAL    = 0;
    
    enum void* RTLD_DEFAULT = cast(void*) 0;
    enum void* RTLD_NEXT    = cast(void*) -1;
}

struct Dl_info
{
    const(char)* dli_fname;
    void*        dli_fbase;
    const(char)* dli_sname;
    void*        dli_saddr;
}

extern(C) nothrow @nogc
{
    void*  dlopen(const(char)* file, int mode);
    int    dlclose(void* handle);
    void*  dlsym(void* handle, const(char)* name);
    int    dladdr(const(void)* addr, Dl_info* info);
    char*  dlerror();
}
