/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.sys.posix.fcntl;

version(Posix):

public import rtld.sys.posix.sys.types;

enum int O_RDONLY = 0x0000;
enum int O_WRONLY = 0x0001;
enum int O_RDWR   = 0x0002;

version(linux)
{
    enum int O_CREAT   = 0x0040;
    enum int O_EXCL    = 0x0080;
    enum int O_TRUNC   = 0x0200;
    enum int O_APPEND  = 0x0400;
    enum int O_CLOEXEC = 0x80000;
    enum int AT_FDCWD  = -100;
} 
else version(OSX)
{
    enum int O_CREAT   = 0x0200;
    enum int O_EXCL    = 0x0800;
    enum int O_TRUNC   = 0x0400;
    enum int O_APPEND  = 0x0008;
    enum int O_CLOEXEC = 0x1000000;
     enum int AT_FDCWD  = -2;
}

extern(C) @nogc nothrow
{
    int creat(const(char)* path, mode_t mode);
    int fcntl(int fd, int cmd, ...);
    int open(const(char)* path, int flags, ...);
    int openat(int dirfd, const(char)* path, int flags, ...);
}
