/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.sys.posix.pthread;

version(Posix):

alias pthread_t = ulong;
alias pthread_attr_t = void;
alias pthread_key_t = uint;
alias pthread_once_t = int;
alias pthread_mutexattr_t = void*;

alias pthread_start_routine = extern(C) void* function(void*);

struct pthread_mutex_t
{
    private align(8) ubyte[48] __opaque;
}

extern(C) nothrow @nogc
{
    int pthread_create(
        pthread_t* thread,
        const(pthread_attr_t)* attr,
        pthread_start_routine start_routine,
        void* arg
    );
    int pthread_join(pthread_t thread, void** retval);
    int pthread_cancel(pthread_t thread);
    int pthread_detach(pthread_t thread);
    int pthread_equal(pthread_t t1, pthread_t t2);
    void pthread_exit(void* retval);

    int pthread_mutex_init(pthread_mutex_t* mutex, const(pthread_mutexattr_t)* attr);
    int pthread_mutex_lock(pthread_mutex_t* mutex);
    int pthread_mutex_trylock(pthread_mutex_t* mutex);
    int pthread_mutex_unlock(pthread_mutex_t* mutex);
    int pthread_mutex_destroy(pthread_mutex_t* mutex);
}
