/*
Copyright (c) 2018-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * JSON parser.
 *
 * Copyright: Timur Gafarov 2018-2026.
 * License: $(LINK2 boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module rtld.data.json;

import rtld.core.io;
import rtld.core.file;
import rtld.core.memory;
import rtld.core.ownership;
import rtld.core.compound;
import rtld.core.conv;
import rtld.container.array;
import rtld.container.hashmap;
import rtld.hash.xxhash64;
import rtld.text.utils;
import rtld.text.utf8;
import rtld.text.str;
import rtld.text.format;

class JSONLexer
{
    ///
    string text;

    ///
    size_t position;

    ///
    string currentLexeme;

    ///
    this(string text)
    {
        this.text = text;
        nextLexeme();
    }

    ///
    void nextLexeme()
    {
        size_t length = text.length;

        // Skip whitespace
        while (position < length)
        {
            char c = text[position];

            if (c == ' ' || c == '\t' || c == '\n' || c == '\r')
                position++;
            else
                break;
        }

        // EOF
        if (position >= length)
        {
            currentLexeme = "";
            return;
        }

        size_t start = position;
        char c = text[position];

        // Single-character tokens
        if (c == '{' ||
            c == '}' ||
            c == '[' ||
            c == ']' ||
            c == ',' ||
            c == ':')
        {
            position++;
            currentLexeme = text[start..position];
            return;
        }

        // Quoted string
        if (c == '"' || c == '\'' || c == '`')
        {
            char quote = c;
            position++;

            while (position < length)
            {
                c = text[position];

                if (c == '\\')
                {
                    // Skip escaped character.
                    // This also handles escaped quotes.
                    position++;

                    if (position < length)
                        position++;

                    continue;
                }

                if (c == quote)
                {
                    position++;
                    currentLexeme = text[start..position];
                    return;
                }

                position++;
            }

            // EOF without closing quote
            currentLexeme = text[start..$];
            return;
        }

        // Everything else: read until whitespace or JSON delimiter.
        while (position < length)
        {
            c = text[position];

            if (c == ' '  ||
                c == '\t' ||
                c == '\n' ||
                c == '\r' ||
                c == '{'  ||
                c == '}'  ||
                c == '['  ||
                c == ']'  ||
                c == ','  ||
                c == ':')
            {
                break;
            }

            position++;
        }

        currentLexeme = text[start..position];
    }
}

/// JSON types enum
enum JSONType
{
    Null,
    Number,
    String,
    Array,
    Object,
    Boolean
}

struct JSONObjectProperty
{
    ulong hash;
    string key;
    JSONValue value;
}

alias JSONArray = JSONValue[];

struct JSONObject
{
    JSONObjectProperty[] data;
    
    /// Returns a pointer to the entry's value, or null if it doesn't exist.
    JSONValue* get(string key) nothrow @nogc
    {
        ulong hash = xxHash64(key, XXHASH64_SEED);
        foreach(ref prop; data)
        {
            if (prop.hash == hash)
                return &prop.value;
        }
        return null;
    }
    
    /// Bracket syntax.
    JSONValue opIndex(string key) nothrow @nogc
    {
        JSONValue* value = get(key);
        if (value is null)
            return JSONValue.init;
        else
            return *value;
    }
    
    /// "in" operator.
    JSONValue* opBinaryRight(string op)(string key) nothrow @nogc if (op == "in")
    {
        return get(key);
    }
}

struct JSONValue
{
    union
    {
        double asNumber;
        bool asBoolean;
        string asString;
        JSONArray asArray;
        JSONObject asObject;
        void* asPointer;
    }
    
    ///
    JSONType type;
    
    ///
    void print(OutputStream stream) @nogc nothrow
    {
        switch(type)
        {
            case JSONType.Null:
                .printStr(stream, "null");
                break;
            case JSONType.Number:
                .print(stream, asNumber);
                break;
            case JSONType.Boolean:
                if (asBoolean)
                    .print(stream, "true");
                else
                    .print(stream, "false");
                break;
            case JSONType.String:
                .print(stream, "\"", asString, "\"");
                break;
            case JSONType.Array:
                .printStr(stream, "[");
                foreach(size_t i, ref element; asArray)
                {
                    if (i > 0)
                        printStr(stream, ", ");
                    element.print(stream);
                }
                .printStr(stream, "]");
                break;
            case JSONType.Object:
                .printStr(stream, "{");
                foreach(size_t i, ref prop; asObject.data)
                {
                    if (i > 0)
                        .printStr(stream, ", ");
                    .printStr(stream, "\"");
                    .printStr(stream, prop.key);
                    .printStr(stream, "\":");
                    prop.value.print(stream);
                }
                .printStr(stream, "}");
                break;
            default:
                .printStr(stream, "?");
                break;
        }
    }
}

/// JSON parsing result
alias JSONResult = Compound!(bool, String);

/// JSON parsing errors enum
enum JSONError
{
    EOI = JSONResult(false, String("unexpected end of input"))
}

enum JSON_OK = JSONResult(true, String(""));

struct JSONArena
{
    struct Block
    {
        ubyte[] data;
        size_t offset;
    }

    Array!Block blocks;
    size_t bufferSize;

    this(size_t bufferSize)
    {
        this.bufferSize = bufferSize;
        addBlock(bufferSize);
    }

    void addBlock(size_t size)
    {
        blocks.append(Block(New!(ubyte[])(size), 0));
    }

    ubyte[] allocate(size_t size, size_t alignment)
    {
        auto last = &blocks.data[blocks.length - 1];
        size_t alignedOffset = alignup(last.offset, alignment);
        if (alignedOffset + size > last.data.length)
        {
            addBlock(size > bufferSize ? size : bufferSize);
            last = &blocks.data[blocks.length - 1];
            alignedOffset = 0;
        }
        ubyte[] res = last.data[alignedOffset..alignedOffset+size];
        last.offset = alignedOffset + size;
        return res;
    }

    size_t totalSize()
    {
        size_t s;
        foreach(ref b; blocks)
            s += b.data.length;
        return s;
    }

    void free()
    {
        foreach (ref b; blocks)
            Delete(b.data);
        blocks.free();
    }
}

struct ArenaArray(T)
{
    JSONArena* arena;

    T[] buffer;
    size_t length;
    size_t capacity;

    void append(T value)
    {
        if (length == capacity)
            grow();
        buffer[length++] = value;
    }

    void grow()
    {
        size_t newCapacity = capacity
            ? capacity * 2
            : 8;

        T[] newBuffer = cast(T[])arena.allocate(T.sizeof * newCapacity, T.alignof);

        if (length)
            newBuffer[0..length] = buffer[0..length];

        buffer = newBuffer;
        capacity = newCapacity;
    }

    T[] finish()
    {
        T[] result = buffer[0..length];
        length = 0;
        capacity = 0;
        buffer = [];
        return result;
    }
}

class JSONDocument: Owner
{
   public:
    bool isValid;
    JSONValue root;
    
    this(string input, Owner owner = null)
    {
        super(owner);
        lexer = New!JSONLexer(input);
        parserArena = JSONArena(16 * 1024);
        JSONResult res = parse();
        isValid = res[0];
        auto msg = res[1];
        if (!isValid && msg.length)
            printLn(msg.toString);
        msg.free();
    }
    
    ~this()
    {
        Delete(lexer);
        parserArena.free();
    }
    
    size_t allocationSize()
    {
        return parserArena.totalSize();
    }
    
   protected:

    JSONLexer lexer;
    JSONArena parserArena;
    
    string currentLexeme() @property
    {
        return lexer.currentLexeme;
    }
    
    void nextLexeme()
    {
        lexer.nextLexeme();
    }
    
    JSONResult parse()
    {
        JSONResult res = parseValue(&root);
        return res;
    }
    
    JSONResult parseValue(JSONValue* value)
    {
        if (!currentLexeme.length)
            return JSONError.EOI;
        if (currentLexeme == "{")
            return parseObject(value);
        else if (currentLexeme == "[")
            return parseArray(value);
        else
            return parseTerminal(value, currentLexeme);
    }
    
    JSONResult parseObject(JSONValue* value)
    {
        value.type = JSONType.Object;
        nextLexeme();
        auto tmpArray = ArenaArray!(JSONObjectProperty)(&parserArena);
        while (currentLexeme.length && currentLexeme != "}")
        {
            string propKey = currentLexeme;
            if (!propKey.length)
                return JSONError.EOI;
            if (propKey[0] != '\"' || propKey[$-1] != '\"')
                return JSONResult(false, format("illegal key \"{0}\"", propKey));
            propKey = propKey[1..$-1];

            nextLexeme();
            if (currentLexeme != ":")
                return JSONResult(false, format("\":\" expected, got \"{0}\"", currentLexeme));

            nextLexeme();
            
            JSONValue propValue;
            JSONResult res = parseValue(&propValue);
            if (!res[0])
                return res;

            ulong propKeyHash = xxHash64(propKey, XXHASH64_SEED);
            tmpArray.append(JSONObjectProperty(propKeyHash, propKey, propValue));

            nextLexeme();

            if (currentLexeme == ",")
                nextLexeme();
            else if (currentLexeme != "}")
                return JSONResult(false, format("\"}\" expected, got \"{0}\"", currentLexeme));
        }
        value.asObject = JSONObject(tmpArray.finish());
        return JSON_OK;
    }
    
    JSONResult parseArray(JSONValue* value)
    {
        value.type = JSONType.Array;
        nextLexeme();
        auto tmpArray = ArenaArray!(JSONValue)(&parserArena);
        while (currentLexeme.length && currentLexeme != "]")
        {
            JSONValue elemValue;
            JSONResult res = parseValue(&elemValue);
            if (!res[0])
                return res;

            tmpArray.append(elemValue);
            nextLexeme();

            if (currentLexeme == ",")
                nextLexeme();
            else if (currentLexeme != "]")
                return JSONResult(false, format("\"}\" expected, got \"{0}\"", currentLexeme));
        }
        value.asArray = tmpArray.finish();
        return JSON_OK;
    }
    
    JSONResult parseTerminal(JSONValue* value, string data)
    {
        if (data[0] == '\"')
        {
            if (data[$-1] != '\"')
                return JSONResult(false, format("illegal string \"{0}\"", data));
            data = data[1..$-1];
            value.type = JSONType.String;
            value.asString = data;
        }
        else if (data == "true")
        {
            value.type = JSONType.Boolean;
            value.asBoolean = true;
        }
        else if (data == "false")
        {
            value.type = JSONType.Boolean;
            value.asBoolean = false;
        }
        else if (data == "null")
        {
            value.type = JSONType.Null;
            value.asPointer = null;
        }
        else
        {
            value.type = JSONType.Number;
            if (!parseDouble(data, value.asNumber))
            {
                value.asNumber = double.nan;
                return JSONResult(false, format("illegal value \"{0}\"", data));
            }
        }
        
        return JSON_OK;
    }
}

//
unittest
{
    string input = "
    {
        \"foo\": \"bar\",
        \"test\": 100,
        \"bool\": true,
        \"arr\": [0, 1, 2],
        \"emptyObj\": {},
        \"emptyArr\": [],
    }
    ";
    
    JSONDocument doc = New!JSONDocument(input);
    assert(doc.root.asObject["foo"].asString == "bar");
    assert(doc.root.asObject["test"].asNumber == 100);
    assert(doc.root.asObject["bool"].asBoolean == true);
    assert(doc.root.asObject["arr"].asArray[1].asNumber == 1);
    assert(doc.root.asObject["emptyObj"].type == JSONType.Object);
    assert(doc.root.asObject["emptyArr"].type == JSONType.Array);
    Delete(doc);
}
