/*
Copyright (c) 2018-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * JSON parser.
 *
 * Copyright: Timur Gafarov 2018-2026.
 * License: $(LINK2 boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module rtld.data.json;

import rtld.core.io;
import rtld.core.file;
import rtld.core.memory;
import rtld.core.ownership;
import rtld.core.compound;
import rtld.core.conv;
import rtld.container.array;
import rtld.container.hashmap;
import rtld.hash.xxhash64;
import rtld.text.utils;
import rtld.text.utf8;
import rtld.text.lexer;
import rtld.text.str;
import rtld.text.format;

///
class JSONLexer
{
    ///
    string text;
    
    ///
    Lexer lexer;
    
    ///
    string currentLexeme;
    
    ///
    string[11] delimiters = [
        "{", "}", "[", "]", ",", ":", "\n", " ", "\"", "\'", "`"
    ];
    
    ///
    this(string text)
    {
        this.text = text;
        lexer.ignoreNewlines = true;
        lexer.start(this.text, delimiters);
        nextLexeme();
    }
    
    ///
    void nextLexeme()
    {
        // Skip whitespaces
        string lex;
        do
        {
            lex = lexer.getLexeme();
            if (lex.length == 0) break;
        }
        while(lex == " " || lex == "\t" || lex == "\n");
        
        // EOF
        if (lex.length == 0)
        {
            currentLexeme = "";
            return;
        }
        
        if (lex == "\"" || lex == "\'" || lex == "`")
        {
            string quote = lex;
            size_t startPos = lexer.position() - 1;
            
            while(true)
            {
                auto nextLex = lexer.getLexeme();
                if (nextLex.length == 0)
                {
                    // EOF without closing quote
                    currentLexeme = text[startPos..$];
                    return;
                }
                else if (nextLex.length == 1 && nextLex == quote)
                {
                    // Closing quote found
                    size_t endPos = lexer.position();
                    currentLexeme = text[startPos..endPos];
                    return;
                }
            }
        }
        else
        {
            currentLexeme = lex;
        }
    }
}

/// JSON types enum
enum JSONType
{
    Null,
    Number,
    String,
    Array,
    Object,
    Boolean
}

/// Generic JSON value
class JSONValue: Owner
{
    union
    {
        double asNumber;
        bool asBoolean;
        string asString;
        JSONArray asArray;
        JSONObject asObject;
        void* asPointer;
        protected ubyte[JSONArray.sizeof] asRawBytes;
    }
    
    ///
    JSONType type;
    
    ///
    this(Owner owner = null)
    {
        super(owner);
        type = JSONType.Null;
        asRawBytes[] = 0;
    }
    
    ///
    ~this()
    {
        if (type == JSONType.Array)
            asArray.free();
        else if (type == JSONType.Object)
            asObject.free();
    }
    
    ///
    void makeArray()
    {
        type = JSONType.Array;
    }
    
    ///
    void makeObject()
    {
        type = JSONType.Object;
    }
    
    ///
    void addArrayElement(JSONValue element)
    {
        type = JSONType.Array;
        asArray.append(element);
    }
    
    ///
    void addObjectProperty(string key, JSONValue element)
    {
        type = JSONType.Object;
        asObject[key] = element;
    }
    
    /// For dlib 1.x compatibility.
    alias addField = addObjectProperty;
    
    ///
    void print(OutputStream stream) @nogc nothrow
    {
        switch(type)
        {
            case JSONType.Null:
                .printStr(stream, "null");
                break;
            case JSONType.Number:
                .print(stream, asNumber);
                break;
            case JSONType.Boolean:
                if (asBoolean)
                    .print(stream, "true");
                else
                    .print(stream, "false");
                break;
            case JSONType.String:
                .print(stream, "\"", asString, "\"");
                break;
            case JSONType.Array:
                .printStr(stream, "[");
                foreach(size_t i, ref element; asArray.data)
                {
                    if (i > 0)
                        printStr(stream, ", ");
                    element.print(stream);
                }
                .printStr(stream, "]");
                break;
            case JSONType.Object:
                .printStr(stream, "{");
                foreach(size_t i, ref entry; asObject.entries.data)
                {
                    if (i > 0)
                        .printStr(stream, ", ");
                    .printStr(stream, "\"");
                    .printStr(stream, entry.key);
                    .printStr(stream, "\":");
                    entry.value.print(stream);
                }
                .printStr(stream, "}");
                break;
            default:
                .printStr(stream, "?");
                break;
        }
    }
}

/// JSON array
alias JSONArray = Array!JSONValue;

/// JSON Object
alias JSONObject = LinearHashMap!JSONValue;

/// JSON parsing result
alias JSONResult = Compound!(bool, String);

/// JSON parsing errors enum
enum JSONError
{
    EOI = JSONResult(false, String("unexpected end of input"))
}

/// JSON document
class JSONDocument: Owner
{
   public:
    bool isValid;
    JSONValue root;
    
    this(string input, Owner owner = null)
    {
        super(owner);
        root = New!JSONValue(this);
        lexer = New!JSONLexer(input);
        JSONResult res = parseValue(root);
        isValid = res[0];
        auto msg = res[1];
        if (!isValid && msg.length)
            printStr(msg.toString);
        msg.free();
    }
    
    ~this()
    {
        Delete(root);
        Delete(lexer);
    }
    
   protected:

    JSONLexer lexer;
    
    string currentLexeme() @property
    {
        return lexer.currentLexeme;
    }
    
    void nextLexeme()
    {
        lexer.nextLexeme();
    }
    
    JSONResult parseValue(JSONValue value)
    {
        if (!currentLexeme.length)
            return JSONError.EOI;

        if (currentLexeme == "{")
        {
            value.makeObject();
            nextLexeme();
            while (currentLexeme.length && currentLexeme != "}")
            {
                string identifier = currentLexeme;
                if (!identifier.length)
                    return JSONError.EOI;
                if (identifier[0] != '\"' || identifier[$-1] != '\"')
                    return JSONResult(false, format("illegal identifier \"{0}\"", identifier));
                identifier = identifier[1..$-1];

                nextLexeme();
                if (currentLexeme != ":")
                    return JSONResult(false, format("\":\" expected, got \"{0}\"", currentLexeme));

                nextLexeme();
                JSONValue newValue = New!JSONValue(this);
                JSONResult res = parseValue(newValue);
                if (!res[0])
                    return res;

                value.addObjectProperty(identifier, newValue);

                nextLexeme();

                if (currentLexeme == ",")
                    nextLexeme();
                else if (currentLexeme != "}")
                    return JSONResult(false, format("\"}\" expected, got \"{0}\"", currentLexeme));
            }
        }
        else if (currentLexeme == "[")
        {
            value.makeArray();
            nextLexeme();
            while (currentLexeme.length && currentLexeme != "]")
            {
                JSONValue newValue = New!JSONValue(this);
                JSONResult res = parseValue(newValue);
                if (!res[0])
                    return res;

                value.addArrayElement(newValue);

                nextLexeme();

                if (currentLexeme == ",")
                    nextLexeme();
                else if (currentLexeme != "]")
                    return JSONResult(false, format("\"}\" expected, got \"{0}\"", currentLexeme));
            }
        }
        else
        {
            string data = currentLexeme;
            if (data[0] == '\"')
            {
                if (data[$-1] != '\"')
                    return JSONResult(false, format("illegal string \"{0}\"", data));
                data = data[1..$-1];
                value.type = JSONType.String;
                value.asString = data;
            }
            else if (data == "true")
            {
                value.type = JSONType.Boolean;
                value.asBoolean = true;
            }
            else if (data == "false")
            {
                value.type = JSONType.Boolean;
                value.asBoolean = false;
            }
            else if (data == "null")
            {
                value.type = JSONType.Null;
                value.asPointer = null;
            }
            else
            {
                value.type = JSONType.Number;
                if (!parseDouble(data, value.asNumber))
                {
                    value.asNumber = double.nan;
                    return JSONResult(false, format("illegal value \"{0}\"", data));
                }
            }
        }

        return JSONResult(true, String(""));
    }
}

//
unittest
{
    string input = "
    {
        \"foo\": \"bar\",
        \"test\": 100,
        \"bool\": true,
        \"arr\": [0, 1, 2],
        \"emptyObj\": {},
        \"emptyArr\": [],
    }
    ";
    
    JSONDocument doc = New!JSONDocument(input);
    assert(doc.root.asObject["foo"].asString == "bar");
    assert(doc.root.asObject["test"].asNumber == 100);
    assert(doc.root.asObject["bool"].asBoolean == true);
    assert(doc.root.asObject["arr"].asArray[1].asNumber == 1);
    assert(doc.root.asObject["emptyObj"].type == JSONType.Object);
    assert(doc.root.asObject["emptyArr"].type == JSONType.Array);
    Delete(doc);
}
