/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Provides logging facilities.
 *
 * Description:
 * The `rtld.logger.logger` module provides logging functions.
 *
 * Copyright: Timur Gafarov 2025-2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module rtld.logger.logger;

import rtld.core.io;
import rtld.core.file;
import rtld.text.str;

/**
 * Log levels for controlling message verbosity and severity.
 */
enum LogLevel: uint
{
    /// Log all messages.
    All = 0,

    /// Debug messages.
    Debug = 1,

    /// Informational messages.
    Info = 2,

    /// Warnings.
    Warning = 3,

    /// Errors.
    Error = 4,

    /// Fatal errors.
    FatalError = 5
}

/**
 * Options for log output configuration.
 *
 * Members:
 *   enabled         = If true, logging is enabled.
 *   printToStdout   = If true, log to standard output.
 *   printToFile     = If true, log to a file.
 *   printToBuffer   = If true, log to buffer.
 *   printTimestamp  = If true, prepend timestamps to log messages.
 *   printLogLevel   = If true, prepend log level tags to messages.
 *   filename        = Log file name (if file output is enabled).
 *   dateTimePrinter = Function to generate timestamp strings.
 */
struct LogOutputOptions
{
    bool enabled;
    bool printToStdout;
    bool printToFile;
    bool printToBuffer;
    bool printTimestamp;
    bool printLogLevel;
    String filename;
    String function() dateTimePrinter;
}

private
{
    __gshared LogLevel logLevel = LogLevel.All;
    
    __gshared File _logFile;
    __gshared bool _logFileInitialized = false;
    __gshared String _logBuffer;
    
    __gshared LogOutputOptions _logOutputOptions = {
        enabled: true,
        printToStdout: true,
        printToFile: false,
        printToBuffer: false,
        printTimestamp: false,
        printLogLevel: true,
        dateTimePrinter: &defaultDateTimePrinter
    };
}

void finalize()
{
    if (_logFile.isValid)
    {
        _logFile.flush();
        _logFile.close();
        _logFileInitialized = false;
    }
    
    _logBuffer.free();
    _logOutputOptions.filename.free();
}

/**
 * Sets the filename for file logging and enables file output.
 *
 * Params:
 *   filename = The log file name.
 */
void setLogFilename(string filename)
{
    _logOutputOptions.printToFile = true;
    _logOutputOptions.filename = String(filename);
}

/**
 * Returns internal log buffer that is used for printing
 * if `logOutputOptions.printToBuffer` is enabled.
 *
 * The buffer can be reallocated as it grows, so ideally
 * this should be called each frame to update in a timely manner.
 *
 * Returns:
 *   A string containing the log history.
 */
string logBuffer()
{
    return _logBuffer.toString;
}

/**
 * Returns the default timestamp string for log messages.
 *
 * Returns:
 *   A formatted date and time string.
 */
String defaultDateTimePrinter()
{
    /*
    auto now = Clock.currTime;
    return format("[%02d.%02d.%04d %02d:%02d:%02d]",
        now.day, now.month, now.year,
        now.hour, now.minute, now.second);
    */
    // TODO
    return String("");
}

/**
 * Logs a message at the specified log level.
 *
 * Params:
 *   level = The log level.
 *   args  = The message arguments (variadic).
 */
void log(A...)(LogLevel level, A args)
{
    if (!_logOutputOptions.enabled || level < logLevel)
        return;
    
    String timestamp;
    if (_logOutputOptions.dateTimePrinter)
        timestamp = _logOutputOptions.dateTimePrinter();
    
    string levelStr = "";
    switch(level)
    {
        case LogLevel.Debug:
            levelStr = "[Debug] ";
            break;
        case LogLevel.Info:
            levelStr = "[Info] ";
            break;
        case LogLevel.Warning:
            levelStr = "[Warning] ";
            break;
        case LogLevel.Error:
            levelStr = "[Error] ";
            break;
        case LogLevel.FatalError:
            levelStr = "[Fatal error] ";
            break;
        default: break;
    }
    
    if (_logOutputOptions.printToStdout)
    {
        if (_logOutputOptions.printTimestamp)
        {
            if (_logOutputOptions.printLogLevel)
                printLn(timestamp, levelStr, args);
            else
                printLn(timestamp, " ", args);
        }
        else
        {
            if (_logOutputOptions.printLogLevel)
                printLn(levelStr, args);
            else
                printLn(args);
        }
    }
    
    /*
    // TODO:
    if (_logOutputOptions.printToFile && _logOutputOptions.filename.length)
    {
        if (_logFileInitialized)
        {
            if (_logOutputOptions.printTimestamp)
            {
                if (_logOutputOptions.printLogLevel)
                    _logFile.writeln(timestamp, levelStr, args);
                else
                    _logFile.writeln(timestamp, " ", args);
            }
            else
            {
                if (_logOutputOptions.printLogLevel)
                    _logFile.writeln(levelStr, args);
                else
                    _logFile.writeln(args);
            }
            
            _logFile.flush();
        }
        else
        {
            _logFile = File(_logOutputOptions.filename, "w");
            if ()
            {
                _logFileInitialized = true;
            }
            else
            {
                log("[Logger Error] Failed to open log file: ", e.msg);
                _logOutputOptions.filename = "";
                _logOutputOptions.printToFile = false;
            }
        }
    }
    */
    
    /*
    // TODO:
    if (_logOutputOptions.printToBuffer)
    {
        _logBuffer ~= levelStr;
        foreach(arg; args)
        {
            _logBuffer ~= arg.to!string;
        }
        _logBuffer ~= "\n";
    }
    */
    
    timestamp.free();
}
