/*
Copyright (c) 2025-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003
Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Provides logging facilities.
 *
 * Description:
 * The `rtld.logger.logger` module provides logging functions.
 *
 * Copyright: Timur Gafarov 2025-2026
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module rtld.logger.logger;

import rtld.core.io;
import rtld.core.file;
import rtld.text.str;
import rtld.text.format;
import rtld.time.datetime;

/**
 * Log levels for controlling message verbosity and severity.
 */
enum LogLevel: uint
{
    /// Log all messages.
    All = 0,

    /// Debug messages.
    Debug = 1,

    /// Informational messages.
    Info = 2,

    /// Warnings.
    Warning = 3,

    /// Errors.
    Error = 4,

    /// Fatal errors.
    FatalError = 5
}

/**
 * Options for log output configuration.
 *
 * Members:
 *   enabled         = If true, logging is enabled.
 *   printToStdout   = If true, log to standard output.
 *   printToFile     = If true, log to a file.
 *   printToBuffer   = If true, log to buffer.
 *   printTimestamp  = If true, prepend timestamps to log messages.
 *   printLogLevel   = If true, prepend log level tags to messages.
 *   filename        = Log file name (if file output is enabled).
 *   dateTimePrinter = Function to generate timestamp strings.
 */
struct LogOutputOptions
{
    bool enabled;
    bool printToStdout;
    bool printToFile;
    bool printToBuffer;
    bool printTimestamp;
    bool printLogLevel;
    string filename;
    String function() dateTimePrinter;
}

private
{
    __gshared LogLevel logLevel = LogLevel.All;
    
    __gshared String _logFilename;
    __gshared File _logFile;
    __gshared bool _logFileInitialized = false;
    __gshared String _logBuffer;
    
    __gshared LogOutputOptions _logOutputOptions = {
        enabled: true,
        printToStdout: true,
        printToFile: false,
        printToBuffer: false,
        printTimestamp: false,
        printLogLevel: true,
        dateTimePrinter: &defaultDateTimePrinter
    };
}

///
void finalize()
{
    if (_logFile.isValid)
    {
        _logFile.flush();
        _logFile.close();
        _logFileInitialized = false;
    }
    
    _logBuffer.free();
    _logFilename.free();
}

///
void setLogOutputOptions(LogOutputOptions* options)
{
    if (_logFile.isValid)
    {
        _logFile.flush();
        _logFile.close();
        _logFileInitialized = false;
    }
    
    _logFilename.free();
    
    _logOutputOptions = *options;
    
    // Store a private copy for safety
    _logFilename = String(_logOutputOptions.filename);
    _logOutputOptions.filename = _logFilename.toString;
    
    if (_logOutputOptions.dateTimePrinter is null)
        _logOutputOptions.dateTimePrinter = &defaultDateTimePrinter;
}

/**
 * Sets the filename for file logging and enables file output.
 *
 * Params:
 *   filename = The log file name.
 */
void setLogFilename(string filename)
{
    _logFilename = String(filename);
    _logOutputOptions.filename = _logFilename.toString;
    _logOutputOptions.printToFile = true;
}

/**
 * Returns internal log buffer that is used for printing
 * if `logOutputOptions.printToBuffer` is enabled.
 *
 * The buffer can be reallocated as it grows, so ideally
 * this should be called each frame to update in a timely manner.
 *
 * Returns:
 *   A string containing the log history.
 */
string logBuffer()
{
    return _logBuffer.toString;
}

/**
 * Returns the default timestamp string for log messages.
 *
 * Returns:
 *   A formatted date and time string.
 */
String defaultDateTimePrinter()
{
    DateTime now = currentTimeUTC();
    return format("[{0}.{1}.{2} {3}:{4}:{5}]",
        now.day, now.month, now.year,
        now.hours, now.minutes, now.seconds);
}

pragma(inline, true)
private string levelToString(LogLevel level) @nogc nothrow
{
    final switch (level)
    {
        case LogLevel.All:        return "";
        case LogLevel.Debug:      return "[Debug] ";
        case LogLevel.Info:       return "[Info] ";
        case LogLevel.Warning:    return "[Warning] ";
        case LogLevel.Error:      return "[Error] ";
        case LogLevel.FatalError: return "[Fatal error] ";
    }
}

pragma(inline, true)
private void logLine(alias printerFunc, Args...)(OutputStream stream, string levelStr, string timestampStr, Args args)
{
    if (_logOutputOptions.printTimestamp)
        print(stream, timestampStr, " ");
    if (levelStr.length)
        printStr(stream, levelStr);
    printerFunc(stream, args);
}

private void logImpl(alias printerFunc, Args...)(LogLevel level, Args args)
{
    if (!_logOutputOptions.enabled || level < logLevel)
        return;
    
    String timestamp;
    if (_logOutputOptions.printTimestamp && _logOutputOptions.dateTimePrinter)
        timestamp = _logOutputOptions.dateTimePrinter();
    
    string levelStr = _logOutputOptions.printLogLevel ? levelToString(level) : "";
    
    if (_logOutputOptions.printToStdout)
        logLine!printerFunc(stdout, levelStr, timestamp.toString, args);
    
    if (_logOutputOptions.printToFile && _logFilename.length)
    {
        if (!_logFileInitialized)
        {
            auto openResult = File.open(_logFilename.toString, FileAccessMode.Write);
            if (openResult.success)
            {
                _logFile = openResult.value;
                _logFileInitialized = true;
            }
            else
            {
                _logOutputOptions.filename = "";
                _logOutputOptions.printToFile = false;
                _logFilename.free();
                
                // TODO: informative file error messages
                logError("Failed to open log file (error code: ", openResult.error, ")");
            }
        }
        
        if (_logFileInitialized)
        {
            logLine!printerFunc(_logFile, levelStr, timestamp.toString, args);
            _logFile.flush();
        }
    }
    
    /*
    // TODO:
    if (_logOutputOptions.printToBuffer)
    {
        _logBuffer ~= levelStr;
        foreach(arg; args)
        {
            _logBuffer ~= arg.to!string;
        }
        _logBuffer ~= "\n";
    }
    */
    
    timestamp.free();
}

/**
 * Logs a message at the specified log level.
 *
 * Params:
 *   level = The log level.
 *   args  = The message arguments (variadic).
 */
pragma(inline, true)
void log(A...)(LogLevel level, A args)
{
    logImpl!(printLn)(level, args);
}

/**
 * Logs a formatted message at the specified log level.
 *
 * Params:
 *   level = The log level.
 *   fmt   = Formatting string.
 *   args  = Formatting parameters (variadic).
 */
pragma(inline, true)
void logFmt(A...)(LogLevel level, const(char)[] fmt, A args)
{
    logImpl!(printFmtLn)(level, fmt, args);
}

/**
 * Logs a debug message.
 *
 * Params:
 *   args = The message arguments (variadic).
 */
pragma(inline, true)
void logDebug(A...)(A args)
{
    log(LogLevel.Debug, args);
}

/**
 * Logs a formatted debug message.
 *
 * Params:
 *   fmt   = Formatting string.
 *   args  = Formatting parameters (variadic).
 */
pragma(inline, true)
void logDebugFmt(A...)(const(char)[] fmt, A args)
{
    logFmt(LogLevel.Debug, fmt, args);
}

/**
 * Logs an informational message.
 *
 * Params:
 *   args = The message arguments (variadic).
 */
pragma(inline, true)
void logInfo(A...)(A args)
{
    log(LogLevel.Info, args);
}

/**
 * Logs a formatted informational message.
 *
 * Params:
 *   fmt   = Formatting string.
 *   args  = Formatting parameters (variadic).
 */
pragma(inline, true)
void logInfoFmt(A...)(const(char)[] fmt, A args)
{
    logFmt(LogLevel.Info, fmt, args);
}

/**
 * Logs a warning message.
 *
 * Params:
 *   args = The message arguments (variadic).
 */
pragma(inline, true)
void logWarning(A...)(A args)
{
    log(LogLevel.Warning, args);
}

/**
 * Logs a formatted warning message.
 *
 * Params:
 *   fmt   = Formatting string.
 *   args  = Formatting parameters (variadic).
 */
pragma(inline, true)
void logWarningFmt(A...)(const(char)[] fmt, A args)
{
    logFmt(LogLevel.Warning, fmt, args);
}

/**
 * Logs an error message.
 *
 * Params:
 *   args = The message arguments (variadic).
 */
pragma(inline, true)
void logError(A...)(A args)
{
    log(LogLevel.Error, args);
}

/**
 * Logs a formatted error message.
 *
 * Params:
 *   fmt   = Formatting string.
 *   args  = Formatting parameters (variadic).
 */
pragma(inline, true)
void logErrorFmt(A...)(const(char)[] fmt, A args)
{
    logFmt(LogLevel.Error, fmt, args);
}

/**
 * Logs a fatal error message.
 *
 * Params:
 *   args = The message arguments (variadic).
 */
pragma(inline, true)
void logFatalError(A...)(A args)
{
    log(LogLevel.FatalError, args);
}

/**
 * Logs a formatted fatal error message.
 *
 * Params:
 *   fmt   = Formatting string.
 *   args  = Formatting parameters (variadic).
 */
pragma(inline, true)
void logFatalErrorFmt(A...)(const(char)[] fmt, A args)
{
    logFmt(LogLevel.FatalError, fmt, args);
}
