/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.libc.math;

version(WebAssembly)
{
}
else version(FreeStanding)
{
}
else
{
    extern(C) pure nothrow @nogc
    {
        double sqrt(double x);
        double sin(double x);
        double cos(double x);
        double tan(double x);
        double ceil(double x);
        double floor(double x);
        double round(double x);
        double trunc(double x);
        double rint(double x);
        double nearbyint(double arg);
        double pow(double x, double y);
        double exp(double x);
        double exp2(double x);
        double log(double x);
        double log2(double x);
        double log10(double x);
        double fmax(double x, double y);
        double fmin(double x, double y);
        double fma(double x, double y, double z);
        double copysign(double x, double y);
        double cbrt(double x);
        double asin(double x);
        double acos(double x);
        double atan(double x);
        double atan2(double y, double x);
        double hypot(double x, double y);
        double modf(double x, double* intptr);
        double sinh(double x);
        double cosh(double x);
        double tanh(double x);
        double asinh(double x);
        double acosh(double x);
        double atanh(double x);
    }
}
