/*
Copyright (c) 2019-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.libc.stdio;

import rtld.libc.stdint;

enum int EOF = -1;

enum int SEEK_SET = 0;
enum int SEEK_CUR = 1;
enum int SEEK_END = 2;

enum int _IOFBF = 0;
enum int _IOLBF = 1;
enum int _IONBF = 2;

enum size_t BUFSIZ = 8192;

struct FILE;
struct fpos_t;

version(WebAssembly)
{
}
else version(FreeStanding)
{
}
else
{
    version(Linux)
    {
        extern(C) __gshared FILE* stdin;
        extern(C) __gshared FILE* stdout;
        extern(C) __gshared FILE* stderr;
    }
    else version(OSX)
    {
        private extern(C) __gshared FILE* __stdinp;
        private extern(C) __gshared FILE* __stdoutp;
        private extern(C) __gshared FILE* __stderrp;

        @property FILE* stdin()  nothrow @nogc { return __stdinp; }
        @property FILE* stdout() nothrow @nogc { return __stdoutp; }
        @property FILE* stderr() nothrow @nogc { return __stderrp; }
    }
    else version(Windows)
    {
        private extern(C) FILE** __acrt_iob_func(uint index) nothrow @nogc;

        @property FILE* stdin()  nothrow @nogc { return *__acrt_iob_func(0); }
        @property FILE* stdout() nothrow @nogc { return *__acrt_iob_func(1); }
        @property FILE* stderr() nothrow @nogc { return *__acrt_iob_func(2); }
    }
    
    extern(C) nothrow @nogc
    {
        /// Closes a file.
        int fclose(FILE* stream);
        
        /// Returns true when the position indicator has reached the end of the file.
        int feof(FILE* stream);
        
        /// Returns true if a recent file operation had an error.
        int ferror(FILE* stream);
        
        /// Returns the ASCII value of a character in a file and advances the position indicator.
        int fgetc(FILE* stream);
        
        /// Reads a line from a file and advances the position indicator.
        char* fgets(char* str, int num, FILE* stream);
        
        /// Opens a file and returns a file pointer for use in file handling functions.
        FILE* fopen(const(char)* fname, const(char)* mode);
        
        /// Writes a formatted string into a file.
        int fprintf(FILE* stream, const(char)* format, ...);
        
        /// Writes a character into a file and advances the position indicator.
        int fputc(int c, FILE* stream);
        
        /// Writes a string into a file and advances the position indicator.
        int fputs(const(char)* str, FILE* stream);
        
        /// Reads data from a file and writes it into a block of memory.
        size_t fread(void* buf, size_t size, size_t count, FILE* stream);
        
        /// Reads formatted data from a file and writes it into a number of memory locations.
        int fscanf(FILE* stream, const(char)* format, ...);
        
        /// Moves the position indicator of a file pointer.
        int fseek(FILE* stream, c_long offset, int whence);
        
        /// Returns the value of the position indicator of a file pointer.
        c_long ftell(FILE* stream);
        
        /// Writes data from a block of memory into a file.
        size_t fwrite(const(void)* buf, size_t size, size_t count, FILE* stream);
        
        /// The same as fgetc.
        alias getc = fgetc;
        
        /// Reads one character of user input and returns its ASCII value.
        int getchar();
        
        /// Writes a formatted string to the console.
        int printf(const(char)* fmt, ...);
        
        /// The same as fputc.
        alias putc = fputc;
        
        /// Outputs a single character to the console.
        int putchar(int c);
        
        /// Outputs a string to the console.
        int puts(const(char)* s);
        
        /// Deletes a file.
        int remove(const(char)* fname);
        
        /// Changes the name of a file.
        int rename(const(char)* oldfname, const(char)* newfname);
        
        /// Moves the position indicator to the beginning of the file.
        void rewind(FILE* stream);
        
        /// Reads formatted data from user input and writes it into a number of memory locations
        int scanf(const(char)* format, ...);
        
        /// Writes a formatted string into a char array (memory-safe)
        int snprintf(char* str, size_t size, const(char)* fmt, ...);
        
        ///
        //int vsnprintf(char* str, size_t n, const(char)* fmt, va_list arg);
        
        /// Writes a formatted string into a char array.
        int sprintf(char* buf, const(char)* fmt, ...);
        
        /// Reads a formatted string from a char array and writes it into a number of memory locations.
        int sscanf(const(char)* buf, const(char)* fmt, ...);
    }
}