/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.libc.stdint;

alias int8_t = byte;
alias int16_t = short;
alias int32_t = int;
alias int64_t = long;

alias uint8_t = ubyte;
alias uint16_t = ushort;
alias uint32_t = uint;
alias uint64_t = ulong;

alias int_least8_t = byte;
alias int_least16_t = short;
alias int_least32_t = int;
alias int_least64_t = long;

alias uint_least8_t = ubyte;
alias uint_least16_t = ushort;
alias uint_least32_t = uint;
alias uint_least64_t = ulong;

alias int_fast8_t = byte;
alias int_fast16_t = long;
alias int_fast32_t = long;
alias int_fast64_t = long;

alias uint_fast8_t = ubyte;
alias uint_fast16_t = ulong;
alias uint_fast32_t = ulong;
alias uint_fast64_t = ulong;

alias intmax_t = long;
alias intptr_t = long;
alias uintmax_t = ulong;
alias uintptr_t = ulong;

alias wchar_t = wchar;

version(X86)
{
    alias c_long = int;
    alias c_ulong = uint;
}
else version(Windows)
{
    alias c_long = int;
    alias c_ulong = uint;
}
else version(Posix)
{
    alias c_long = long;
    alias c_ulong = ulong;
}
else
{
    alias c_long = long;
    alias c_ulong = ulong;
}
