/*
Copyright (c) 2022-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.libc.stdlib;

version(WebAssembly)
{
    extern(C) nothrow @nogc
    {
        uint jsMalloc(uint) nothrow @nogc;
        void jsFree(uint) nothrow @nogc;
        
        pragma(inline, true)
        void* malloc(size_t size)
        {
            return cast(void*)jsMalloc(size);
        }
        
        pragma(inline, true)
        void free(void* mem)
        {
            jsFree(cast(uint)mem);
        }
        
        // Fallback
        pragma(inline, true)
        void srand(uint seed)
        {
            // TODO
        }
        
        // Fallback
        pragma(inline, true)
        int rand()
        {
            // TODO
            return 0;
        }
        
        pragma(inline, true)
        void exit(int status)
        {
            //
        }
        
        pragma(inline, true)
        void _Exit(int status)
        {
            //
        }
    }
}
else version(FreeStanding)
{
    extern(C) nothrow @nogc
    {
        // For user-side implementation:
        __gshared void* function(size_t) custom_malloc;
        __gshared void function(void* mem) custom_free;
        __gshared void function(uint seed) custom_srand;
        __gshared int function() custom_rand;
        
        pragma(inline, true)
        void* malloc(size_t size)
        {
            if (custom_malloc)
                return custom_malloc(size);
            else
                return null;
        }
        
        pragma(inline, true)
        void free(void* mem)
        {
            if (custom_free)
                custom_free(mem);
        }
        
        pragma(inline, true)
        void srand(uint seed)
        {
            if (custom_srand)
                custom_srand(seed);
        }
        
        pragma(inline, true)
        int rand()
        {
            if (custom_rand)
                return custom_rand();
            else
                return 0;
        }
        
        pragma(inline, true)
        void exit(int status)
        {
            //
        }
        
        pragma(inline, true)
        void _Exit(int status)
        {
            //
        }
    }
}
else
{
    extern(C) nothrow @nogc
    {
        void* malloc(size_t size);
        void free(void* mem);
        void srand(uint seed);
        int rand();
        void exit(int status);
        void _Exit(int status);
    }
}
