/*
Copyright (c) 2022-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.libc.stdlib;

enum NULL = null;
enum EXIT_SUCCESS = 0;
enum EXIT_FAILURE = 1;

struct div_t
{
    int quot;
    int rem;
}

struct ldiv_t
{
    long quot;
    long rem;
}

version(WebAssembly)
{
}
else version(FreeStanding)
{
}
else
{
    extern(C) nothrow @nogc
    {
        int abs(int i);
        int atexit(void function());
        double atof(const(char)* s);
        float atoff(const(char)* s);
        int atoi(const(char)* s);
        long atol(const(char)* s);
        void* bsearch(const(void)* key, const(void)* base, size_t nmemb, size_t size, int function(const(void)*, const(void)*) compar);
        void* calloc(size_t n, size_t s);
        void* calloc_r(void* reent, size_t n, size_t s);
        div_t div(int n, int d);
        char* ecvt(double val, int chars, int* decpt, int* sgn);
        char* ecvtf(float val, int chars, int* decpt, int* sgn);
        char* fcvt(double val, int decimals, int* decpt, int* sgn);
        char* fcvtf(float val, int decimals, int* decpt, int* sgn);
        char* gcvt(double val, int precision, char* buf);
        char* gcvtf(float val, int precision, char* buf);
        char* ecvtbuf(double val, int chars, int* decpt, int* sgn, char* buf);
        char* fcvtbuf(double val, int decimals, int* decpt, int* sgn, char* buf);
        void exit(int status);
        char* getenv(const(char)* name);
        long labs(long i);
        ldiv_t ldiv(long n, long d);
        void* malloc(size_t size);
        void* realloc(void* aptr, size_t nbytes);
        void free(void* mem);
        void* _malloc_r(void* reent, size_t nbytes);
        void* _realloc_r(void* reent, void* aptr, size_t nbytes);
        void _free_r(void* reent, void* aptr);
        int mbtowc(wchar* pwc, const(char)* s, size_t n);
        void qsort(void* base, size_t nmemb, size_t size, int function(const(void)*, const(void)*) compar);
        int rand();
        void srand(uint seed);
        int _rand_r(void* reent);
        void _srand_r(void* reent, uint seed);
        double strtod(const(char)* str, char** tail);
        float strtodf(const(char)* str, char** tail);
        double _strtod_r(void* reent, const(char)* str, char** tail);
        long strtol(const(char)* s, char** ptr, int base);
        long _strtol_r(void* reent, const(char)* s, char** ptr, int base);
        ulong strtoul(const(char)* s, char** ptr, int base);
        ulong _strtoul_r(void* reent, const(char)* s, char** ptr, int base);
        int system(char* s);
        int _system_r(void* reent, char* s);
        int wctomb(char* s, wchar wc);
        
        /// Sets or changes an environment variable.
        int setenv(const(char)* name, const(char)* value, int overwrite);

        /// Deletes an environment variable.
        int unsetenv(const(char)* name);

        /// Low-level function to add or change environment string (format "NAME=VALUE").
        int putenv(char* string);
    }
}
