/*
Copyright (c) 2018-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.text.encodings;

public
{
    import rtld.text.utf8;
    import rtld.text.utf16;
}

/**
* Transcodes a UTF-8 slice into a null-terminated UTF-16 LE string within a byte buffer.
*/
const(wchar)* toUTF16z(string input, ubyte[] destBuffer) @nogc nothrow
{
    if (destBuffer.length < 2)
        return null;

    UTF8Decoder decoder;
    decoder.input = input;
    decoder.index = 0;

    UTF16LEEncoder encoder;

    size_t writeIdx = 0;
    // Leave the last 2 bytes free for the mandatory UTF-16 null terminator (U+0000)
    size_t maxWriteLen = destBuffer.length - 2; 

    while (!decoder.eos())
    {
        int codePoint = decoder.decodeNext();

        if (codePoint == UTF8_END) break;
        if (codePoint == UTF8_ERROR)
            return null;

        // Check if there is space in the buffer to write a potential surrogate pair (4 bytes)
        if (writeIdx >= maxWriteLen)
            return null;

        // Pass the remaining free buffer space to the encoder
        size_t bytesWritten = encoder.encode(cast(uint)codePoint, destBuffer[writeIdx..$]);
        
        if (bytesWritten == 0)
            return null; // Encoding error
        
        writeIdx += bytesWritten;
    }

    destBuffer[writeIdx] = 0;
    destBuffer[writeIdx + 1] = 0;

    return cast(const(wchar)*)destBuffer.ptr;
}

/**
* Transcodes a UTF-16 slice into a null-terminated UTF-8 string within a byte buffer.
*/
const(char)* toUTF8z(const(wchar)[] input, ubyte[] destBuffer) @nogc nothrow
{
    if (destBuffer.length < 4)
        return null;

    UTF16LEDecoder decoder;
    decoder.input = input;
    decoder.index = 0;

    UTF8Encoder encoder;

    size_t writeIdx = 0;
    size_t maxWriteLen = destBuffer.length - 1; 

    while (!decoder.eos())
    {
        int codePoint = decoder.decodeNext();

        if (codePoint == UTF16_END) break;
        if (codePoint == UTF16_ERROR) return null;

        if (writeIdx + 4 > maxWriteLen)
        {
            ubyte[4] tempBuf;
            size_t projected = encoder.encode(cast(uint)codePoint, tempBuf);
            if (projected == 0 || writeIdx + projected > maxWriteLen)
                return null;
        }

        size_t bytesWritten = encoder.encode(cast(uint)codePoint, destBuffer[writeIdx..$]);
        if (bytesWritten == 0)
            return null;

        writeIdx += bytesWritten;
    }

    destBuffer[writeIdx] = 0;

    return cast(const(char)*)destBuffer.ptr;
}
