/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.text.format;

import rtld.core.errors;
import rtld.core.traits;
import rtld.core.tuple;
import rtld.text.str;
import rtld.text.encodings;

/**
 * Formats a string using the given format string and arguments.
 * Uses RTLD formatting syntax: {i}, where i is the argument index.
 *
 * Params:
 *   fmt - The format string.
 *   args - Arguments to format.
 *
 * Returns:
 *   The formatted String object.
 */
String format(Args...)(string fmt, Args args)
{
    String s;
    s.reserve(fmt.length + Args.length * 8);

    for (size_t i = 0; i < fmt.length; i++)
    {
        if (fmt[i] == '{' && i + 1 < fmt.length)
        {
            size_t start = i + 1;
            size_t end = start;
            
            while (end < fmt.length && fmt[end] >= '0' && fmt[end] <= '9')
            {
                end++;
            }
            
            if (end < fmt.length && fmt[end] == '}' && end > start)
            {
                size_t argIdx = 0;
                for (size_t k = start; k < end; k++)
                {
                    argIdx = argIdx * 10 + (fmt[k] - '0');
                }
                
                ArgSwitch: switch(argIdx)
                {
                    static foreach(idx; 0..Args.length)
                    {
                        case idx:
                            s.append(args[idx]);
                            break ArgSwitch;
                    }
                    default:
                        s ~= "{ERROR}";
                        break ArgSwitch;
                }
                
                i = end;
                continue;
            }
        }
        
        s ~= fmt[i];
    }
    
    s.addZero();
    return s;
}
