/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.text.format;

import rtld.core.errors;
import rtld.core.traits;
import rtld.core.tuple;
import rtld.text.str;
import rtld.text.encodings;

/**
 * Formats a string using the given format string and arguments.
 * Uses RTLD formatting syntax: {i}, where i is the argument index.
 *
 * Params:
 *   fmt - The format string.
 *   args - Arguments to format.
 *
 * Returns:
 *   The formatted String object.
 */
String format(Args...)(const(char)[] fmt, Args args)
{
    String s;
    s.reserve(fmt.length + Args.length * 8);
    
    size_t lastIdx = 0;

    for (size_t i = 0; i < fmt.length; i++) 
    {
        if (fmt[i] == '{') 
        {
            size_t j = i + 1;
            int argIdx = 0;
            bool hasIndex = false;

            while (j < fmt.length && fmt[j] >= '0' && fmt[j] <= '9')
            {
                argIdx = (argIdx * 10) + (fmt[j] - '0');
                hasIndex = true;
                j++;
            }

            const(char)[] spec = null;
            if (hasIndex && j < fmt.length && fmt[j] == ':')
            {
                size_t specStart = j + 1;
                size_t k = specStart;
                while (k < fmt.length && fmt[k] != '}')
                    k++;

                if (k < fmt.length)
                {
                    spec = fmt[specStart..k];
                    j = k;
                }
            }

            if (j < fmt.length && fmt[j] == '}' && hasIndex)
            {
                if (i > lastIdx)
                    s.append(fmt[lastIdx..i]);

                bool found = false;

                static foreach (idx, Arg; Args)
                {
                    if (!found && argIdx == idx)
                    {
                        s.appendArgSpec(args[idx], spec);
                        found = true;
                    }
                }

                if (!found)
                {
                    s.append("{?}");
                }
                
                i = j; 
                lastIdx = i + 1;
            }
        }
    }
    
    if (lastIdx < fmt.length)
        s.append(fmt[lastIdx..$]);
    
    return s;
}

///
private void appendArgSpec(T)(ref String s, T arg, const(char)[] spec)
{
    if (spec.length == 0)
    {
        s.append(arg);
        return;
    }

    static if (isInteger!T)
    {
        ulong bits = cast(ulong)arg;
        ulong mask = T.sizeof >= 8 ? ulong.max : ((1UL << (T.sizeof * 8)) - 1);
        bits &= mask;

        switch (spec[0])
        {
            case 'x': s.appendHex(bits, false); return;
            case 'X': s.appendHex(bits, true);  return;
            case 'b': s.appendBinary(bits);     return;
            //TODO:
            //case 'o': s.appendOctal(bits);      return;
            default: break;
        }
    }
    else static if (isFloatingPoint!T)
    {
        if (spec[0] == 'f' || spec[0] == 'F')
        {
            int precision = 6;
            if (spec.length > 1)
            {
                precision = 0;
                foreach (c; spec[1..$])
                {
                    if (c < '0' || c > '9') { precision = 6; break; }
                    precision = precision * 10 + (c - '0');
                }
            }
            appendFloatFixed(s, cast(double)arg, precision);
            return;
        }
    }

    s.append(arg); // unknown spec, or non-numeric type: default formatting
}

private void appendHex(ref String s, ulong value, bool uppercase)
{
    if (value == 0) { s.append("0"); return; }

    static immutable char[16] lower = "0123456789abcdef";
    static immutable char[16] upper = "0123456789ABCDEF";
    const(char[16])* digits = uppercase ? &upper : &lower;
    char[16] buf;
    size_t pos = buf.length;
    while (value > 0)
    {
        pos--;
        buf[pos] = (*digits)[value & 0xF];
        value >>= 4;
    }
    s.append(cast(string)buf[pos..$]);
}

private void appendBinary(ref String s, ulong value)
{
    if (value == 0)
    {
        s.append("0");
        return;
    }
    char[64] buf;
    size_t pos = buf.length;
    while (value > 0)
    {
        pos--;
        buf[pos] = cast(char)('0' + (value & 1));
        value >>= 1;
    }
    s.append(cast(string)buf[pos..$]);
}

private void appendFloatFixed(ref String s, double arg, int precision)
{
    if (arg != arg) { s.append("nan"); return; }
    if (arg == double.infinity)  { s.append("inf");  return; }
    if (arg == -double.infinity) { s.append("-inf"); return; }
    if (arg < 0.0) { s.append("-"); arg = -arg; }

    long integerPart = cast(long)arg;
    s.append(integerPart);

    if (precision <= 0.0)
        return;

    s.append(".");

    double fractionalPart = arg - integerPart;
    char[24] buf;
    size_t pos = 0;
    while (pos < precision)
    {
        fractionalPart *= 10;
        int digit = cast(int)fractionalPart;
        buf[pos++] = cast(char)('0' + digit);
        fractionalPart -= digit;
    }
    s.append(cast(string)buf[0..pos]); // no trailing-zero stripping here
}
