/*
Copyright (c) 2018-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * UTF-8 string type.
 *
 * Copyright: Timur Gafarov 2018-2026.
 * License: $(LINK2 https://boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module rtld.text.str;

import rtld.core.io;
import rtld.core.traits;
import rtld.core.memory;
import rtld.core.file;
import rtld.container.array;
import rtld.text.utf8;

/**
 * GC-free UTF-8 string type based on rtld.container.array.
 * Stores up to 128 bytes without dynamic memory allocation,
 * so short strings are processed very fast.
 * String is always zero-terminated and directly compatible with C.
 */
struct String
{
    /**
     * Underlying array of characters
     */
    Array!(char, 128) data;

    pragma(inline, true)
    void addZero()
    {
        if (data.length > 0)
        {
            if (data[$-1] != '\0')
                data.insertBack('\0');
        }
        else
            data.insertBack('\0');
    }

    pragma(inline, true)
    void removeZero()
    {
        if (data.length > 0)
            data.removeBack(1);
    }

    /**
     * Construct from D string
     */
    this(string s)
    {
        data.insertBack(s);
        addZero();
    }

    /**
     * Construct from zero-terminated C string (ASCII or UTF8)
     */
    this(const(char)* cStr)
    {
        size_t offset = 0;
        while(cStr[offset] != 0)
        {
            offset++;
        }
        if (offset > 0)
            data.insertBack(cStr[0..offset]);
        addZero();
    }

    /**
     * Construct from zero-terminated UTF-16 LE string
     */
    this(const(wchar)* wStr)
    {
        wchar* utf16 = cast(wchar*)wStr;
        wchar utf16char;
        do
        {
            utf16char = *wStr;
            utf16++;

            if (utf16char)
            {
                if (utf16char < 0x80)
                {
                    data.insertBack((utf16char >> 0 & 0x7F) | 0x00);
                }
                else if (utf16char < 0x0800)
                {
                    data.insertBack((utf16char >> 6 & 0x1F) | 0xC0);
                    data.insertBack((utf16char >> 0 & 0x3F) | 0x80);
                }
                else if (utf16char < 0x010000)
                {
                    data.insertBack((utf16char >> 12 & 0x0F) | 0xE0);
                    data.insertBack((utf16char >> 6 & 0x3F) | 0x80);
                    data.insertBack((utf16char >> 0 & 0x3F) | 0x80);
                }
                else if (utf16char < 0x110000)
                {
                    data.insertBack((utf16char >> 18 & 0x07) | 0xF0);
                    data.insertBack((utf16char >> 12 & 0x3F) | 0x80);
                    data.insertBack((utf16char >> 6 & 0x3F) | 0x80);
                    data.insertBack((utf16char >> 0 & 0x3F) | 0x80);
                }
            }
        }
        while(utf16char);
        addZero();
    }
    
    /**
     * Construct from a File.
     */
    this(File file)
    {
        this = String.fromFile(file);
    }
    
    /**
     * Creates a String from a File.
     */
    static String fromFile(File file)
    {
        String s;
        
        if (file.handle == InvalidHandle)
            return s;
        
        auto sizeResult = file.size();
        if (!sizeResult.success)
            return s;
        
        size_t size = sizeResult.value;
        s.data.resize(size, 0);
        auto readResult = file.read(s.data.data);
        if (!readResult.success)
        {
            s.free();
            return s;
        }
        s.addZero();
        return s;
    }
    
    /**
     * Loads a file and creates a String from it.
     */
    static String fromFile(string path)
    {
        String s;
        
        if (path.length == 0)
            return s;
        
        auto openResult = File.open(path);
        if (!openResult.success)
            return s;
        
        File file = openResult.value;
        s = fromFile(file);
        file.close();
        return s;
    }
    
    /// ditto
    pragma(inline, true)
    static String fromFile(String path)
    {
        return String.fromFile(path.toString);
    }

    ///
    pragma(inline, true)
    void free()
    {
        data.free();
    }
    
    ///
    pragma(inline, true)
    auto opOpAssign(string op)(char[] s) if (op == "~")
    {
        removeZero();
        data.insertBack(s);
        addZero();
        return this;
    }

    ///
    pragma(inline, true)
    auto opOpAssign(string op)(string s) if (op == "~")
    {
        removeZero();
        data.insertBack(s);
        addZero();
        return this;
    }

    ///
    pragma(inline, true)
    auto opOpAssign(string op)(char c) if (op == "~")
    {
        removeZero();
        data.insertBack(c);
        addZero();
        return this;
    }

    ///
    pragma(inline, true)
    auto opOpAssign(string op)(String s) if (op == "~")
    {
        String s1 = this;
        s1.removeZero();
        s1 ~= s;
        s1.addZero();
        return s1;
    }

    ///
    pragma(inline, true)
    void reserve(size_t amount)
    {
        data.reserve(amount);
    }

    ///
    pragma(inline, true)
    @property size_t length()
    {
        if (data.length == 0)
            return 0;
        else
            return data.length - 1;
    }

    ///
    pragma(inline, true)
    @property size_t capacity() const nothrow @nogc
    {
        return data.capacity;
    }

    ///
    pragma(inline, true)
    @property string toString() const @nogc nothrow
    {
        if (data.length == 0)
            return "";
        else
            return cast(string)data.readOnlyData[0..$-1];
    }

    ///
    alias toString this;
    
    ///
    void print(OutputStream stream) @nogc nothrow
    {
        .printStr(stream, toString);
    }

    ///
    pragma(inline, true)
    @property const(char)* ptr() const
    {
        return data.readOnlyData.ptr;
    }

    ///
    pragma(inline, true)
    @property char* ptrMutable()
    {
        return data.data.ptr;
    }

    ///
    pragma(inline, true)
    @property bool isDynamic()
    {
        return data.isDynamic;
    }

    /**
     * Range interface that iterates the string by Unicode code point (dchar),
     * i.e., foreach(dchar c; str.decode)
     */
    pragma(inline, true)
    auto decode()
    {
        return UTF8Decoder().decode(toString());
    }
    
    /// Appends a generic value.
    void append(T)( T val)
    {
        static if (isString!T)
            this ~= val;
        else static if (is(T == String))
            this ~= val;
        else static if (isWString!T)
        {
            auto decoder = UTF16LEDecoder(val);
            UTF8Encoder encoder;
            int codepoint;
            ubyte[4] buffer;
            do
            {
                codepoint = decoder.decodeNext();
                if (codepoint != DECODE_END && codepoint != DECODE_ERROR)
                {
                    encoder.encode(codepoint, buffer);
                    this ~= cast(char[])buffer;
                }
            }
            while(codepoint != DECODE_END && codepoint != DECODE_ERROR);
        }
        else static if (is(T ==  bool))
        {
            if (val)
                this ~= "true";
            else
                this ~= "false";
        }
        else static if (isInteger!T)
        {
            if (val == 0)
            {
                this ~= '0';
                return;
            }
            
            if (val < 0)
            {
                this ~= '-';
                val = -val;
            }
            
            char[20] buf;
            size_t pos = buf.length;
            
            while(val > 0)
            {
                pos--;
                buf[pos] = cast(char)('0' + (val % 10));
                val /= 10;
            }
            
            this ~= buf[pos..$];
        }
        else static if (isFloatingPoint!T)
        {
            if (val != val)
            {
                this ~= "nan";
                return;
            }
            if (val == T.infinity)
            {
                this ~= "inf";
                return;
            }
            if (val == -T.infinity)
            {
                this ~= "-inf";
                return;
            }

            if (val < 0)
            {
                this ~= '-';
                val = -val;
            }

            long integerPart = cast(long)val;
            append(integerPart);
            this ~= '.';

            double fractionalPart = val - integerPart;
            int precision = 6;
            
            char[20] buf;
            size_t pos = 0;

            while(precision > 0)
            {
                fractionalPart *= 10;
                int digit = cast(int)fractionalPart;
                
                buf[pos] = cast(char)('0' + digit);
                pos++;
                
                fractionalPart -= digit;
                precision--;
            }

            while(pos > 1 && buf[pos - 1] == '0')
            {
                pos--;
            }

            this ~= buf[0 .. pos];
        }
        else static if (isArray!T)
        {
            this ~= "[";
            foreach(size_t i, ref element; val)
            {
                if (i > 0)
                    this ~= ", ";
                append(element);
            }
            this ~= "]";
        }
        else static if (is(T == struct))
        {
            this ~= __traits(identifier, T);
            this ~= "(";
            static foreach(i; 0..val.tupleof.length)
            {
                static if (i > 0)
                    this ~= ", ";
                this ~= val.tupleof[i];
            }
            this ~= ")";
        }
        else static if (__traits(hasMember, T, "toString") && 
                    is(typeof(val.toString()): const(char)[]))
        {
            static if (isClass!T || isInterface!T)
            {
                if (val is null)
                {
                    this ~= "null";
                    return;
                }
            }
            this ~= val.toString();
        }
        else static if (isObject!T)
        {
            if (val is null)
            {
                this ~= "null";
                return;
            }
            
            static if (is(T == interface))
            {
                auto obj = cast(Object)val;
                auto classInfo = obj ? typeid(obj) : null;
            }
            else
            {
                auto classInfo = typeid(val);
            }

            if (classInfo !is null)
            {
                string fullName = classInfo.name;
                
                size_t lastDot = 0;
                foreach (i; 0..fullName.length)
                {
                    if (fullName[i] == '.')
                        lastDot = i + 1;
                }
                
                s ~= fullName[lastDot .. $];
            }
            else
            {
                s ~= "{?}";
            }
        }
        else static if (isPointer!T)
        {
            if (val is null)
            {
                this ~= "null";
                return;
            }

            this ~= "0x";

            size_t addr = cast(size_t)val;
            
            enum hexLength = size_t.sizeof * 2;
            char[hexLength] buf;
            
            static immutable char[16] hexDigits = "0123456789abcdef";

            for (size_t i = hexLength; i > 0; i--)
            {
                buf[i - 1] = hexDigits[addr & 0xF];
                addr >>= 4;
            }

            this ~= buf;
        }
        else
        {
            this ~= "{?}";
        }
    }
}

///
unittest
{
    String s = "hello";
    s ~= ", world";
    s ~= '!';
    assert(!s.isDynamic);
    string dStr = s;
    assert(dStr == "hello, world!");
    s.free();
    assert(s.length == 0);
    
    const(char)* cStr = "Hello!";
    String s2 = String(cStr);
    assert(s2.toString == "Hello!");
}
