/*
Copyright (c) 2016-2025 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * UTF-16 decoder and encoder
 *
 * Copyright: Timur Gafarov 2016-2025.
 * License: $(LINK2 boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov, Roman Chistokhodov
 */
module rtld.text.utf16;

import rtld.text.utf8;
import rtld.text.common;

enum ushort UTF16_HI_SURROGATE = 0xD800;
enum ushort UTF16_LO_SURROGATE = 0xDC00;
enum ushort UTF16_BOM_LE = 0xfeff;
enum ushort UTF16_BOM_BE = 0xfffe;

/// Constant to return from the decoder on the end of string.
enum UTF16_END = DECODE_END;

/// Constant to return from the decoder when error occurs.
enum UTF16_ERROR = DECODE_ERROR;

/**
 * UTF-16 LE decoder to use with dlib.text.encodings.transcode
 */
struct UTF16LEDecoder
{
    public:

    /// Input string. Set it before decoding
    const(wchar)[] input;

    /// Current index in an input string
    size_t index = 0;

    /// Current character index
    int character = 0;

    /**
     * Decode next character.
     * Returns: decoded code point, or UTF8_ERROR if error occured, or UTF8_END if input has no more characters.
     */
    int decodeNext() @nogc nothrow
    {
        if (index >= input.length)
            return index == input.length ? UTF16_END : UTF16_ERROR;

        character++;

        uint codePoint = input[index++];

        if (codePoint >= 0xD800 && codePoint <= 0xDBFF)
        {
            if (index >= input.length)
                return UTF16_ERROR;

            uint lowSurrogate = input[index++];
            
            if (lowSurrogate < 0xDC00 || lowSurrogate > 0xDFFF)
                return UTF16_ERROR;

            return ((codePoint - 0xD800) << 10) + (lowSurrogate - 0xDC00) + 0x10000;
        }
        
        if (codePoint >= 0xDC00 && codePoint <= 0xDFFF)
            return UTF16_ERROR;

        return cast(int)codePoint;
    }

    /**
     * Check if decoder is in the end of input.
     */
    bool eos() @nogc nothrow
    {
        return (index >= input.length);
    }

    /**
     * Range interface.
     */
    auto decode(const(wchar)[] s) @nogc nothrow
    {
        input = s;

        static struct ByDchar
        {
            private:
            UTF16LEDecoder _decoder;
            dchar _lastRead;

            public:
            this(UTF16LEDecoder decoder) @nogc nothrow
            {
                _decoder = decoder;
                _lastRead = cast(dchar)_decoder.decodeNext();
            }

            bool empty() @nogc nothrow
            {
                return _lastRead == UTF16_END || _lastRead == UTF16_ERROR;
            }

            dchar front() @nogc nothrow
            {
                return _lastRead;
            }

            void popFront() @nogc nothrow
            {
                _lastRead = cast(dchar)_decoder.decodeNext();
            }

            auto save() @nogc nothrow
            {
                return this;
            }
        }

        return ByDchar(this);
    }

    /// ditto
    auto decode() @nogc nothrow
    {
        return decode(input);
    }
}

///
unittest
{
    wstring input = "Жå∑";
    auto decoder = UTF16LEDecoder(cast(string)input);
    assert(decoder.decodeNext() == 'Ж');
    assert(decoder.decodeNext() == 'å');
    assert(decoder.decodeNext() == '∑');
}

/**
 * UTF-16 LE encoder to use with dlib.text.encodings.transcode
 */
struct UTF16LEEncoder
{
    /**
     * Encodes a Unicode code point to UTF-16 LE into user-provided buffer.
     * Buffer must be at least 4 bytes length.
     * Returns number of bytes written, or 0 at error.
     */
    size_t encode(uint ch, ubyte[] buffer) @nogc nothrow
    {
        if (buffer.length < 4)
            return 0;

        if (ch <= 0xFFFF)
        {
            if (ch >= UTF16_HI_SURROGATE && ch <= 0xDFFF)
                return 0;
            buffer[0] = cast(ubyte)(ch & 0xFF);
            buffer[1] = cast(ubyte)((ch >> 8) & 0xFF);
            return 2;
        }
        else if (ch <= 0x10FFFF)
        {
            uint v = ch - 0x10000;
            ushort highSurrogate = cast(ushort)((v >> 10) + UTF16_HI_SURROGATE);
            ushort lowSurrogate  = cast(ushort)((v & 0x3FF) + UTF16_LO_SURROGATE);

            // High surrogate bytes
            buffer[0] = cast(ubyte)(highSurrogate & 0xFF);
            buffer[1] = cast(ubyte)((highSurrogate >> 8) & 0xFF);

            // Low surrogate bytes
            buffer[2] = cast(ubyte)(lowSurrogate & 0xFF);
            buffer[3] = cast(ubyte)((lowSurrogate >> 8) & 0xFF);
            
            return 4;
        }
        else
        {
            return 0;
        }
    }
}

///
unittest
{
    UTF16LEEncoder enc;
    char[4] buffer;
    size_t numBytes = enc.encode('Ж', buffer);
    assert(numBytes == 2);
    assert(cast(wchar[])(buffer[0..numBytes]) == [0x0416]);
}
