/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.core.atomic;

version(LDC)
{
    import ldc.llvmasm;

    /// Atomic Compare-And-Swap.
    pragma(inline, true)
    bool atomicCAS(shared(uint)* ptr, uint cmp, uint val) @nogc nothrow
    {
        version(X86_64)
        {
            return __asm!bool(
                "lock; cmpxchg $3, ($1); setz $0", 
                "={ax},r,r,r,~{memory},~{cc}", 
                ptr, cmp, val
            );
        }
        else version(X86)
        {
            return __asm!bool(
                "lock; cmpxchg $3, ($1); setz $0", 
                "={ax},r,r,r,~{memory},~{cc}", 
                ptr, cmp, val
            );
        }
        else version(AArch64)
        {
            return __asm!bool(
                "1: ldaxr w4, [$1]\n" ~
                "   cmp w4, ${2:w}\n" ~
                "   b.ne 2f\n" ~
                "   stlxr w5, ${3:w}, [$1]\n" ~
                "   cbnz w5, 1b\n" ~
                "   mov $0, #1\n" ~
                "   b 3f\n" ~
                "2: clrex\n" ~
                "   mov $0, #0\n" ~
                "3:",
                "=r,r,r,r,~{x4},~{x5},~{memory},~{cc}",
                ptr, cmp, val
            );
        }
        else
        {
            return true;
        }
    }

    /// Atomic write.
    pragma(inline, true)
    void atomicStore(shared(bool)* ptr, bool val) @nogc nothrow
    {
        version(X86_64)
        {
            __asm!void("xchg $1, ($0)", "r,r,~{memory}", ptr, val);
        }
        else version(X86)
        {
            __asm!void("xchg $1, ($0)", "r,r,~{memory}", ptr, val);
        }
        else version(AArch64)
        {
            __asm!void("stlrb ${1:w}, [$0]", "r,r,~{memory}", ptr, val);
        }
        else
        {
            *cast(bool*)p = val;
        }
    }

    /// Atomic read.
    pragma(inline, true)
    bool atomicLoad(const shared(bool)* ptr) @nogc nothrow
    {
        version(X86_64)
        {
            return __asm!bool("movb ($1), $0", "=r,r,~{memory}", ptr);
        }
        else version(X86)
        {
            return __asm!bool("movb ($1), $0", "=r,r,~{memory}", ptr);
        }
        else version(AArch64)
        {
            return __asm!bool("ldarb ${0:w}, [$1]", "=r,r,~{memory}", ptr);
        }
        else
        {
            return *cast(const(bool)*)p;
        }
    }
}
else
{
    /// Atomic Compare-And-Swap.
    pragma(inline, true)
    bool atomicCAS(shared(uint)* p, uint cmp, uint val) @nogc nothrow
    {
        version(X86_64)
        {
            asm @nogc nothrow
            {
                mov EAX, cmp;
                mov EDX, val;
                mov RCX, p;
                lock;
                cmpxchg [RCX], EDX;
                setz AL;
            }
        }
        else version(X86)
        {
            asm @nogc nothrow
            {
                mov EAX, cmp;
                mov EDX, val;
                mov ECX, p;
                lock;
                cmpxchg [ECX], EDX;
                setz AL;
            }
        }
        else
        {
            return true; 
        }
    }
    
    /// Atomic write.
    pragma(inline, true)
    void atomicStore(shared(bool)* p, bool val) @nogc nothrow
    {
        version(X86_64)
        {
            asm @nogc nothrow
            {
                mov AL, val;
                mov RCX, p;
                xchg [RCX], AL;
            }
        }
        else version(X86)
        {
            asm @nogc nothrow
            {
                mov AL, val;
                mov ECX, p;
                xchg [ECX], AL;
            }
        }
        else
        {
            *cast(bool*)p = val;
        }
    }
    
    /// Atomic read.
    pragma(inline, true)
    bool atomicLoad(const shared(bool)* p) @nogc nothrow
    {
        version(X86_64)
        {
            asm @nogc nothrow
            {
                mov RCX, p;
                mov AL, [RCX];
            }
        }
        else version(X86)
        {
            asm @nogc nothrow
            {
                mov ECX, p;
                mov AL, [ECX];
            }
        }
        else
        {
            return *cast(const(bool)*)p;
        }
    }
}
