/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Runtime error messages. Used by object.d and core modules.
 */
module rtld.core.errors;

import rtld.core.io;
import rtld.core.process;

pragma(inline, true)
void error(string msg) nothrow @nogc
{
    printStrLn(msg);
    exit(1);
}

pragma(inline, true)
void switchError(string file, size_t line) nothrow @nogc
{
    printFmtLn("{0}:{1}: no appropriate switch clause found", file, line);
    exit(1);
}

pragma(inline, true)
void assertionError(string file, size_t line) nothrow @nogc
{
    printFmtLn("{0}:{1}: assertion failed", file, line);
    exit(1);
}

pragma(inline, true)
void assertionErrorMsg(string file, size_t line, string msg) nothrow @nogc
{
    printFmtLn("{0}:{1}: assertion failed: {2}", file, line, msg);
    exit(1);
}

pragma(inline, true)
void sliceLengthMismatchError(size_t dstlen, size_t srclen) nothrow @nogc
{
    printFmtLn("Mismatched slice lengths in copy ({0} vs {1})", dstlen, srclen);
    exit(1);
}

pragma(inline, true)
void arrayBoundsSimpleError(string file, uint line) nothrow @nogc
{
    printFmtLn("{0}:{1}: array bounds violation (index or slice out of range)", file, line);
    exit(1);
}

pragma(inline, true)
void arrayIndexError(string file, uint line, size_t index, size_t length) nothrow @nogc
{
    printFmtLn("{0}:{1}: array index out of range: index {2} exceeds length {3}",
        file, line, index, length);
    exit(1);
}

pragma(inline, true) 
void arrayBoundsSliceError(string file, size_t line, size_t lower, size_t upper, size_t length) nothrow @nogc
{
    printFmtLn("{0}:{1}: array slice bounds out of range: [{2} .. {3}] exceeds length {4}", 
        file, line, lower, upper, length);
    exit(1);
}

pragma(inline, true)
void outOfMemoryError() nothrow @nogc
{
    printStrLn("Out of memory");
    exit(1);
}

pragma(inline, true)
void outOfMemoryError(string file, size_t line) nothrow @nogc
{
    printFmtLn("{0}:{1}: out of memory", file, line);
    exit(1);
}

///
pragma(inline, true)
void doubleFreeError() nothrow @nogc
{
    printStrLn("Double free or memory corruption");
    exit(1);
}

///
pragma(inline, true)
void doubleFreeError(string file, size_t line) nothrow @nogc
{
    printFmtLn("{0}:{1}: double free or memory corruption", file, line);
    exit(1);
}
