/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.core.file;

version(Posix)
{
    import rtld.sys.posix.fcntl;
    import rtld.sys.posix.unistd;
    
    alias PlatformHandle = int;
    enum InvalidHandle = -1;
}
else version(Windows)
{
    import rtld.sys.windows.windows;
    
    alias PlatformHandle = HANDLE;
    enum InvalidHandle = INVALID_HANDLE_VALUE;
}

import rtld.time.datetime;
import rtld.text.encodings;

enum ENOSYS = 38;

struct Result(T)
{
    T value;
    int error;
    
    pragma(inline, true)
    bool success() const scope @nogc nothrow
    {
        return error == 0;
    }
    
    pragma(inline, true)
    static Result!T Success(T val) scope @nogc nothrow
    {
        return Result!T(val, 0);
    }
    
    pragma(inline, true)
    static Result!T Failure(int code) scope @nogc nothrow
    {
        return Result!T(T.init, code);
    }
}

enum FileAccessMode
{
    Read,
    Write,
    ReadWrite
}

enum FilePermission: uint
{
    None    = 0,
    Read    = 1 << 0,
    Write   = 1 << 1,
    Execute = 1 << 2
}

struct FileStat
{
    DateTime creationTime;
    DateTime modificationTime;
    long size;
    uint permissions;
    bool isDirectory;
}

alias FileOpenResult = Result!File;
alias FileIOResult = Result!size_t;
alias FileSizeResult = Result!long;
alias FileStatResult = Result!FileStat;

struct File
{
    PlatformHandle handle = InvalidHandle;
    
    bool isValid() const @nogc nothrow
    {
        return handle != InvalidHandle;
    }
    
    static FileOpenResult open(string path, FileAccessMode accessMode = FileAccessMode.Read) @nogc nothrow
    {
        if (path.length == 0)
            return FileOpenResult.Failure(cast(int)0x16); // EINVAL / ERROR_INVALID_PARAMETER

        version(Posix)
        {
            char[1024] stackPath;
            
            if (path.length >= stackPath.length)
                return FileOpenResult.Failure(cast(int)36); // ENAMETOOLONG
            
            stackPath[0..path.length] = path[];
            stackPath[path.length] = '\0';

            int flags = 0;
            final switch(accessMode)
            {
                case FileAccessMode.Read:
                    flags = O_RDONLY;
                    break;
                case FileAccessMode.Write:
                    flags = O_WRONLY | O_CREAT | O_TRUNC;
                    break;
                case FileAccessMode.ReadWrite:
                    flags = O_RDWR | O_CREAT;
                    break;
            }
            flags |= O_CLOEXEC;

            int fd = openat(AT_FDCWD, stackPath.ptr, flags, cast(mode_t)0x1B4);
            
            if (fd < 0)
                return FileOpenResult.Failure(fd);
            
            return FileOpenResult.Success(File(fd));

        }
        else version(Windows)
        {
            ubyte[1024] stackPath;
            
            const(wchar)* utf16Path = toUTF16z(path, stackPath);
            if (utf16Path is null)
                return FileOpenResult.Failure(cast(int)87);

            DWORD dwAccess = 0;
            DWORD dwCreation = 0;
            final switch(accessMode)
            {
                case FileAccessMode.Read:
                    dwAccess = GENERIC_READ;
                    dwCreation = OPEN_EXISTING;
                    break;
                case FileAccessMode.Write:
                    dwAccess = GENERIC_WRITE;
                    dwCreation = CREATE_ALWAYS;
                    break;
                case FileAccessMode.ReadWrite:
                    dwAccess = GENERIC_READ | GENERIC_WRITE;
                    dwCreation = OPEN_ALWAYS;
                    break;
            }

            HANDLE h = CreateFileW(utf16Path, dwAccess, FILE_SHARE_READ, null, dwCreation, FILE_ATTRIBUTE_NORMAL, null);

            if (h == INVALID_HANDLE_VALUE)
                return FileOpenResult.Failure(cast(int)GetLastError());
            
            return FileOpenResult.Success(File(h));
        }
        else
        {
            // Fallback
            return FileOpenResult.Failure(ENOSYS);
        }
    }
    
    FileIOResult read(void[] buffer) scope @nogc nothrow
    {
        if (this.handle == InvalidHandle)
            return FileIOResult.Failure(cast(int)-1);
        
        if (buffer.length == 0)
            return FileIOResult.Success(0);

        version(Posix)
        {
            ssize_t bytesRead = .read(this.handle, buffer.ptr, buffer.length);
            
            if (bytesRead < 0)
                return FileIOResult.Failure(cast(int)bytesRead);
            
            return FileIOResult.Success(cast(size_t)bytesRead);
        }
        else version(Windows)
        {
            DWORD bytesRead = 0;
            DWORD toRead = (buffer.length > uint.max) ? uint.max : cast(DWORD)buffer.length;
            
            if (!ReadFile(this.handle, buffer.ptr, toRead, &bytesRead, null))
                return FileIOResult.Failure(cast(int)GetLastError());
            
            return FileIOResult.Success(cast(size_t)bytesRead);
        }
        else
        {
            // Fallback
            return FileIOResult.Failure(ENOSYS);
        }
    }
    
    FileIOResult write(const(void)[] buffer) scope @nogc nothrow
    {
        if (this.handle == InvalidHandle)
            return FileIOResult.Failure(cast(int)-1);
        
        if (buffer.length == 0)
            return FileIOResult.Success(0);

        version(Posix)
        {
            ssize_t bytesWritten = .write(this.handle, buffer.ptr, buffer.length);
            
            if (bytesWritten < 0)
                return FileIOResult.Failure(cast(int)bytesWritten);
            
            return FileIOResult.Success(cast(size_t)bytesWritten);
        }
        else version(Windows)
        {
            DWORD bytesWritten = 0;
            DWORD toWrite = (buffer.length > uint.max) ? uint.max : cast(DWORD)buffer.length;

            if (!WriteFile(this.handle, buffer.ptr, toWrite, &bytesWritten, null))
                return FileIOResult.Failure(cast(int)GetLastError());
            
            return FileIOResult.Success(cast(size_t)bytesWritten);
        }
        else
        {
            // Fallback
            return FileIOResult.Failure(ENOSYS);
        }
    }
    
    void flush() scope @nogc nothrow
    {
        if (this.handle == InvalidHandle)
            return;
        version(Posix)
            .fsync(this.handle);
        version(Windows)
            FlushFileBuffers(this.handle);
    }

    void close() scope @nogc nothrow
    {
        if (this.handle != InvalidHandle)
        {
            version(Posix)
                .close(this.handle);
            version(Windows)
                CloseHandle(this.handle);
            this.handle = InvalidHandle;
        }
    }
    
    FileSizeResult size() scope @nogc nothrow
    {
        if (this.handle == InvalidHandle)
            return FileSizeResult.Failure(cast(int)-1);

        version(Posix)
        {
            stat_t statBuf = void;
            int result = .fstat(this.handle, &statBuf);
            
            if (result < 0)
                return FileSizeResult.Failure(result);
            
            return FileSizeResult.Success(statBuf.st_size);
        } 
        else version(Windows)
        {
            long fileSize = 0;
            
            if (!GetFileSizeEx(this.handle, &fileSize))
                return FileSizeResult.Failure(cast(int)GetLastError());
            
            return FileSizeResult.Success(fileSize);
        }
        else
        {
            // Fallback
            return FileIOResult.Failure(ENOSYS);
        }
    }
    
    static FileStatResult stat(string path) @nogc nothrow
    {
        if (path.length == 0)
            return FileStatResult.Failure(cast(int)0x16);

        FileStat info;

        version(Posix)
        {
            char[1024] stackPath;
            
            if (path.length >= stackPath.length)
                return FileStatResult.Failure(cast(int)36); // ENAMETOOLONG
            
            stackPath[0..path.length] = path[];
            stackPath[path.length] = '\0';

            stat_t statBuf = void;
            if (.stat(stackPath.ptr, &statBuf) < 0)
                return FileStatResult.Failure(cast(int)-1);

            info.size = statBuf.st_size;
            info.creationTime = unixToDateTime(statBuf.st_atime); 
            info.modificationTime = unixToDateTime(statBuf.st_mtime);
            info.isDirectory = (statBuf.st_mode & 0xF000) == 0x4000;
            
            uint perms = FilePermission.None;
            if (.access(stackPath.ptr, R_OK) == 0) perms |= FilePermission.Read;
            if (.access(stackPath.ptr, W_OK) == 0) perms |= FilePermission.Write;
            if (.access(stackPath.ptr, X_OK) == 0) perms |= FilePermission.Execute;
            info.permissions = perms;

            return FileStatResult.Success(info);
        }
        else version(Windows)
        {
            ubyte[1024] stackPath;
            
            const(wchar)* utf16Path = toUTF16z(path, stackPath);
            if (utf16Path is null)
                return FileStatResult.Failure(cast(int)87);
            
            WIN32_FILE_ATTRIBUTE_DATA attrData = void;
            if (!GetFileAttributesExW(utf16Path, GetFileExInfoStandard, &attrData))
                return FileStatResult.Failure(cast(int)GetLastError());
            
            info.size = (cast(long)attrData.nFileSizeHigh << 32) | attrData.nFileSizeLow;

            info.creationTime = unixToDateTime(fileTimeToUnixSecs(attrData.ftCreationTime_dwLowDateTime, attrData.ftCreationTime_dwHighDateTime));
            info.modificationTime = unixToDateTime(fileTimeToUnixSecs(attrData.ftLastWriteTime_dwLowDateTime, attrData.ftLastWriteTime_dwHighDateTime));

            info.isDirectory = (attrData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0;

            uint perms = FilePermission.Read;
            if (!(attrData.dwFileAttributes & FILE_ATTRIBUTE_READONLY))
                perms |= FilePermission.Write;
            if (path.length > 4)
            {
                const(char)[] ext = path[$-4..$];
                if (ext == ".exe" || ext == ".EXE" || ext == ".bat" || ext == ".BAT")
                    perms |= FilePermission.Execute;
            }
            info.permissions = perms;

            return FileStatResult.Success(info);
        }
        else
        {
            return FileStatResult.Failure(ENOSYS);
        }
    }
}
