/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.core.io;

import rtld.core.traits;
import rtld.text.encodings: toUTF8z;
import rtld.container.array;

version(Windows)
{
    import rtld.sys.windows;
    
    private __gshared HANDLE hStdOut;
}
else version(Posix)
{
    import rtld.sys.posix.unistd;
}

void printStr(const(char)[] msg) @nogc nothrow
{
    if (msg.length == 0)
        return;
    
    version(Windows)
    {
        if (hStdOut is null)
            hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);
        if (hStdOut && hStdOut != INVALID_HANDLE_VALUE)
        {
            DWORD written;
            WriteFile(hStdOut, msg.ptr, cast(DWORD)msg.length, &written, null);
        }
    }
    else version(Posix)
    {
        write(STDOUT_FILENO, msg.ptr, cast(size_t_posix)msg.length);
    }
}

void printStrLn(const(char)[] msg) @nogc nothrow
{
    printStr(msg);
    printStr("\n");
}

void print(T)(T arg, bool quote = false) @nogc nothrow
{
    static if (isString!T)
    {
        if (quote)
            printStr("\"");
        printStr(arg);
        if (quote)
            printStr("\"");
    }
    else static if (isWString!T)
    {
        if (quote)
            printStr("\"");
        ubyte[1024] stackBuffer = void;
        const(char)* utf8Resultz = toUTF8z(arg, stackBuffer[]);
        if (utf8Resultz !is null)
        {
            size_t len = 0;
            while (utf8Resultz[len] != '\0')
                len++;
            printStr(utf8Resultz[0..len]);
        }
        else
            printStr("?");
        if (quote)
            printStr("\"");
    }
    else static if (isInteger!T)
    {
        if (arg == 0)
        {
            printStr("0");
            return;
        }
        
        if (arg < 0)
        {
            printStr("-");
            arg = -arg;
        }
        
        char[20] buf;
        size_t pos = buf.length;
        
        while(arg > 0)
        {
            pos--;
            buf[pos] = cast(char)('0' + (arg % 10));
            arg /= 10;
        }
        
        printStr(cast(string)buf[pos..$]);
    }
    else static if (isFloatingPoint!T)
    {
        if (arg != arg)
        {
            printStr("nan");
            return;
        }
        if (arg == T.infinity)
        {
            printStr("inf");
            return;
        }
        if (arg == -T.infinity)
        {
            printStr("-inf");
            return;
        }
        if (arg < 0)
        {
            printStr("-");
            arg = -arg;
        }

        long integerPart = cast(long)arg;
        print(integerPart);
        printStr(".");

        double fractionalPart = arg - integerPart;
        int precision = 6;
        
        char[20] buf;
        size_t pos = 0;

        while(precision > 0)
        {
            fractionalPart *= 10;
            int digit = cast(int)fractionalPart;
            
            buf[pos] = cast(char)('0' + digit);
            pos++;
            
            fractionalPart -= digit;
            precision--;
        }

        while(pos > 1 && buf[pos - 1] == '0')
        {
            pos--;
        }

        printStr(cast(string)buf[0..pos]);
    }
    else static if (is(T == bool))
    {
        printStr(arg ? "true" : "false");
    }
    else static if (isArray!T)
    {
        printStr("[");
        foreach(size_t i, ref element; arg)
        {
            if (i > 0)
                printStr(", ");
            print(element, true);
        }
        printStr("]");
    }
    else static if (isConvertibleToString!T)
    {
        static if (isObject!T)
        {
            if (arg is null)
            {
                printStr("null");
                return;
            }
        }
        printStr(arg.toString());
    }
    /*
    else static if (__traits(hasMember, T, "toString") && 
                    is(typeof(arg.toString((const(char)[] s) => printStr(s)))))
    {
        void delegate(const(char)[]) @nogc nothrow sink;
        sink.ptr = null;
        sink.funcptr = &printStr;
        arg.toString(sink);
    }
    */
    else static if (is(T == struct))
    {
        printStr(__traits(identifier, T));
        printStr("(");
        static foreach (i; 0..arg.tupleof.length)
        {
            static if (i > 0)
                printStr(", ");
            print(arg.tupleof[i], true);
        }
        printStr(")");
    }
    else static if (isObject!T)
    {
        if (arg is null)
        {
            printStr("null");
            return;
        }
        
        static if (is(T == interface))
        {
            auto obj = cast(Object)arg;
            auto classInfo = obj ? typeid(obj) : null;
        }
        else
        {
            auto classInfo = typeid(arg);
        }

        if (classInfo !is null)
        {
            string fullName = classInfo.name;
            
            size_t lastDot = 0;
            foreach (i; 0..fullName.length)
            {
                if (fullName[i] == '.')
                    lastDot = i + 1;
            }
            
            printStr(fullName[lastDot..$]);
        }
        else
        {
            printStr("{?}");
        }
    }
    else static if (isPointer!T)
    {
        if (arg is null)
        {
            printStr("null");
            return;
        }

        printStr("0x");

        size_t addr = cast(size_t)arg;
        
        enum hexLength = size_t.sizeof * 2;
        char[hexLength] buf;
        
        static immutable char[16] hexDigits = "0123456789abcdef";

        for (size_t i = hexLength; i > 0; i--)
        {
            buf[i - 1] = hexDigits[addr & 0xF];
            addr >>= 4;
        }

        printStr(cast(string)buf);
    }
    else
    {
        printStr("{?}");
    }
}

void printLn(T)(T arg) @nogc nothrow
{
    print(arg);
    printStr("\n");
}

void printFmt(Args...)(const(char)[] fmt, Args args) @nogc nothrow
{
    size_t lastIdx = 0;

    for (size_t i = 0; i < fmt.length; i++) 
    {
        if (fmt[i] == '{') 
        {
            size_t j = i + 1;
            int argIdx = 0;
            bool hasIndex = false;

            while (j < fmt.length && fmt[j] >= '0' && fmt[j] <= '9') 
            {
                argIdx = (argIdx * 10) + (fmt[j] - '0');
                hasIndex = true;
                j++;
            }

            if (j < fmt.length && fmt[j] == '}' && hasIndex) 
            {
                if (i > lastIdx) {
                    printStr(fmt[lastIdx .. i]);
                }

                bool found = false;

                static foreach (idx, Arg; Args)
                {
                    if (!found && argIdx == idx)
                    {
                        print(args[idx]);
                        found = true;
                    }
                }

                if (!found)
                {
                    printStr("{?}");
                }
                
                i = j; 
                lastIdx = i + 1;
            }
        }
    }
    
    if (lastIdx < fmt.length) {
        printStr(fmt[lastIdx..$]);
    }
}

void printFmtLn(Args...)(const(char)[] fmt, Args args) @nogc nothrow
{
    printFmt(fmt, args);
    printStr("\n");
}
