/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.core.io;

import rtld.core.traits;
import rtld.libc.stdio;
import rtld.text.encodings: toUTF8z;

version(Windows)
{
    import rtld.sys.windows;
    private __gshared HANDLE hStdOut;
}
else version(Posix)
{
    extern(C) nothrow @nogc
    {
        import rtld.libc.stdint: c_long;
        c_long write(int fd, const(void)* buf, c_long count);
    }
    
    private enum STDOUT_FILENO = 1;
}

void printStr(const(char)[] msg) @nogc nothrow
{
    if (msg.length == 0)
        return;
    
    version(Windows)
    {
        if (hStdOut is null)
            hStdOut = GetStdHandle(STD_OUTPUT_HANDLE);
        if (hStdOut && hStdOut != INVALID_HANDLE_VALUE)
        {
            DWORD written;
            WriteFile(hStdOut, msg.ptr, cast(DWORD)msg.length, &written, null);
        }
    }
    else version(Posix)
    {
        write(STDOUT_FILENO, msg.ptr, cast(c_long)msg.length);
    }
}

void printStrLn(const(char)[] msg) @nogc nothrow
{
    printStr(msg);
    printStr("\n");
}

void print(T)(T arg)
{
    static if (is(T == const(char)[]) || is(T == string) || is(T == char[]))
    {
        printStr(arg);
    }
    else static if (is(T == const(wchar)[]) || is(T == wstring) || is(T == wchar[]))
    {
        ubyte[1024] stackBuffer = void;
        const(char)* utf8Resultz = toUTF8z(arg, stackBuffer[]);
        if (utf8Resultz !is null)
        {
            size_t len = 0;
            while (utf8Resultz[len] != '\0')
                len++;
            printStr(utf8Resultz[0..len]);
        }
        else
            printStr("{ERROR}");
    }
    else static if (is(T: long))
    {
        char[32] tmpBuf = void;
        int len;
        static if (is(T == ulong) || is(T == uint) || is(T == ushort) || is(T == ubyte))
            len = snprintf(tmpBuf.ptr, tmpBuf.length, "%llu".ptr, cast(ulong)arg);
        else
            len = snprintf(tmpBuf.ptr, tmpBuf.length, "%lld".ptr, cast(long)arg);
        if (len > 0 && len < tmpBuf.length)
            printStr(tmpBuf[0..len]);
        else
            printStr("{INT_ERR}");
    }
    else static if (is(T: double) || is(T: float))
    {
        char[32] tmpBuf = void;
        int len = snprintf(tmpBuf.ptr, tmpBuf.length, "%g".ptr, cast(T)arg);
        if (len > 0 && len < tmpBuf.length)
            printStr(tmpBuf[0..len]);
        else
            printStr("{ERROR}");
    }
    else static if (is(T == bool))
    {
        printStr(arg ? "true" : "false");
    }
    else static if (isArray!T)
    {
        printStr("[");
        foreach(size_t i, ref element; arg)
        {
            if (i > 0)
                printStr(", ");
            print(element);
        }
        printStr("]");
    }
    else static if (__traits(hasMember, T, "toString") && 
                    is(typeof(arg.toString()) : const(char)[]))
    {
        static if (is(T == class) || is(T == interface))
        {
            if (arg is null)
            {
                printStr("null");
                return;
            }
        }
        printStr(arg.toString());
    }
    /*
    else static if (__traits(hasMember, T, "toString") && 
                    is(typeof(arg.toString((const(char)[] s) => printStr(s)))))
    {
        void delegate(const(char)[]) @nogc nothrow sink;
        sink.ptr = null;
        sink.funcptr = &printStr;
        arg.toString(sink);
    }
    */
    else static if (is(T == struct))
    {
        printStr(__traits(identifier, T));
        printStr("(");
        static foreach (i; 0..arg.tupleof.length)
        {
            static if (i > 0)
                printStr(", ");
            print(arg.tupleof[i]);
        }
        printStr(")");
    }
    else
    {
        printStr("{?}");
    }
}

void printLn(T)(T arg)
{
    print(arg);
    printStr("\n");
}

void printFmt(Args...)(const(char)[] fmt, Args args)
{
    size_t lastIdx = 0;

    for (size_t i = 0; i < fmt.length; i++) 
    {
        if (fmt[i] == '{') 
        {
            size_t j = i + 1;
            int argIdx = 0;
            bool hasIndex = false;

            while (j < fmt.length && fmt[j] >= '0' && fmt[j] <= '9') 
            {
                argIdx = (argIdx * 10) + (fmt[j] - '0');
                hasIndex = true;
                j++;
            }

            if (j < fmt.length && fmt[j] == '}' && hasIndex) 
            {
                if (i > lastIdx) {
                    printStr(fmt[lastIdx .. i]);
                }

                bool found = false;

                static foreach (idx, Arg; Args) 
                {
                    if (!found && argIdx == idx) 
                    {
                        print(args[idx]);
                        found = true;
                    }
                }

                if (!found) 
                {
                    printStr("{!INDEX_OUT_OF_BOUNDS}");
                }
                
                i = j; 
                lastIdx = i + 1;
            }
        }
    }
    
    if (lastIdx < fmt.length) {
        printStr(fmt[lastIdx..$]);
    }
}

void printFmtLn(Args...)(const(char)[] fmt, Args args)
{
    printFmt(fmt, args);
    printStr("\n");
}
