/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.core.memory;

import rtld.core.atomic;
import rtld.core.io;
import rtld.core.traits;
import rtld.core.errors;
import rtld.core.process;
import rtld.libc.string;
import rtld.memory;

enum ulong MP_RECORD_MAGIC = 0xDEADBEEF;

struct MPRecord
{
    ulong magic;
    string name;
    string file;
    ulong line;
    ulong size;
    MPRecord* prev;
    MPRecord* next;
    ulong _padding;
}

version(WebAssembly)
{
}
else version(FreeStanding)
{
}
else
{
    enum MPRecordSize = MPRecord.sizeof;
    
    private __gshared
    {
        bool _memoryProfilerEnabled = true;
        MPRecord* profilerHead = null;
        shared(uint) profilerLock = 0;
        ulong _allocatedMemory = 0;
        ulong _allocationCount = 0;
    }
    
    ///
    ulong allocatedMemory() @nogc nothrow
    {
        return _allocatedMemory;
    }
    
    ///
    ulong allocationCount() @nogc nothrow
    {
        return _allocationCount;
    }
    
    ///
    MPRecord* memRecord(void* memory) @nogc nothrow
    {
        if (_memoryProfilerEnabled && memory)
        {
            MPRecord* rec = cast(MPRecord*)(memory - MPRecordSize);
            if (rec.magic == MP_RECORD_MAGIC)
                return rec;
        }
        return null;
    }
    
    ///
    pragma(inline, true)
    void memRecordClear(MPRecord* rec) @nogc nothrow
    {
        rec.magic = 0x0;
        rec.name = [];
        rec.file = [];
        rec.line = 0x0;
        rec.size = 0x0;
        rec.prev = null;
        rec.next = null;
    }
    
    ///
    pragma(inline, true)
    bool memoryProfilerEnabled() @nogc nothrow
    {
        return _memoryProfilerEnabled;
    }
    
    ///
    pragma(inline, true)
    void memoryProfilerEnabled(bool mode) @nogc nothrow
    {
        _memoryProfilerEnabled = mode;
    }
    
    private void lockProfiler() @nogc nothrow
    {
        while(atomicCAS(&profilerLock, 0, 1) != 0)
        {
            version(LDC)
            {
                import ldc.llvmasm;
                version(X86)          { __asm!void("pause", "~{memory}"); }
                else version(X86_64)  { __asm!void("pause", "~{memory}"); }
                else version(AArch64) { __asm!void("yield", "~{memory}"); }
            }
            else version(X86_64) { asm @nogc nothrow { db 0xF3, 0x90; } }
            else version(X86)    { asm @nogc nothrow { db 0xF3, 0x90; } }
        }
    }

    private void unlockProfiler() @nogc nothrow
    {
        atomicStore(cast(shared(bool)*)&profilerLock, false);
    }
    
    // TODO: printMemoryLog
    
    ///
    void printMemoryLeaks() @nogc nothrow
    {
        if (!_memoryProfilerEnabled)
            return;
        
        stdout.printLn("=== MEMORY LEAK REPORT ===");
        
        lockProfiler();
        if (profilerHead is null)
        {
            stdout.printLn("No allocations.");
            unlockProfiler();
            stdout.printLn("==========================");
            return;
        }

        stdout.printFmtLn("Active allocations: {0}, total bytes: {1}\n", _allocationCount, _allocatedMemory);

        MPRecord* current = profilerHead;
        while(current !is null)
        {
            stdout.printFmtLn("Leak: {0} ({1} byte(s)) @ {2}:{3}",
                current.name,
                current.size,
                current.file,
                current.line
            );
            current = current.next;
        }
        stdout.printLn("==========================");
        unlockProfiler();
    }
    
    /// Allocates an untyped buffer.
    void[] allocate(size_t len, string file = __FILE__, int line = __LINE__)
    {
        size_t allocSize = len;
        if (_memoryProfilerEnabled)
            allocSize += MPRecordSize;
        void* memory = defaultAllocator.allocate(allocSize).ptr;
        if (memory is null)
            outOfMemoryError(file, line);
        
        if (_memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)memory;
            *rec = MPRecord(MP_RECORD_MAGIC, "void[]", file, line, len, null, null);
            
            lockProfiler();
            rec.next = profilerHead;
            if (profilerHead)
                profilerHead.prev = rec;
            profilerHead = rec;
            _allocatedMemory += len;
            _allocationCount++;
            unlockProfiler();
            
            memory += MPRecordSize;
        }
        
        return memory[0..len];
    }
    
    /// Allocates an object.
    T allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__)
        if (is(T == class))
    {
        enum objectSize = __traits(classInstanceSize, T);
        size_t allocSize = objectSize;
        if (_memoryProfilerEnabled)
            allocSize += MPRecordSize;
        void* memory = defaultAllocator.allocate(allocSize).ptr;
        if (memory is null)
            outOfMemoryError(file, line);
        
        if (_memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)memory;
            *rec = MPRecord(MP_RECORD_MAGIC, T.stringof, file, line, objectSize, null, null);
            
            lockProfiler();
            rec.next = profilerHead;
            if (profilerHead)
                profilerHead.prev = rec;
            profilerHead = rec;
            _allocatedMemory += objectSize;
            _allocationCount++;
            unlockProfiler();
            
            memory += MPRecordSize;
        }
        
        const(void)[] initSymbol = __traits(initSymbol, T);
        memcpy(memory, initSymbol.ptr, objectSize);
        auto instance = cast(T)memory;
        static if (__traits(hasMember, T, "__ctor"))
            instance.__ctor(args);
        return instance;
    }
    
    /// Allocates an structure.
    T* allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__)
        if (is(T == struct))
    {
        enum objectSize = T.sizeof;
        size_t allocSize = objectSize;
        if (_memoryProfilerEnabled)
            allocSize += MPRecordSize;
        void* memory = defaultAllocator.allocate(allocSize).ptr;
        if (memory is null)
            outOfMemoryError(file, line);
        
        if (_memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)memory;
            *rec = MPRecord(MP_RECORD_MAGIC, T.stringof, file, line, objectSize, null, null);
            
            lockProfiler();
            rec.next = profilerHead;
            if (profilerHead)
                profilerHead.prev = rec;
            profilerHead = rec;
            _allocatedMemory += objectSize;
            _allocationCount++;
            unlockProfiler();
            
            memory += MPRecordSize;
        }
        
        T* instance = cast(T*)memory;
        *instance = T(args);
        return instance;
    }
    
    /// Allocates an array.
    T allocate(T)(size_t length, string file = __FILE__, int line = __LINE__)
        if (isArray!T)
    {
        alias AT = ElementType!T;
        size_t objectSize = length * AT.sizeof;
        size_t allocSize = objectSize;
        if (_memoryProfilerEnabled)
            allocSize += MPRecordSize;
        void* memory = defaultAllocator.allocate(allocSize).ptr;
        if (memory is null)
            outOfMemoryError(file, line);
        
        if (_memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)memory;
            *rec = MPRecord(MP_RECORD_MAGIC, T.stringof, file, line, objectSize, null, null);
            
            lockProfiler();
            rec.next = profilerHead;
            if (profilerHead)
                profilerHead.prev = rec;
            profilerHead = rec;
            _allocatedMemory += objectSize;
            _allocationCount++;
            unlockProfiler();
            
            memory += MPRecordSize;
        }
        
        T arr = cast(T)memory[0..objectSize];
        foreach(ref v; arr)
            v = v.init;
        return arr;
    }
    
    /// Deallocates an object.
    void deallocate(T)(ref T obj, string file = __FILE__, int line = __LINE__)
        if (is(T == class) || is(T == interface))
    {
        if (obj is null)
            return;
        
        void* memory = cast(void*)obj;
        enum objectSize = __traits(classInstanceSize, T);
        size_t allocSize = objectSize;
        if (_memoryProfilerEnabled)
            allocSize += MPRecordSize;
        
        static if (__traits(hasMember, T, "__dtor"))
            obj.__dtor();
        
        if (_memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)(memory - MPRecordSize);
            if (rec.magic == MP_RECORD_MAGIC)
            {
                lockProfiler();
                if (rec.prev) rec.prev.next = rec.next;
                if (rec.next) rec.next.prev = rec.prev;
                if (profilerHead == rec) profilerHead = rec.next;
                _allocatedMemory -= rec.size;
                _allocationCount--;
                unlockProfiler();
            }
            else
                doubleFreeError(file, line);
            memRecordClear(rec);
            memory -= MPRecordSize;
        }
        
        defaultAllocator.deallocate(memory[0..allocSize]);
        obj = null;
    }
    
    /// Deallocates a structure.
    void deallocate(T)(T* pstruct, string file = __FILE__, int line = __LINE__)
        if (is(T == struct))
    {
        if (pstruct is null)
            return;
        
        void* memory = cast(void*)pstruct;
        enum objectSize = T.sizeof;
        size_t allocSize = objectSize;
        if (_memoryProfilerEnabled)
            allocSize += MPRecordSize;
        
        if (_memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)(memory - MPRecordSize);
            if (rec.magic == MP_RECORD_MAGIC)
            {
                lockProfiler();
                if (rec.prev) rec.prev.next = rec.next;
                if (rec.next) rec.next.prev = rec.prev;
                if (profilerHead == rec) profilerHead = rec.next;
                _allocatedMemory -= rec.size;
                _allocationCount--;
                unlockProfiler();
            }
            else
                doubleFreeError(file, line);
            memRecordClear(rec);
            memory -= MPRecordSize;
        }
        
        defaultAllocator.deallocate(memory[0..allocSize]);
    }
    
    /// Deallocates an array.
    void deallocate(T)(ref T arr, string file = __FILE__, int line = __LINE__)
        if (isArray!T)
    {
        if (arr.ptr is null)
            return;
        
        alias AT = ElementType!T;
        size_t objectSize = arr.length * AT.sizeof;
        size_t allocSize = objectSize;
        if (_memoryProfilerEnabled)
            allocSize += MPRecordSize;
        
        void* memory = cast(void*)arr.ptr;
        if (_memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)(memory - MPRecordSize);
            if (rec.magic == MP_RECORD_MAGIC)
            {
                lockProfiler();
                if (rec.prev) rec.prev.next = rec.next;
                if (rec.next) rec.next.prev = rec.prev;
                if (profilerHead == rec) profilerHead = rec.next;
                _allocatedMemory -= rec.size;
                _allocationCount--;
                unlockProfiler();
            }
            else
                doubleFreeError(file, line);
            memRecordClear(rec);
            memory -= MPRecordSize;
        }
        
        defaultAllocator.deallocate(memory[0..allocSize]);
        arr = [];
    }
    
    alias New = allocate;
    alias Delete = deallocate;
}
