/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.core.memory;

import rtld.core.traits;
import rtld.core.errors;
import rtld.libc.string;
import rtld.memory;

enum ulong MP_RECORD_MAGIC = 0xBADBEEF;

struct MPRecord
{
    ulong magic;
    string name;
    string file;
    ulong line;
    ulong size;
}

version(WebAssembly)
{
}
else version(FreeStanding)
{
}
else
{
    enum MPRecordSize = MPRecord.sizeof;
    
    __gshared bool memoryProfilerEnabled = true;
    
    ///
    MPRecord* memRecord(void* memory)
    {
        if (memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)(memory - MPRecordSize);
            if (rec.magic == MP_RECORD_MAGIC)
                return rec;
            else
                return null;
        }
        else
            return null;
    }
    
    ///
    void memRecordClear(MPRecord* rec)
    {
        rec.magic = 0x0;
        rec.name = [];
        rec.file = [];
        rec.line = 0x0;
        rec.size = 0x0;
    }
    
    /// Allocates an object.
    T allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__)
        if (is(T == class))
    {
        enum objectSize = __traits(classInstanceSize, T);
        size_t allocSize = objectSize;
        if (memoryProfilerEnabled)
            allocSize += MPRecordSize;
        void* memory = defaultAllocator.allocate(allocSize).ptr;
        if (!memory)
            onOutOfMemoryError();
        
        if (memoryProfilerEnabled)
        {
            *cast(MPRecord*)memory = MPRecord(MP_RECORD_MAGIC, T.stringof, file, line, objectSize);
            //_allocatedMemory += size; // TODO
            memory += MPRecordSize;
        }
        
        const(void)[] initSymbol = __traits(initSymbol, T);
        memcpy(memory, initSymbol.ptr, objectSize);
        auto instance = cast(T)memory;
        static if (__traits(hasMember, T, "__ctor"))
            instance.__ctor(args);
        return instance;
    }
    
    /// Allocates an array.
    T allocate(T)(size_t length, string file = __FILE__, int line = __LINE__)
        if (isArray!T)
    {
        alias AT = ElementType!T;
        size_t objectSize = length * AT.sizeof;
        size_t allocSize = objectSize;
        if (memoryProfilerEnabled)
            allocSize += MPRecordSize;
        void* memory = defaultAllocator.allocate(allocSize).ptr;
        if (!memory)
            onOutOfMemoryError();
        
        if (memoryProfilerEnabled)
        {
            *cast(MPRecord*)memory = MPRecord(MP_RECORD_MAGIC, T.stringof, file, line, objectSize);
            //_allocatedMemory += size; // TODO
            memory += MPRecordSize;
        }
        
        T arr = cast(T)memory[0..objectSize];
        foreach(ref v; arr)
            v = v.init;
        return arr;
    }
    
    /// Deallocates an object.
    void deallocate(T)(ref T obj)
        if (is(T == class) || is(T == interface))
    {
        if (obj is null)
            return;
        
        void* memory = cast(void*)obj;
        enum objectSize = __traits(classInstanceSize, T);
        size_t allocSize = objectSize;
        if (memoryProfilerEnabled)
            allocSize += MPRecordSize;
        
        static if (__traits(hasMember, T, "__dtor"))
            obj.__dtor();
        
        if (memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)(memory - MPRecordSize);
            memRecordClear(rec);
            //_allocatedMemory -= rec.size; // TODO
            memory -= MPRecordSize;
        }
        
        defaultAllocator.deallocate(memory[0..allocSize]);
        obj = null;
    }
    
    /// Deallocates an array.
    void deallocate(T)(ref T arr)
        if (isArray!T)
    {
        if (arr.ptr is null)
            return;
        
        alias AT = ElementType!T;
        size_t objectSize = arr.length * AT.sizeof;
        size_t allocSize = objectSize;
        if (memoryProfilerEnabled)
            allocSize += MPRecordSize;
        
        void* memory = cast(void*)arr.ptr;
        if (memoryProfilerEnabled)
        {
            MPRecord* rec = cast(MPRecord*)(memory - MPRecordSize);
            memRecordClear(rec);
            //_allocatedMemory -= rec.size; // TODO
            memory -= MPRecordSize;
        }
        
        defaultAllocator.deallocate(memory[0..allocSize]);
        arr = [];
    }
    
    alias New = allocate;
    alias Delete = deallocate;
}
