/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.core.thread;

version(Windows)
{
    import rtld.sys.windows.windows;
}
else version(Posix)
{
    import rtld.libc.time;
    import rtld.sys.posix.pthread;
    import rtld.sys.posix.time;
}

/**
 * Base class for creating threads
 */
class Thread
{
   protected:
    
    void function() func;
    void delegate() dlgt;
    bool callFunc;
    bool initialized = false;
    
   public:
    
    version(Windows)
    {
        private void* winThread;
    }
    else version(Posix)
    {
        private pthread_t posixThread;
        private bool running = false;
    }
    
    /// Constructor. Initializes a thread using a function pointer
    this(void function() func)
    {
        this.func = func;
        callFunc = true;
    }
    
    /// Constructor. Initializes a thread using a delegate
    this(void delegate() dlgt)
    {
        this.dlgt = dlgt;
        callFunc = false;
    }
    
    /// Destructor
    ~this()
    {
        version(Windows)
        {
            if (winThread)
                CloseHandle(winThread);
        }
        else version(Posix)
        {
            if (initialized)
                pthread_detach(posixThread);
        }
    }
    
    /// Starts the thread
    final void start() nothrow @nogc
    {
        version(Windows)
        {
            if (winThread)
                CloseHandle(winThread);
            uint threadId;
            winThread = CreateThread(null, cast(size_t)0, &winThreadFunc, cast(void*)this, cast(uint)0, &threadId);
            assert(winThread !is null);
            initialized = true;
        }
        else version(Posix)
        {
            running = true;
            int error = pthread_create(&posixThread, null, &posixThreadFunc, cast(void*)this);
            assert(error == 0);
            initialized = true;
        }
    }
    
    /// Waits for the thread to terminate
    final void join() nothrow @nogc
    {
        version(Windows)
        {
            WaitForMultipleObjects(1u, &winThread, 1, INFINITE);
        }
        else version(Posix)
        {
            pthread_join(posixThread, null);
        }
    }
    
    /// Checks if thread is running
    final bool isRunning() nothrow @nogc
    {
        version(Windows)
        {
            uint c = 0;
            GetExitCodeThread(winThread, &c);
            return (c == STILL_ACTIVE);
        }
        else version(Posix)
        {
            return running;
        }
        else
        {
            return false;
        }
    }
    
    /// Stops the thread immediately. This functionality is unsafe, use with care
    final void terminate() nothrow @nogc
    {
        version(Windows)
        {
            TerminateThread(winThread, 1);
        }
        else version(Posix)
        {
            pthread_cancel(posixThread);
        }
    }
    
    version(Windows)
    {
        private extern(Windows) static uint winThreadFunc(const(void)* lpParam)
        {
            Thread t = cast(Thread)lpParam;
            if (t.callFunc)
                t.func();
            else
                t.dlgt();
            return 0;
        }
    }
    else version(Posix)
    {
        private extern(C) static void* posixThreadFunc(void* arg)
        {
            Thread t = cast(Thread)arg;
            if (t.callFunc)
                t.func();
            else
                t.dlgt();
            t.running = false;
            return null;
        }
    }
    
    /// Wait for specified amout of milliseconds
    static void sleep(uint msec) nothrow @nogc
    {
        version(Windows)
        {
            Sleep(msec);
        }
        else version(Posix)
        {
            timespec ts;
            ts.tv_sec = msec / 1000;
            ts.tv_nsec = (msec % 1000) * 1000000;
            nanosleep(&ts, null);
        }
    }
}
