/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.core.traits;

///
/*
template Unqual(T)
{
    static if (is(T U == const U) || is(T U == immutable U) ||
               is(T U == shared U) || is(T U == inout U))
        alias Unqual = U;
    else
        alias Unqual = T;
}
*/

///
template Unqual(T: const U, U)
{
    alias Unqual = U;
}

///
template isInteger(T)
{
    enum isInteger = is(Unqual!T == int) || is(Unqual!T == uint) ||
                     is(Unqual!T == byte) || is(Unqual!T == ubyte) ||
                     is(Unqual!T == short) || is(Unqual!T == ushort) ||
                     is(Unqual!T == long) || is(Unqual!T == ulong);
}

///
template isFloatingPoint(T)
{
    enum isFloatingPoint = is(Unqual!T == float) || is(Unqual!T == double) || is(Unqual!T == real);
}

///
template isSingleFloat(T)
{
    enum isSingleFloat = is(Unqual!T == float);
}

///
template isStaticArray(T)
{
    enum isStaticArray = is(T == U[N], U, size_t N);
}

///
template isDynamicArray(T)
{
    enum isDynamicArray = is(T == U[], U);
}

///
template isArray(T)
{
    enum isArray = isDynamicArray!T || isStaticArray!T;
}

///
template isString(T)
{
    enum isString = is(T == string) || is(T == char[]) || is(T: const(char)[]);
}

///
template isWString(T)
{
    enum isWString = is(T == wstring) || is(T == wchar[]) || is(T == const(wchar)[]);
}

///
template ElementType(T)
{
    static if (is(T == U[], U))
        alias ElementType = U;
}

///
template isClass(T)
{
    enum isClass = is(T == class);
}

///
template isInterface(T)
{
    enum isInterface = is(T == interface);
}

///
template hasConstructor(T)
{
    enum hasConstructor = __traits(hasMember, T, "__ctor");
}

///
template hasDestructor(T)
{
    enum hasDestructor = __traits(hasMember, T, "__dtor");
}

///
template isFinalizable(T)
{
    enum isFinalizable =
        is(T == class) ||
        is(T == interface) ||
        hasDestructor!T ||
        isDynamicArray!T;
}
