/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * A simple cross-platform window abstraction.
 */
module rtld.gui.window;

version(Windows)
{
    version = WindowsSystemPresent;
}
else version(linux)
{
    version = WindowsSystemPresent;
}

version(WindowsSystemPresent):

import rtld.time.timer;
import rtld.gl.context;

version(Windows)
{
    public import rtld.sys.windows.windows;
}
else version(linux)
{
    public import rtld.sys.linux.x11;
}

struct SystemWindowCreationSettings
{
    uint x;
    uint y;
    uint width;
    uint height;
    bool center;
    const(wchar)* title;
}

struct SystemWindowInfo
{
    version(Windows)
    {
        HWND hwnd;
        HDC hdc;
        WNDCLASSW wc;
        MSG message;
    }
    else version(linux)
    {
        Window window;
        Display* display;
        Screen* screen;
        Window root;
        ulong wmProtocols;
        ulong wmDelete;
        XEvent event;
    }
    
    bool valid = false;
}

struct SystemWindowEvent
{
    version(Windows)
    {
        MSG message;
    }
    else version(linux)
    {
        ulong wmProtocols;
        ulong wmDelete;
        XEvent xEvent;
    }
}

class SystemWindow
{
    SystemWindowCreationSettings settings;
    SystemWindowInfo info;
    protected SystemWindowEvent event;
    bool glPresent = false;
    OpenGLVersion glVersion;
    GLContext glContext;
    
    uint x = 0;
    uint y = 0;
    uint width = 0;
    uint height = 0;
    bool running = false;
    
    uint displayWidth = 0;
    uint displayHeight = 0;
    
    double timer = 0.0;
    double timeStep = 1.0 / 60.0;
    
    this(SystemWindowCreationSettings* settings)
    {
        this.settings = *settings;
        this.x = settings.x;
        this.y = settings.y;
        this.width = settings.width;
        this.height = settings.height;
        
        version(Windows)
        {
            info.wc.style = 0;
            info.wc.lpfnWndProc = &WndProc;
            info.wc.cbClsExtra = 0;
            info.wc.cbWndExtra = 0;
            info.wc.hInstance = GetModuleHandle(null);
            info.wc.hIcon = null;
            info.wc.hCursor = LoadCursor(null, IDC_ARROW);
            info.wc.hbrBackground = cast(HBRUSH)GetStockObject(BLACK_BRUSH);
            info.wc.lpszMenuName = null;
            info.wc.lpszClassName = "RTLDWindow"w.ptr;

            if (RegisterClassW(&info.wc) == 0)
                return;
            
            uint style = WS_OVERLAPPEDWINDOW | WS_VISIBLE | WS_CLIPSIBLINGS | WS_CLIPCHILDREN;
            RECT rect;
            rect.left = settings.x;
            rect.top = settings.y;
            rect.right = settings.x + settings.width;
            rect.bottom = settings.y + settings.height;
            AdjustWindowRectEx(&rect, style, FALSE, 0);
            int finalWidth = rect.right - rect.left;
            int finalHeight = rect.bottom - rect.top;
            
            this.width = cast(uint)finalWidth;
            this.height = cast(uint)finalHeight;

            displayWidth = GetSystemMetrics(SM_CXSCREEN);
            displayHeight = GetSystemMetrics(SM_CYSCREEN);
            
            if (settings.center)
            {
                this.x = (displayWidth - this.width) / 2;
                this.y = (displayHeight - this.height) / 2;
            }

            info.hwnd = CreateWindowExW(
                0,
                info.wc.lpszClassName,
                settings.title,
                WS_OVERLAPPEDWINDOW | WS_VISIBLE | WS_CLIPSIBLINGS | WS_CLIPCHILDREN,
                this.x, this.y,
                this.width, this.height,
                null,
                null,
                info.wc.hInstance,
                cast(void*)this
            );
            
            info.hdc = GetDC(info.hwnd);
        }
        else version(linux)
        {
            info.display = XOpenDisplay(null);
            if (info.display is null)
                return;
            
            info.screen = XDefaultScreenOfDisplay(info.display);
            info.root = XRootWindowOfScreen(info.screen);
            
            int screenNumber = 0; 
            displayWidth = XDisplayWidth(info.display, screenNumber);
            displayHeight = XDisplayHeight(info.display, screenNumber);
            
            if (settings.center)
            {
                this.x = (displayWidth - this.width) / 2;
                this.y = (displayHeight - this.height) / 2;
            }
            
            info.window = XCreateSimpleWindow(
                info.display, info.root,
                this.x, this.y,
                this.width, this.height,
                0, 0, 0);
            
            XSelectInput(info.display, info.window, StructureNotifyMask);
            
            event.wmProtocols = XInternAtom(info.display, "WM_PROTOCOLS", 0);
            event.wmDelete = XInternAtom(info.display, "WM_DELETE_WINDOW", 0);
            XSetWMProtocols(info.display, info.window, &event.wmDelete, 1);
            
            XSetWindowBackground(info.display, info.window, 0x000000);
            XClearWindow(info.display, info.window);
            XMapWindow(info.display, info.window);
            XFlush(info.display);
        }
        
        info.valid = true;
        this.running = true;
    }
    
    bool createGLContext(OpenGLVersion glVersion) nothrow @nogc
    {
        if (!info.valid)
            return false;
        
        GLDevice glDevice;
        version(Windows)
        {
            glDevice = GLDevice(info.hdc);
        }
        else version(linux)
        {
            glDevice = GLDevice(info.display, info.window);
        }
        auto context = loadOpenGL(glDevice, glVersion);
        if (isValidGLContext(context))
        {
            this.glVersion = glVersion;
            this.glContext = context;
            this.glPresent = true;
            return true;
        }
        else
        {
            this.glPresent = false;
            return false;
        }
    }
    
    protected void dispatch()
    {
        if (!running || !info.valid)
            return;
        
        version(Windows)
        {
            while(PeekMessage(&event.message, null, 0, 0, PM_REMOVE) != 0)
            {
                if (event.message.message == WM_QUIT)
                {
                    running = false;
                }
                
                TranslateMessage(&event.message);
                DispatchMessage(&event.message);
            }
        }
        else version(linux)
        {
            while(XPending(info.display) > 0)
            {
                XNextEvent(info.display, &event.xEvent);
                
                if (event.xEvent.type == ClientMessage &&
                    event.xEvent.xclient.messageType == event.wmProtocols &&
                    cast(ulong)event.xEvent.xclient.data[0] == event.wmDelete)
                {
                    running = false;
                }
                else if (event.xEvent.type == ConfigureNotify)
                {
                    XConfigureEvent xce = event.xEvent.xconfigure;
                    if (xce.width != width || xce.height != height)
                    {
                        width = cast(uint)xce.width;
                        height = cast(uint)xce.height;
                        onResize(width, height);
                    }
                }
            }
        }
    }
    
    protected void swapBuffers() nothrow @nogc
    {
        if (!glPresent)
            return;
        
        version(Windows)
        {
            SwapBuffers(info.hdc);
        }
        else version(linux)
        {
            eglSwapBuffers(glContext.display, glContext.surface);
        }
    }
    
    void run()
    {
        timer = getTimeStep();
        
        while(running)
        {
            dispatch();
            
            double timeStep = getTimeStep();
            timer += timeStep;
            if (timer >= timeStep)
            {
                timer -= timeStep;
                onUpdate(timeStep);
            }
        }
        
        onQuit();
        
        version(linux)
        {
            if (info.valid)
            {
                XDestroyWindow(info.display, info.window);
                XCloseDisplay(info.display);
            }
        }
    }
    
    void onUpdate(double dt) {}
    void onQuit() {}
    void onResize(uint width, uint height) {}
}

version(Windows)
{
    extern(Windows) LRESULT WndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
    {
        if (msg == WM_NCCREATE)
        {
            auto createStruct = cast(CREATESTRUCT*)lParam;
            SystemWindow window = cast(SystemWindow)createStruct.lpCreateParams;
            SetWindowLongPtr(hwnd, GWLP_USERDATA, cast(LONG_PTR)cast(void*)window);
            return TRUE;
        }
        
        SystemWindow window = cast(SystemWindow)cast(void*)GetWindowLongPtr(hwnd, GWLP_USERDATA);
        if (window is null)
            return DefWindowProc(hwnd, msg, wParam, lParam);
        
        switch(msg)
        {
            case WM_DESTROY:
                PostQuitMessage(0);
                return 0;
            case WM_SIZE:
                window.width = cast(uint)(lParam & 0xFFFF);
                window.height = cast(uint)(lParam >> 16);
                if (window.running)
                    window.onResize(window.width, window.height);
                return 0;
            default:
                break;
        }
        
        return DefWindowProc(hwnd, msg, wParam, lParam);
    }
}
