/*
Copyright (c) 2026 Timur Gafarov.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.time.timer;

version(Windows)
{
    import rtld.sys.windows;
}
version(Posix)
{
    import rtld.sys.posix.time;
}

private
{
    version(Windows)
    {
        __gshared LARGE_INTEGER t_freq;
        __gshared bool t_initialized = false;
    }
    version(Posix)
    {
        __gshared bool t_initialized = false;
    }
    
    __gshared double _lastTime = 0.0;
}

double getTime() @nogc nothrow
{
    version(Windows)
    {
        if (!t_initialized)
        {
            QueryPerformanceFrequency(&t_freq);
            t_initialized = true;
        }

        LARGE_INTEGER counter;
        QueryPerformanceCounter(&counter);

        return cast(double)counter.QuadPart /
               cast(double)t_freq.QuadPart;
    }
    else version(Posix)
    {
        timespec ts;
        clock_gettime(CLOCK_MONOTONIC, &ts);

        return cast(double)ts.tv_sec +
               cast(double)ts.tv_nsec / 1_000_000_000.0;
    }
    else
    {
        return 0.0;
    }
}

double getTimeStep() @nogc nothrow
{
    double currentTime = getTime();

    if (_lastTime == 0.0)
    {
        _lastTime = currentTime;
        return 0.0;
    }

    double dt = currentTime - _lastTime;
    _lastTime = currentTime;

    return dt;
}

struct Stopwatch
{
   private:
    double _startTime = 0.0;
    double _elapsedTime = 0.0;
    bool _running = false;

   public:
    void start() @nogc nothrow
    {
        if (!_running)
        {
            _startTime = getTime();
            _running = true;
        }
    }

    void stop() @nogc nothrow
    {
        if (_running)
        {
            _elapsedTime += getTime() - _startTime;
            _running = false;
        }
    }

    void reset() @nogc nothrow
    {
        _startTime = 0.0;
        _elapsedTime = 0.0;
        _running = false;
    }

    double elapsed() const @nogc nothrow
    {
        if (_running)
            return _elapsedTime + (getTime() - _startTime);

        return _elapsedTime;
    }

    bool running() const @nogc nothrow
    {
        return _running;
    }
}

private
{
    enum double _NANOSECONDS = 1000_000_000.0;
    enum double _MICROSECONDS = 1000_000.0;
    enum double _MILLISECONDS = 1000.0;
    enum double _INV_MINUTE = 1.0 / 60.0;
    enum double _INV_HOUR = 1.0 / 3600.0;
    enum double _INV_DAY = 1.0 / 86400.0;
}

pragma(inline, true)
double nanoseconds(double s) pure @nogc nothrow
{
    return s * _NANOSECONDS;
}

pragma(inline, true)
double microseconds(double s) pure @nogc nothrow
{
    return s * _MICROSECONDS;
}

pragma(inline, true)
double milliseconds(double s) pure @nogc nothrow
{
    return s * _MILLISECONDS;
}

pragma(inline, true)
double seconds(double s) pure @nogc nothrow
{
    return s;
}

pragma(inline, true)
double minutes(double s) pure @nogc nothrow
{
    return s * _INV_MINUTE;
}

pragma(inline, true)
double hours(double s) pure @nogc nothrow
{
    return s * _INV_HOUR;
}

pragma(inline, true)
double days(double s) pure @nogc nothrow
{
    return s * _INV_DAY;
}
