/*
Copyright (c) 2025-2026 Timur Gafarov.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.time.timer;

version(Windows)
{
    import rtld.sys.windows;
}
version(Posix)
{
    import rtld.sys.posix.time;
}

private
{
    version(Windows)
    {
        __gshared LARGE_INTEGER t_freq;
        __gshared LARGE_INTEGER t_last;
        __gshared bool t_initialized = false;
    }
    version(Posix)
    {
        __gshared timespec t_last;
        __gshared bool t_initialized = false;
    }
}

double getTimeStep() @nogc nothrow
{
    version(Windows)
    {
        if (!t_initialized)
        {
            // First call
            QueryPerformanceFrequency(&t_freq);
            QueryPerformanceCounter(&t_last);
            t_initialized = true;
            return 0.0;
        }

        LARGE_INTEGER counter;
        QueryPerformanceCounter(&counter);

        double dt = cast(double)(counter.QuadPart - t_last.QuadPart) / cast(double)(t_freq.QuadPart);
        t_last = counter;
        return dt;
    }
    else version(Posix)
    {
        if (!t_initialized)
        {
            // First call
            clock_gettime(CLOCK_MONOTONIC, &t_last);
            t_initialized = true;
            return 0.0;
        }

        timespec counter;
        clock_gettime(CLOCK_MONOTONIC, &counter);

        double dt = cast(double)(counter.tv_sec - t_last.tv_sec) + 
                    cast(double)(counter.tv_nsec - t_last.tv_nsec) / 1_000_000_000.0;
        t_last = counter;
        return dt;
    }
    else
    {
        // Not implemented
        return 0.0;
    }
}
