/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.sys.linux.x11;

version(linux):

import rtld.core.linker;

struct Display;
struct Screen;

alias XID = ulong;
alias Window = XID;
alias Atom = XID;

enum ClientMessage = 33;

alias Bool = int;

struct XClientMessageEvent
{
    int type;
    ulong serial;
    Bool sendEvent;
    Display* display;
    Window window;
    Atom messageType;
    int format;
    long[5] data;
}

struct XConfigureEvent
{
    int type;
    ulong serial;
    bool send_event;
    Display* display;
    Window event;
    Window window;
    int x, y;
    int width, height;
    int border_width;
    Window above;
    bool override_redirect;
}

union XEvent
{
    int type;
    XConfigureEvent xconfigure;
    XClientMessageEvent xclient;
    long[24] pad;
}

enum StructureNotifyMask = 1 << 17;
enum ConfigureNotify = 22;

extern(C) nothrow @nogc
{
    alias f_XOpenDisplay = Display* function(const(char)*);
    alias f_XCloseDisplay = int function(Display*);
    alias f_XCreateSimpleWindow = Window function(
        Display*,
        Window,
        int, int,
        uint, uint,
        uint,
        ulong,
        ulong);
    alias f_XMapWindow = int function(Display*, Window);
    alias f_XDestroyWindow = int function(Display*, Window);
    alias f_XPending = int function(Display*);
    alias f_XNextEvent = int function(Display*, XEvent*);
    alias f_XSelectInput = int function(Display*, Window, long);
    alias f_XDefaultScreenOfDisplay = Screen* function(Display*);
    alias f_XRootWindowOfScreen = Window function(Screen*);
    alias f_XFlush = int function(Display*);
    alias f_XInternAtom = ulong function(Display*, const(char)*, int);
    alias f_XSetWMProtocols = int function(Display*, Window, ulong*, int);
    alias f_XClearWindow = int function(Display*, Window);
    alias f_XSetWindowBackground = int function(Display*, Window, ulong);
}

__gshared
{
    f_XOpenDisplay XOpenDisplay;
    f_XCloseDisplay XCloseDisplay;
    f_XCreateSimpleWindow XCreateSimpleWindow;
    f_XMapWindow XMapWindow;
    f_XDestroyWindow XDestroyWindow;
    f_XPending XPending;
    f_XNextEvent XNextEvent;
    f_XSelectInput XSelectInput;
    f_XDefaultScreenOfDisplay XDefaultScreenOfDisplay;
    f_XRootWindowOfScreen XRootWindowOfScreen;
    f_XFlush XFlush;
    f_XInternAtom XInternAtom;
    f_XSetWMProtocols XSetWMProtocols;
    f_XClearWindow XClearWindow;
    f_XSetWindowBackground XSetWindowBackground;
}

void init() nothrow @nogc
{
    auto libX11 = openLibrary("libX11.so.6");
    XOpenDisplay = cast(f_XOpenDisplay)getFunctionPointer(libX11, "XOpenDisplay");
    XCloseDisplay = cast(f_XCloseDisplay)getFunctionPointer(libX11, "XCloseDisplay");
    XCreateSimpleWindow = cast(f_XCreateSimpleWindow)getFunctionPointer(libX11, "XCreateSimpleWindow");
    XMapWindow = cast(f_XMapWindow)getFunctionPointer(libX11, "XMapWindow");
    XDestroyWindow = cast(f_XDestroyWindow)getFunctionPointer(libX11, "XDestroyWindow");
    XPending = cast(f_XPending)getFunctionPointer(libX11, "XPending");
    XNextEvent = cast(f_XNextEvent)getFunctionPointer(libX11, "XNextEvent");
    XSelectInput = cast(f_XSelectInput)getFunctionPointer(libX11, "XSelectInput");
    XDefaultScreenOfDisplay = cast(f_XDefaultScreenOfDisplay)getFunctionPointer(libX11, "XDefaultScreenOfDisplay");
    XRootWindowOfScreen = cast(f_XRootWindowOfScreen)getFunctionPointer(libX11, "XRootWindowOfScreen");
    XFlush = cast(f_XFlush)getFunctionPointer(libX11, "XFlush");
    XInternAtom = cast(f_XInternAtom)getFunctionPointer(libX11, "XInternAtom");
    XSetWMProtocols = cast(f_XSetWMProtocols)getFunctionPointer(libX11, "XSetWMProtocols");
    XClearWindow = cast(f_XClearWindow)getFunctionPointer(libX11, "XClearWindow");
    XSetWindowBackground = cast(f_XSetWindowBackground)getFunctionPointer(libX11, "XSetWindowBackground");
}
