/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.math.angles;

import rtld.core.traits;
import rtld.math.base;

/**
 * Convert degrees to radians
 */
pragma(inline, true)
T degtorad(T) (T angle) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return (angle / 180.0) * PI;
}

/**
 * Convert radians to degrees
 */
pragma(inline, true)
T radtodeg(T) (T angle) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return (angle / PI) * 180.0;
}

/**
 * Convert radians to revolutions
 */
pragma(inline, true)
T radtorev(T)(T angle) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return angle / (2.0 * PI);
}

/**
 * Convert revolutions to radians
 */
pragma(inline, true)
T revtorad(T)(angle) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return angle * (2.0 * PI);
}


/**
 * Field of view angle Y from X
 */
pragma(inline, true)
T fovYfromX(T) (T xfov, T aspectRatio) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    xfov = degtorad(xfov);
    T yfov = 2.0 * atan(tan(xfov * 0.5) / aspectRatio);
    return radtodeg(yfov);
}

/**
 * Field of view angle X from Y
 */
pragma(inline, true)
T fovXfromY(T) (T yfov, T aspectRatio) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    yfov = degtorad(yfov);
    T xfov = 2.0 * atan(tan(yfov * 0.5) * aspectRatio);
    return radtodeg(xfov);
}

/** 
 * Wraps an arbitrary angle to [-180, +180] degrees range.
 * Input angle units depend on the provided period
 * (360 for degrees, 2.0 * PI for radians).
 *
 * Params:
 *   angle = input angle.
 *   period = full circle measure.
 * Returns:
 *   Wrapped angle.
 */
pragma(inline, true)
T wrapAngle(T)(T angle, T period = 360.0) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return angle - period * floor((angle + period * 0.5) / period);
}

///
unittest
{
    assert((wrapAngle(270.0f) + 90.0f) <= EPSILON);
}

/**
 * Returns shortest angular distance between two angles (in radians).
 */
T shortestAngleDelta(T)(T angleFrom, T angleTo) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    float delta = angleTo - angleFrom;
    while (delta > PI)  delta -= 2.0 * PI;
    while (delta < -PI) delta += 2.0 * PI;
    return delta;
}

///
unittest
{
    float d = shortestAngleDelta(degtorad(45.0f), degtorad(315.0f));
    assert((d - degtorad(90.0f)) <= EPSILON);
}
