/*
Copyright (c) 2019-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Optimized elementary mathematical functions.
 *
 * Description:
 * This is a direct replacement for std.math that implicitly choses between
 * LLVM intrinsics, libc functions and fallback implementations depending
 * on the compilation target.
 *
 * Copyright: Timur Gafarov 2019-2026.
 * License: $(LINK2 boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module rtld.math.base;

version(FreeStanding)
{
    version = UseFreeStandingMath;
}

version(UseFreeStandingMath)
{
    version(X86)
    {
        version = UseX87Math;
    }
    version(X86_64)
    {
        version = UseX87Math;
    }
}

public import rtld.math.constants;

version(LDC)
{
    import ldc.intrinsics;
}

import rtld.math.fallback;

version(LDC)
{
    // Inverse square root via LLVM intrinsic.
    pragma(inline, true)
    float rsqrt(float number) pure nothrow @nogc
    {
        return 1.0f / llvm_sqrt(number);
    }
}
else
{
    // John Carmack's fast inverse square root, just for fun (a bit faster than 1/sqrt of std.math).
    pragma(inline, true)
    float rsqrt(float number) pure nothrow @nogc
    {
        uint i;
        const float threehalfs = 1.5f;
        float x2 = number * 0.5f;
        float y  = number;
        i  = *cast(uint*)&y;                  // evil floating point bit level hacking
        i  = 0x5f3759df - (i >> 1);           // what the fuck?
        y  = *cast(float*)&i;
        y  = y * (threehalfs - (x2 * y * y)); // 1st iteration
    //  y  = y * (threehalfs - (x2 * y * y)); // 2nd iteration, this can be removed
        return y;
    }
}

/// Cotangent.
pragma(inline, true)
T cot(T)(T x) pure nothrow @nogc
{
    return cos(x) / sin(x);
}

version(UseFreeStandingMath)
{
    // Fallback (bare metal) implementations
    
    alias abs   = absFallback;
    alias fabs  = fabsFallback;
    alias sqrt = sqrtFallback;
    alias sin = sinFallback;
    alias cos = cosFallback;
    alias tan = tanFallback;
    alias ceil  = ceilFallback;
    alias floor = floorFallback;
    alias round = roundFallback;
    alias trunc = truncFallback;
    // TODO: rint
    // TODO: nearbyint
    alias pow = powFallback;
    alias exp = expFallback;
    alias exp2 = exp2Fallback;
    alias log = logFallback;
    alias log2 = log2Fallback;
    alias log10 = log10Fallback;
    alias fmax = fmaxFallback;
    alias fmin = fminFallback;
    // TODO: fma
    // TODO: copysign
}
else version(LDC)
{
    // A subset of elementary functions that can be LLVM intrinsics
    
    // Tangent via LLVM intrinsics.
    pragma(inline, true)
    T llvm_tan(T)(T x) pure nothrow @nogc
    {
        return llvm_sin(x) / llvm_cos(x);
    }
    
    alias abs   = absFallback;
    alias fabs  = llvm_fabs;
    alias sqrt  = llvm_sqrt;
    alias sin   = llvm_sin;
    alias cos   = llvm_cos;
    alias tan   = llvm_tan;
    alias ceil  = llvm_ceil;
    alias floor = llvm_floor;
    alias round = llvm_round;
    alias trunc = llvm_trunc;
    alias rint  = llvm_rint;
    alias nearbyint = llvm_nearbyint;
    alias pow   = llvm_pow;
    alias exp   = llvm_exp;
    alias exp2  = llvm_exp2;
    alias log   = llvm_log;
    alias log2  = llvm_log2;
    alias log10 = llvm_log10;
    alias fmax  = llvm_maxnum;
    alias fmin  = llvm_minnum;
    alias fma   = llvm_fma;
    alias copysign = llvm_copysign;
}
else
{
    // Use libc
    
    alias abs   = absFallback;
    alias fabs  = fabsFallback;
    
    extern(C) pure nothrow @nogc
    {
        double sqrt(double x);
        double sin(double x);
        double cos(double x);
        double tan(double x);
        double ceil(double x);
        double floor(double x);
        double round(double x);
        double trunc(double x);
        double rint(double x);
        double nearbyint(double arg);
        double pow(double x, double y);
        double exp(double x);
        double exp2(double x);
        double log(double x);
        double log2(double x);
        double log10(double x);
        double fmax(double x, double y);
        double fmin(double x, double y);
        double fma(double x, double y, double z);
        double copysign(double x, double y);
    }
}

version(UseFreeStandingMath)
{
    // Fallback (bare metal) implementations
    
    alias cbrt = cbrtFallback;
    alias asin = asinFallback;
    alias acos = acosFallback;
    alias atan = atanFallback;
    alias atan2 = atan2Fallback;
    alias hypot = hypotFallback;
    // TODO: modf
    alias sinh = sinhFallback;
    alias cosh = coshFallback;
    alias tanh = tanhFallback;
    alias asinh = asinhFallback;
    alias acosh = acoshFallback;
    alias atanh = atanhFallback;
}
else
{
    // Use libc
    
    extern(C) nothrow @nogc
    {
        double cbrt(double x);
        double asin(double x);
        double acos(double x);
        double atan(double x);
        double atan2(double y, double x);
        double hypot(double x, double y);
        double modf(double x, double* intptr);
        double sinh(double x);
        double cosh(double x);
        double tanh(double x);
        double asinh(double x);
        double acosh(double x);
        double atanh(double x);
    }
}

/*
  TODO:
  - poly
  - nextPow2
  - truncPow2
  - lround
  - lrint
  - rndtol
  - quantize
  - powmod
  - expm1
  - ldexp
  - frexp
  - logb
  - ilogb
  - log1p
  - scalbn
  - fmod
  - remainder
  - approxEqual
  - feqrel
  - fdim
  - isClose
  - nextDown
  - nextUp
  - nextafter
  - NaN
  - getNaNPayload
  - cmp
  - isFinite
  - isIdentical
  - isNormal
  - isSubnormal
  - signbit
  - sgn
  - isPowerOf2
  - IeeeFlags
  - ieeeFlags
  - resetIeeeFlags
  - FloatingPointControl
*/
