/*
Copyright (c) 2019-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Optimized elementary mathematical functions.
 *
 * Description:
 * This is a direct replacement for std.math that implicitly choses between
 * LLVM intrinsics, libc functions and fallback implementations depending
 * on the compilation target.
 *
 * Copyright: Timur Gafarov 2019-2026.
 * License: $(LINK2 boost.org/LICENSE_1_0.txt, Boost License 1.0).
 * Authors: Timur Gafarov
 */
module rtld.math.base;

version(FreeStanding)
    version = UseFreeStandingMath;

version(LDC)
    import ldc.intrinsics;

version(Phobos)
    import std.math;
else
    public import rtld.math.constants;

import rtld.math.fallback;

version(LDC)
{
    // Inverse square root via LLVM intrinsic.
    pragma(inline, true)
    float rsqrt(float number) pure nothrow @nogc
    {
        return 1.0f / llvm_sqrt(number);
    }
}
else
{
    // John Carmack's fast inverse square root, just for fun (a bit faster than 1/sqrt of std.math).
    pragma(inline, true)
    float rsqrt(float number) pure nothrow @nogc
    {
        uint i;
        const float threehalfs = 1.5f;
        float x2 = number * 0.5f;
        float y  = number;
        i  = *cast(uint*)&y;                  // evil floating point bit level hacking
        i  = 0x5f3759df - (i >> 1);           // what the fuck?
        y  = *cast(float*)&i;
        y  = y * (threehalfs - (x2 * y * y)); // 1st iteration
    //  y  = y * (threehalfs - (x2 * y * y)); // 2nd iteration, this can be removed
        return y;
    }
}

/// Cotangent.
pragma(inline, true)
T cot(T)(T x) pure nothrow @nogc
{
    return cos(x) / sin(x);
}

version(UseFreeStandingMath)
{
    // Fallback (bare metal) implementations
    
    alias abs   = absFallback;
    alias fabs  = fabsFallback;
    alias sqrt = sqrtFallback;
    alias sin = sinFallback;
    alias cos = cosFallback;
    alias tan = tanFallback;
    alias ceil  = ceilFallback;
    alias floor = floorFallback;
    alias round = roundFallback;
    alias trunc = truncFallback;
    alias rint = rintFallback;
    alias nearbyint = nearbyintFallback;
    alias pow = powFallback;
    alias exp = expFallback;
    alias exp2 = exp2Fallback;
    alias log = logFallback;
    alias log2 = log2Fallback;
    alias log10 = log10Fallback;
    alias fmax = fmaxFallback;
    alias fmin = fminFallback;
    alias fma = fmaFallback;
    alias copysign = copysignFallback;
}
else version(LDC)
{
    // A subset of elementary functions that can be LLVM intrinsics
    
    // Tangent via LLVM intrinsics.
    pragma(inline, true)
    T llvm_tan(T)(T x) pure nothrow @nogc
    {
        return llvm_sin(x) / llvm_cos(x);
    }
    
    alias abs       = absFallback;
    alias fabs      = llvm_fabs;
    alias sqrt      = llvm_sqrt;
    alias sin       = llvm_sin;
    alias cos       = llvm_cos;
    alias tan       = llvm_tan;
    alias ceil      = llvm_ceil;
    alias floor     = llvm_floor;
    alias round     = llvm_round;
    alias trunc     = llvm_trunc;
    alias rint      = llvm_rint;
    alias nearbyint = llvm_nearbyint;
    alias pow       = llvm_pow;
    alias exp       = llvm_exp;
    alias exp2      = llvm_exp2;
    alias log       = llvm_log;
    alias log2      = llvm_log2;
    alias log10     = llvm_log10;
    alias fmax      = llvm_maxnum;
    alias fmin      = llvm_minnum;
    alias fma       = llvm_fma;
    alias copysign  = llvm_copysign;
}
else version(Phobos)
{
    // Use std.math functions
    
    alias abs = std.math.abs;
    alias fabs = std.math.fabs;
    alias sqrt = std.math.sqrt;
    alias sin = std.math.sin;
    alias cos = std.math.cos;
    alias tan = std.math.tan;
    alias ceil = std.math.ceil;
    alias floor = std.math.floor;
    alias round = std.math.round;
    alias trunc = std.math.trunc;
    alias rint = std.math.rint;
    alias nearbyint = std.math.nearbyint;
    alias pow = std.math.pow;
    alias exp = std.math.exp;
    alias exp2 = std.math.exp2;
    alias log = std.math.log;
    alias log2 = std.math.log2;
    alias log10 = std.math.log10;
    alias fmax = std.math.fmax;
    alias fmin = std.math.fmin;
    alias fma = std.math.fma;
    alias copysign = std.math.copysign;
}
else
{
    // Use libc
    
    alias abs   = absFallback;
    alias fabs  = fabsFallback;
    
    extern(C) pure nothrow @nogc
    {
        double sqrt(double x);
        double sin(double x);
        double cos(double x);
        double tan(double x);
        double ceil(double x);
        double floor(double x);
        double round(double x);
        double trunc(double x);
        double rint(double x);
        double nearbyint(double arg);
        double pow(double x, double y);
        double exp(double x);
        double exp2(double x);
        double log(double x);
        double log2(double x);
        double log10(double x);
        double fmax(double x, double y);
        double fmin(double x, double y);
        double fma(double x, double y, double z);
        double copysign(double x, double y);
    }
}

version(UseFreeStandingMath)
{
    // Fallback (bare metal) implementations
    
    alias cbrt = cbrtFallback;
    alias asin = asinFallback;
    alias acos = acosFallback;
    alias atan = atanFallback;
    alias atan2 = atan2Fallback;
    alias hypot = hypotFallback;
    // TODO: modf
    alias sinh = sinhFallback;
    alias cosh = coshFallback;
    alias tanh = tanhFallback;
    alias asinh = asinhFallback;
    alias acosh = acoshFallback;
    alias atanh = atanhFallback;
}
version(Phobos)
{
    // Use std.math functions
    
    alias cbrt = std.math.cbrt;
    alias asin = std.math.asin;
    alias acos = std.math.acos;
    alias atan = std.math.atan;
    alias atan2 = std.math.atan2;
    alias hypot = std.math.hypot;
    alias sinh = std.math.sinh;
    alias cosh = std.math.cosh;
    alias tanh = std.math.tanh;
    alias asinh = std.math.asinh;
    alias acosh = std.math.acosh;
    alias atanh = std.math.atanh;
}
else
{
    // Use libc functions
    
    extern(C) nothrow @nogc
    {
        double cbrt(double x);
        double asin(double x);
        double acos(double x);
        double atan(double x);
        double atan2(double y, double x);
        double hypot(double x, double y);
        double modf(double x, double* intptr);
        double sinh(double x);
        double cosh(double x);
        double tanh(double x);
        double asinh(double x);
        double acosh(double x);
        double atanh(double x);
    }
}

version(Phobos)
{
    // Additional std.math functions
    
    alias poly        = std.math.poly;
    alias nextPow2    = std.math.nextPow2;
    alias truncPow2   = std.math.truncPow2;
    alias lround      = std.math.lround;
    alias lrint       = std.math.lrint;
    alias rndtol      = std.math.rndtol;
    alias quantize    = std.math.quantize;
    alias powmod      = std.math.powmod;
    alias expm1       = std.math.expm1;
    alias ldexp       = std.math.ldexp;
    alias frexp       = std.math.frexp;
    alias logb        = std.math.logb;
    alias ilogb       = std.math.ilogb;
    alias log1p       = std.math.log1p;
    alias scalbn      = std.math.scalbn;
    alias fmod        = std.math.fmod;
    alias remainder   = std.math.remainder;
    alias approxEqual = std.math.approxEqual;
    alias feqrel      = std.math.feqrel;
    alias fdim        = std.math.fdim;
    alias isClose     = std.math.isClose;
    alias nextDown    = std.math.nextDown;
    alias nextUp      = std.math.nextUp;
    alias nextafter   = std.math.nextafter;
    alias NaN         = std.math.NaN;
    alias getNaNPayload = std.math.getNaNPayload;
    alias cmp         = std.math.cmp;
    alias isFinite    = std.math.isFinite;
    alias isIdentical = std.math.isIdentical;
    alias isNormal    = std.math.isNormal;
    alias isSubnormal = std.math.isSubnormal;
    alias signbit     = std.math.signbit;
    alias sgn         = std.math.sgn;
    alias isPowerOf2  = std.math.isPowerOf2;
    alias IeeeFlags   = std.math.IeeeFlags;
    alias ieeeFlags   = std.math.ieeeFlags;
    alias resetIeeeFlags = std.math.resetIeeeFlags;
    alias FloatingPointControl = std.math.FloatingPointControl;
}
else
{
    alias expm1       = expm1Fallback;
    alias log1p       = log1pFallback;
    alias signbit     = signbitFallback;
    
    // TODO
}
