/*
Copyright (c) 2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module rtld.math.constants;

/**
 * Very small value
 */
enum EPSILON = 0.000001;

/*
 * Basic math constants
 */
enum double E           = 2.7182818284590452;
enum double PI          = 3.1415926535897932;
enum double HALFPI      = 1.5707963267948966; // PI/2
enum double QUARTPI     = 0.7853981633974483; // PI/4
enum double INVPI       = 0.3183098861837907; // 1/PI
enum double INVTWOPI    = 0.1591549430918953; // 1/2PI
enum double TWOPI       = 6.2831853071795865; // 2PI
enum double THREEHALFPI = 4.7123889803846899; // 3PI/2
enum double LN10        = 2.3025850929940457; // ln(10)
enum double LN2         = 0.6931471805599453; // ln(2)
enum double INVLN2      = 1.4426950408889634; // 1/ln(2)
enum double LOG2        = 0.3010299956639812; // log10(2)
enum double LOG2E       = 1.4426950408889634; // log2(e)
enum double LOG10E      = 0.4342944819032518; // log10(E)
enum double LOG2T       = 3.3219280948873623; // log2(10)
enum double SQRT2       = 1.4142135623730951; // sqrt(2)
enum double SQRT1_2     = 0.7071067811865476; // sqrt(1/2)

// std.math compatibility
alias PI_2 = HALFPI;
alias PI_4 = QUARTPI;
alias M_1_PI = INVPI;
enum double M_2_PI      = 0.6366197723675813; // 2/PI
enum double M_2_SQRTPI  = 1.1283791670955125; // 2/sqrt(PI)
