/*
Copyright (c) 2019-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Fallback math functions.
 *
 * Description:
 * Provides platform-independent fallbacks for the following elementary functions:
 * - abs, fabs
 * - trunc, floor, ceil, round, fmod
 * - sqrt, cbrt
 * - sin, cos, tan
 * - asin, acos, atan, atan2
 * - exp, exp2, log, log2, log10, pow
 * - hypot, modf,
 * - sinh, cosh, tanh
 * - asinh, acosh, atanh
 * - rint, nearbyint
 * - fma
 * - signbit, copysign
 */
module rtld.math.fallback;

import rtld.core.traits;
import rtld.math.constants;
import rtld.math.utils;

pragma(inline, true)
T absFallback(T)(T v) pure nothrow @nogc
{
    return (v > 0.0)? v : -v;
}

alias fabsFallback = absFallback;

alias fmaxFallback = max2;
alias fminFallback = min2;

///////////////////////////////////////

version(FreeStanding)
    version = UseFreeStandingMath;
else version(unittest)
    version = UseFreeStandingMath;

version(UseFreeStandingMath):

version(X86)
    version = UseX87Math;
version(X86_64)
    version = UseX87Math;

import rtld.math.trigtables;

pragma(inline, true)
T truncFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return cast(long)x;
}

pragma(inline, true)
T floorFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    long intPart = cast(long)x;
    return (x < 0 && x != cast(T)intPart) ? intPart - 1 : intPart;
}

pragma(inline, true)
T ceilFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    long intPart = cast(long)x;
    T xtrunc = (x < 0 && x != cast(T)intPart) ? intPart - 1 : intPart;
    return (xtrunc < x)? xtrunc + 1 : x;
}

pragma(inline, true)
T roundFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x < 0.0)
        return cast(long)(x - 0.5);
    else
        return cast(long)(x + 0.5);
}

T sqrtFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    version(UseX87Math)
    {
        T result;
        
        if (is(T == float))
        {
            asm pure nothrow @nogc
            {
                fld dword ptr x;
                fsqrt;
                fstp dword ptr result;
            }
        }
        else
        {
            asm pure nothrow @nogc
            {
                fld qword ptr x;
                fsqrt;
                fstp qword ptr result;
            }
        }
        
        return result;
    }
    else
    {
        double z = cast(double)(x > 1.0) ? x * 0.5 : x + 1.0;
        for (uint i = 1; i <= 10; i++)
        {
            z -= (z * z - x) / (2.0 * z);
        }
        return cast(T)z;
    }
}

T cbrtFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum OneOverThree = 1.0 / 3.0;
    if (x < 0) return -cbrt(-x);
    if (isNaN(x) || isInfinity(x)) return x;
    if (x == 0) return 0;
    T a = sqrtFallback(x);
    T b = T.infinity;
    while (a < b)
    {
        b = a;
        a = (2.0 * a + (x / (b * b))) * OneOverThree;
    }
    return a;
}

T sinFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    T xfmod = x - floorFallback(x * INVTWOPI) * TWOPI;
    x = (0 > xfmod)? 0 : xfmod;
    
    T rsign = 1.0;
    T adjusted_x = x;
    if (x < 0) 
    {
        adjusted_x = -x;
        rsign = -1.0;
    }
    if (adjusted_x > PI) 
    {
        adjusted_x = min2(PI, TWOPI - adjusted_x);
        rsign = -1.0;
    }
    
    T j = adjusted_x * (cast(T)(sinTable.length - 2) * INVPI);
    int zero = cast(int)j;
    T nx = j - zero;
    return ((1.0 - nx) * sinTable[zero][0] + nx * sinTable[zero + 1][0]) * rsign;
}

T cosFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    T xfmod = x - floorFallback(x * INVTWOPI) * TWOPI;
    x = (0 > xfmod)? 0 : xfmod;
    
    T adjusted_x = x;
    if (x < 0) 
    {
        adjusted_x = -x;
    }
    if (adjusted_x > PI) 
    {
        adjusted_x = min2(PI, TWOPI - adjusted_x);
    }
     
    T j = adjusted_x * (cast(T)(cosTable.length - 2) * INVPI);
    int zero = cast(int)j;
    T nx = j - zero;
    return (1.0 - nx) * cosTable[zero][0] + nx * cosTable[zero + 1][0];
}

pragma(inline, true)
T tanFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return sinFallback(x) / cosFallback(x);
}

pragma(inline, true)
T asinFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return atan2Fallback(x, sqrt(1.0 - x * x));
}

pragma(inline, true)
T acosFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return atan2Fallback(sqrt(1.0 - x * x), x);
}

T atanFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    // Implementation from Algol 60
    const T        R1 =  0x1.9310cfe85307cp+3;
    const T        R2 = -0x1.58beca04f1805p+6;
    const T        R3 = -0x1.46d547fed8a3dp+0;
    const T        R4 = -0x1.57bd961f06c89p-4;
    const T        S1 =  0x1.b189e39236635p+4;
    const T        S2 =  0x1.a3b86f7830dc0p+2;
    const T        S3 =  0x1.1273f9e5eff20p+1;
    const T        S4 =  0x1.44831dafbf542p+0;
    const T       RT3 =  0x1.bb67ae8584caap+0;
    const T     PIBY6 =  0x1.0c152382d7365p-1;
    const T   PIBY2M1 =  0x1.243f6a8885a30p-1;
    const T     RT3M1 =  0x1.76cf5d0b09955p-1;
    const T TANPIBY12 =  0x1.126145e9ecd56p-2;
    const T       ONE =  0x1.0000000000000p+0;

    double XX1, XSQ, CONSTANT = 0.0;
    int SIGN = 0, INV = 0;

    if (x < 0) { SIGN = 1; XX1 = -x; } else XX1 = x;
    if (XX1 > ONE) { XX1 = 1.0 / XX1; INV = 1; }
    if (XX1 > TANPIBY12) { XX1 = (RT3M1 * XX1 - 1.0 + XX1) / (XX1 + RT3); CONSTANT = PIBY6; }

    XSQ = XX1 * XX1;
    XX1 = XX1 * (R1 / (XSQ + S1 + R2 / (XSQ + S2 + R3 / (XSQ + S3 + R4 / (XSQ + S4)))));
    XX1 = XX1 + CONSTANT;

    if (INV) XX1 = 1.0 - XX1 + PIBY2M1;
    if (SIGN) XX1 = -XX1;
     
    return XX1;
}

T atan2Fallback(T)(T y, T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x > 0)
        return atan(y / x);
    else if (x < 0 && y >= 0)
        return atan(y / x) + PI;
    else if (x < 0 && y < 0)
        return atan(y / x) - PI;
    else if (x == 0 && y > 0)
        return HALFPI;
    else if (x == 0 && y < 0)
        return -HALFPI;
    else
        return 0; // Undefined
}

// exp: range reduction + Taylor on reduced interval
T expFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (isNaN(x)) return x;
    if (isInfinity(x))
        return (x > 0) ? T.infinity : 0;

    // Range reduction: x = n*ln2 + r, |r| <= ln2/2
    int n = cast(int)floorFallback(x * INVLN2 + 0.5);
    T r = x - cast(T)(n) * cast(T)LN2;

    // Taylor series for e^r, enough terms for reasonable precision
    T term = 1.0;
    T sum = 1.0;
    for (int k = 1; k <= 14; ++k)
    {
        term *= r / k;
        sum += term;
    }

    // Multiply by 2^n via repeated doubling/halving (safe-ish)
    if (n > 0)
    {
        while (n >= 30)
        {
            sum *= cast(T)(1UL << 30);
            n -= 30;
        }
        if (n > 0) sum *= cast(T)(1UL << n);
    }
    else if (n < 0)
    {
        int m = -n;
        while (m >= 30)
        {
            sum *= cast(T)(1.0) / cast(T)(1UL << 30);
            m -= 30;
        }
        if (m > 0)
            sum *= cast(T)(1.0) / cast(T)(1UL << m);
    }

    return sum;
}

// exp2: 2^x = e^(x ln2)
pragma(inline, true)
T exp2Fallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return expFallback(x * cast(T)LN2);
}

T logFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x <= 0) return T.nan;
    if (isInfinity(x)) return T.infinity;
    if (x == 1) return 0;

    // Use range reduction via the identity log(x) = log(a * 2^n) = log(a) + n*log(2)
    // where 0.5 <= a < 1
    int n = 0;
    T a = x;

    // Scale a to [0.5, 1) range
    while (a >= 2) { a *= 0.5; n++; }
    while (a < 0.5) { a *= 2; n--; }

    // Use series expansion for log(1+y) where y = a-1
    // log(1+y) = y - y^2/2 + y^3/3 - y^4/4 + ...
    T y = a - 1;
    T y2 = y * y;
    T sum = y;
    T term = y;

    // Add terms until contribution becomes negligible
    for (int i = 2; i <= 12; i++)
    {
        term *= -y * (i - 1) / i;
        sum += term;
    }

    return sum + cast(T)LN2 * n;
}

pragma(inline, true)
T log2Fallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return logFallback(x) * cast(T)INVLN2;
}

pragma(inline, true)
T log10Fallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return logFallback(x) * cast(T)LOG10E;
}

// x^n for finite x > 0 and integer n >= 1, by square-and-multiply.
// Pure FP arithmetic (no casts to integers), exact while n < 2^mant_dig.
private T powSmallInt(T)(T x, T n) pure nothrow @nogc
{
    T r = 1;
    while (n >= 1)
    {
        T h = floorFallback(n * 0.5);
        if (n != h * 2)
            r *= x;
        x *= x; // may overflow/underflow, which is harmless here
        n = h;
    }
    return r;
}

T powFallback(T)(T x, T y) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    // Evaluate in double for the extra precision
    static if (is(T == float))
        alias FT = double;
    else
        alias FT = T;
    
    enum FT inf = FT.infinity;
    enum FT LN2 = 0.693147180559945309417232121458176568L;

    // --- IEEE 754 / C99 special cases --------------------------------
    if (y == 0 || x == 1) return 1; // even if the other one is NaN
    if (x != x || y != y) return T.nan;

    FT ax = fabsFallback(x);
    FT ay = fabsFallback(y);
    bool yInt = floorFallback(y) == y; // also true for +-inf
    bool yOdd = isOddInteger(y);

    if (ay == inf)
    {
        if (ax == 1) return 1; // pow(-1, +-inf)
        return ((ax < 1) == (y > 0)) ? cast(FT)0 : inf;
    }
    if (ax == inf)
    {
        bool negOdd = x < 0 && yOdd;
        if (y > 0) return negOdd ? -inf : inf;
        return negOdd ? copysignFallback(cast(FT)0, cast(FT) -1) : cast(FT)0;
    }
    if (x == 0) // +-0 base
    {
        if (y < 0) return yOdd ? copysignFallback(inf, x) : inf;
        return yOdd ? x : cast(FT)0; // keeps the sign of the zero
    }
    if (x < 0 && !yInt)
        return T.nan;

    // magnitude: |x| ^ y
    FT r = 0;
    bool done = false;

    // Small integer exponents: square-and-multiply is exact whenever the result is.
    if (yInt && ay <= 64)
    {
        r = powSmallInt(ax, ay);
        if (y < 0) r = 1 / r;
        done = (r != 0 && r != inf);   // on overflow/underflow use the general path,
    }                                  // which handles the range edges properly

    // General case: 2^(y * log2|x|)
    if (!done)
    {
        FT l = log2Fallback(ax);
        FT p = y * l;
        r = exp2Fallback(p);
        if (fabsFallback(p) < T.max_exp)           // skip when the result is inf/0/subnormal
            r *= 1 + fmaFallback(y, l, -p) * LN2;  // fold back the rounding error of y*l
    }

    return (x < 0 && yOdd) ? -r : r;
}

T hypotFallback(T)(T x, T y) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x == 0) return 0;
    x = abs(x);
    y = abs(y);
    if (x < y)
    {
        auto t = x; x = y; y = t;
    }
    T r = y / x;
    return x * sqrt(1.0 + r * r);
}

pragma(inline, true)
T modfFallback(T)(T x, ref T iptr) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    T i = trunc(x);
    iptr = i;
    return x - i;
}

T sinhFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (isNaN(x)) return x;
    if (isInfinity(x)) return x;
    T ex = exp(x);
    T exn = 1.0 / ex; // exp(-x)
    return (ex - exn) * 0.5;
}

T coshFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (isNaN(x)) return x;
    if (isInfinity(x)) return T.infinity;
    T ex = exp(x);
    T exn = 1.0 / ex;
    return (ex + exn) * 0.5;
}

T tanhFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (isNaN(x)) return x;
    if (isInfinity(x))
        return (x > 0) ? cast(T)1.0 : cast(T)-1.0;
    T two = 2.0;
    T ex2 = exp(-two * x);
    return (1.0 - ex2) / (1.0 + ex2);
}

T asinhFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (isNaN(x)) return x;
    if (isInfinity(x)) return (x > 0) ? T.infinity : -T.infinity;
    T s = sqrt(x * x + 1.0);
    return log(x + s);
}

T acoshFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (isNaN(x)) return x;
    if (x < 1.0) return T.nan;
    if (isInfinity(x)) return T.infinity;
    T s = sqrt((x - 1.0) * (x + 1.0));
    return log(x + s);
}

T atanhFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (isNaN(x)) return x;
    if (x == 1.0) return T.infinity;
    if (x == -1.0) return -T.infinity;
    if (abs(x) > 1.0) return T.nan;
    return 0.5 * log((1.0 + x) / (1.0 - x));
}

/// Rounds to the nearest integer.
T rintFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    T r = floorFallback(x + 0.5);
    if (x - floorFallback(x) == 0.5)
    {
        if (r % 2.0 != 0.0)
        {
            r -= 1.0;
        }
    }
    return r;
}

alias nearbyintFallback = rintFallback;

pragma(inline, true)
T fmaFallback(T)(T x, T y, T z) pure nothrow @nogc
{
    return (x * y) + z;
}

private template SignLayout(T)
{
    static if (T.mant_dig == 24)            // IEEE binary32
    {
        alias Word = uint;
        enum size_t index = 0;
        enum Word mask = 0x8000_0000;
    }
    else static if (T.mant_dig == 53)       // IEEE binary64
    {
        alias Word = ulong;
        enum size_t index = 0;
        enum Word mask = 0x8000_0000_0000_0000;
    }
    else static if (T.mant_dig == 64)       // x87 80-bit extended (always little-endian)
    {
        alias Word = ushort;                // sign lives in the top bit of bytes 8..9
        enum size_t index = 4;
        enum Word mask = 0x8000;
    }
    else static if (T.mant_dig == 113)      // IEEE binary128
    {
        alias Word = ushort;
        version (LittleEndian) enum size_t index = 7;
        else                   enum size_t index = 0;
        enum Word mask = 0x8000;
    }
    else
        static assert(0, "copysign: unsupported floating-point format " ~ T.stringof);
}

private union Bits(T)
{
    T value;
    SignLayout!T.Word[T.sizeof / SignLayout!T.Word.sizeof] word;
}

bool signbitFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (__ctfe)
        return x < 0 || (x == 0 && 1 / x < 0);   // NaN sign isn't observable at CTFE

    alias L = SignLayout!T;
    Bits!T b;
    b.value = x;
    return (b.word[L.index] & L.mask) != 0;
}

T copysignFallback(T, R)(T mag, R sgn) pure nothrow @nogc
    if (isFloatingPoint!T && isFloatingPoint!R)
{
    immutable(bool) neg = signbitFallback(sgn);

    if (__ctfe)
        return signbitFallback(mag) == neg ? mag : -mag;

    alias L = SignLayout!T;
    Bits!T b;
    b.value = mag;
    if (neg)
        b.word[L.index] |= L.mask;
    else
        b.word[L.index] &= cast(L.Word) ~L.mask;
    return b.value;
}
