/*
Copyright (c) 2019-2026 Timur Gafarov

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/**
 * Fallback elementary math functions.
 *
 * Description:
 * Provides platform-independent fallbacks for the following functions:
 * - abs, fabs
 * - trunc, floor, ceil, round, rint, nearbyint
 * - sqrt, cbrt
 * - sin, cos, tan
 * - asin, acos, atan, atan2
 * - exp, exp2, log, log2, log10, log1p, pow, expm1
 * - hypot, modf,
 * - sinh, cosh, tanh
 * - asinh, acosh, atanh
 * - fma
 * - signbit, copysign
 */
module rtld.math.fallback;

import rtld.core.traits;
import rtld.math.constants;
import rtld.math.utils;

private template SignLayout(T)
{
    static if (T.mant_dig == 24) // IEEE binary32
    {
        alias Word = uint;
        enum size_t index = 0;
        enum Word mask = 0x8000_0000;
    }
    else static if (T.mant_dig == 53) // IEEE binary64
    {
        alias Word = ulong;
        enum size_t index = 0;
        enum Word mask = 0x8000_0000_0000_0000;
    }
    else static if (T.mant_dig == 64) // x87 80-bit extended (always little-endian)
    {
        alias Word = ushort; // sign lives in the top bit of bytes 8..9
        enum size_t index = 4;
        enum Word mask = 0x8000;
    }
    else static if (T.mant_dig == 113) // IEEE binary128
    {
        alias Word = ushort;
        version (LittleEndian) enum size_t index = 7;
        else                   enum size_t index = 0;
        enum Word mask = 0x8000;
    }
    else
        static assert(0, "copysign: unsupported floating-point format " ~ T.stringof);
}

private union Bits(T)
{
    T value;
    SignLayout!T.Word[T.sizeof / SignLayout!T.Word.sizeof] word;
}

pragma(inline, true)
bool signbitFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (__ctfe)
        // NaN sign isn't observable at CTFE
        return x < 0 || (x == 0 && 1 / x < 0);

    alias L = SignLayout!T;
    Bits!T b;
    b.value = x;
    return (b.word[L.index] & L.mask) != 0;
}

pragma(inline, true)
T absFallback(T)(T v) pure nothrow @nogc
{
    return (v > 0.0)? v : -v;
}

T fabsFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (__ctfe)
        return signbitFallback(x) ? -x : x;
    alias L = SignLayout!T;
    Bits!T b;
    b.value = x;
    b.word[L.index] &= cast(L.Word) ~L.mask;
    return b.value;
}

T fmaxFallback(T)(T x, T y) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x != x) return y;
    if (y != y) return x;
    if (x == y) return signbitFallback(x) ? y : x;
    return x > y ? x : y;
}

T fminFallback(T)(T x, T y) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x != x) return y;
    if (y != y) return x;
    if (x == y) return signbitFallback(x) ? x : y;
    return x < y ? x : y;
}

T log1pFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x != x)            return x; // NaN
    if (x < -1)            return T.nan;
    if (x == -1)           return -T.infinity;
    if (x == T.infinity)   return x;

    immutable double xd = x;
    if (xd == double.infinity) // real beyond double's range: 1 + x == x
        return logFallback(x);

    immutable double u = 1.0 + xd;
    if (u == 1.0)
        return x; // |x| < eps/2, also keeps -0.0
    return cast(T)(logFallback(u) * (xd / (u - 1.0))); // x/(u-1) ~ 1 first: no overflow for huge x
}

// exp(x) - 1, accurate for tiny x.
//   u = exp(x); if u == 1 then expm1(x) == x, otherwise
//   expm1(x) = (u - 1) * x / log(u)   -- the rounding error of u cancels in the ratio.
// Computed in double (float is exact in it, real gets double accuracy).
T expm1Fallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x != x)            return x;
    if (x == T.infinity)   return x;
    if (x == -T.infinity)  return -1;
    if (x > 50)            return expFallback(x);     // e^-50 < eps: expm1 == exp (also handles overflow)
    if (x < -50)           return -1;

    double xd = x;
    double u  = expFallback(xd);
    if (u == 1.0)  return x;                          // |x| < eps/2, also keeps -0.0
    double d = u - 1.0;
    if (d == -1.0) return -1;
    return cast(T)(d * (xd / logFallback(u)));        // x/log(u) ~ 1 first: no intermediate overflow
}

///////////////////////////////////////

version(FreeStanding)
    version = UseFreeStandingMath;
else version(unittest)
    version = UseFreeStandingMath;

version(UseFreeStandingMath):

version(X86)
    version = UseX87Math;
version(X86_64)
    version = UseX87Math;

T truncFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum T M = 1 / T.epsilon;
    immutable T ax = fabsFallback(x);
    if (!(ax < M)) return x;
    T r = (ax + M) - M;
    if (r > ax) r -= 1; // rounded up: step back to truncate
    return copysignFallback(r, x); // keeps -0.0, e.g. trunc(-0.5) == -0.0
}

T floorFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    immutable T r = truncFallback(x);
    return (x < r) ? r - 1 : r; // floor(-0.5) == -1, floor(-0.0) == -0.0
}

T ceilFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    immutable T r = truncFallback(x);
    return (x > r) ? r + 1 : r; // ceil(-0.5) == -0.0
}

// Half away from zero.
T roundFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum T M = 1 / T.epsilon;
    T ax = fabsFallback(x);
    if (!(ax < M)) return x;
    T t = truncFallback(ax);
    if (ax - t >= 0.5) t += 1; // ax - t is exact
    return copysignFallback(t, x);
}

// Current rounding mode (round-half-even by default).
T rintFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum T M = 1 / T.epsilon;
    if (!(fabsFallback(x) < M)) return x;
    T r = (x >= 0) ? (x + M) - M : (x - M) + M;   // signed, so directed modes work
    return copysignFallback(r, x);            // keeps -0.0
}

alias nearbyintFallback = rintFallback;

T sqrtFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    version(UseX87Math)
    {
        T result;
        
        static if (isSingleFloat!T)
        {
            asm pure nothrow @nogc
            {
                fld dword ptr x;
                fsqrt;
                fstp dword ptr result;
            }
        }
        else
        {
            asm pure nothrow @nogc
            {
                fld qword ptr x;
                fsqrt;
                fstp qword ptr result;
            }
        }
        
        return result;
    }
    else
    {
        double z = cast(double)(x > 1.0) ? x * 0.5 : x + 1.0;
        for (uint i = 1; i <= 10; i++)
        {
            z -= (z * z - x) / (2.0 * z);
        }
        return cast(T)z;
    }
}

T cbrtFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum OneOverThree = 1.0 / 3.0;
    if (x < 0) return -cbrtFallback(-x);
    if (isNaN(x) || isInfinity(x)) return x;
    if (x == 0) return 0;
    T a = sqrtFallback(x);
    T b = T.infinity;
    while (a < b)
    {
        b = a;
        a = (2.0 * a + (x / (b * b))) * OneOverThree;
    }
    return a;
}

// x = n*pi/2 + (y0 + y1), |y0| <= pi/4. Returns n mod 4.
// Accurate for |x| < 2^20 * pi/2 (~1.6e6); beyond that you need Payne-Hanek.
private int reducePio2(double x, out double y0, out double y1) pure nothrow @nogc
{
    enum double invpio2 = 6.36619772367581382433e-01,
                pio2_1  = 1.57079632673412561417e+00,   // first 33 bits of pi/2
                pio2_2  = 6.07710050630396597660e-11,   // next 33 bits
                pio2_2t = 2.02226624879595063154e-21,
                pio2_3  = 2.02226624871116645580e-21,   // next 33 bits
                pio2_3t = 8.47842766036889956997e-32;

    immutable double fn = rintFallback(x * invpio2);
    double r = x - fn * pio2_1;                         // exact
    double t = r;
    double w = fn * pio2_2;
    r = t - w;
    w = fn * pio2_2t - ((t - r) - w);
    t = r;
    w = fn * pio2_3;
    r = t - w;
    w = fn * pio2_3t - ((t - r) - w);
    y0 = r - w;
    y1 = (r - y0) - w;
    return cast(int)(cast(long) fn & 3);
}

// sin(x + y) for |x| <= pi/4; y is a tiny correction term (the tail of the reduced argument)
pragma(inline, true)
private double sinKernel(double x, double y) pure nothrow @nogc
{
    enum double S1 = -1.66666666666666324348e-01, S2 =  8.33333333332248946124e-03,
                S3 = -1.98412698298579493134e-04, S4 =  2.75573137070700676789e-06,
                S5 = -2.50507602534068634195e-08, S6 =  1.58969099521155010221e-10;
    immutable double z = x * x;
    immutable double v = z * x;
    immutable double r = S2 + z * (S3 + z * (S4 + z * (S5 + z * S6)));
    return x - ((z * (0.5 * y - v * r) - y) - v * S1);
}

pragma(inline, true)
private double cosKernel(double x, double y) pure nothrow @nogc
{
    enum double C1 =  4.16666666666666019037e-02, C2 = -1.38888888888741095749e-03,
                C3 =  2.48015872894767294178e-05, C4 = -2.75573143513906633035e-07,
                C5 =  2.08757232129817482790e-09, C6 = -1.13596475577881948265e-11;
    immutable double z  = x * x;
    immutable double r  = z * (C1 + z * (C2 + z * (C3 + z * (C4 + z * (C5 + z * C6)))));
    immutable double hz = 0.5 * z;
    immutable double w  = 1.0 - hz;
    return w + (((1.0 - w) - hz) + (z * r - x * y));
}

T sinFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    double xd = x;
    double ax = fabsFallback(xd);

    if (ax < 0x1p-27)
        return cast(T)xd; // +-0 (sign kept) and tiny x
    if (!(ax < double.infinity))
        return cast(T)(xd - xd); // NaN, +-inf -> NaN

    double y0, y1;
    switch (reducePio2(xd, y0, y1))
    {
        case 0:  return cast(T)  sinKernel(y0, y1);
        case 1:  return cast(T)  cosKernel(y0, y1);
        case 2:  return cast(T) -sinKernel(y0, y1);
        default: return cast(T) -cosKernel(y0, y1);
    }
}

T cosFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    double xd = x;
    double ax = fabsFallback(xd);

    if (ax < 0x1p-27)
        return 1;
    if (!(ax < double.infinity))
        return cast(T) (xd - xd); // NaN, +-inf -> NaN

    double y0, y1;
    switch (reducePio2(xd, y0, y1))
    {
        case 0:  return cast(T)  cosKernel(y0, y1);
        case 1:  return cast(T) -sinKernel(y0, y1);
        case 2:  return cast(T) -cosKernel(y0, y1);
        default: return cast(T)  sinKernel(y0, y1);
    }
}

pragma(inline, true)
T tanFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return sinFallback(x) / cosFallback(x);
}

pragma(inline, true)
T asinFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return atan2Fallback(x, sqrtFallback(1.0 - x * x));
}

pragma(inline, true)
T acosFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return atan2Fallback(sqrtFallback(1.0 - x * x), x);
}

T atanFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    // Implementation from Algol 60
    const T        R1 =  0x1.9310cfe85307cp+3;
    const T        R2 = -0x1.58beca04f1805p+6;
    const T        R3 = -0x1.46d547fed8a3dp+0;
    const T        R4 = -0x1.57bd961f06c89p-4;
    const T        S1 =  0x1.b189e39236635p+4;
    const T        S2 =  0x1.a3b86f7830dc0p+2;
    const T        S3 =  0x1.1273f9e5eff20p+1;
    const T        S4 =  0x1.44831dafbf542p+0;
    const T       RT3 =  0x1.bb67ae8584caap+0;
    const T     PIBY6 =  0x1.0c152382d7365p-1;
    const T   PIBY2M1 =  0x1.243f6a8885a30p-1;
    const T     RT3M1 =  0x1.76cf5d0b09955p-1;
    const T TANPIBY12 =  0x1.126145e9ecd56p-2;
    const T       ONE =  0x1.0000000000000p+0;

    double XX1, XSQ, CONSTANT = 0.0;
    int SIGN = 0, INV = 0;

    if (x < 0) { SIGN = 1; XX1 = -x; } else XX1 = x;
    if (XX1 > ONE) { XX1 = 1.0 / XX1; INV = 1; }
    if (XX1 > TANPIBY12) { XX1 = (RT3M1 * XX1 - 1.0 + XX1) / (XX1 + RT3); CONSTANT = PIBY6; }

    XSQ = XX1 * XX1;
    XX1 = XX1 * (R1 / (XSQ + S1 + R2 / (XSQ + S2 + R3 / (XSQ + S3 + R4 / (XSQ + S4)))));
    XX1 = XX1 + CONSTANT;

    if (INV) XX1 = 1.0 - XX1 + PIBY2M1;
    if (SIGN) XX1 = -XX1;
     
    return XX1;
}

T atan2Fallback(T)(T y, T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x > 0)
        return atanFallback(y / x);
    else if (x < 0 && y >= 0)
        return atanFallback(y / x) + PI;
    else if (x < 0 && y < 0)
        return atanFallback(y / x) - PI;
    else if (x == 0 && y > 0)
        return HALFPI;
    else if (x == 0 && y < 0)
        return -HALFPI;
    else
        return 0; // Undefined
}

// exp: range reduction + Taylor on reduced interval
T expFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (isNaN(x)) return x;
    if (isInfinity(x))
        return (x > 0) ? T.infinity : 0;

    // Range reduction: x = n*ln2 + r, |r| <= ln2/2
    int n = cast(int)floorFallback(x * INVLN2 + 0.5);
    T r = x - cast(T)(n) * cast(T)LN2;

    // Taylor series for e^r, enough terms for reasonable precision
    T term = 1.0;
    T sum = 1.0;
    for (int k = 1; k <= 14; ++k)
    {
        term *= r / k;
        sum += term;
    }

    // Multiply by 2^n via repeated doubling/halving (safe-ish)
    if (n > 0)
    {
        while (n >= 30)
        {
            sum *= cast(T)(1UL << 30);
            n -= 30;
        }
        if (n > 0) sum *= cast(T)(1UL << n);
    }
    else if (n < 0)
    {
        int m = -n;
        while (m >= 30)
        {
            sum *= cast(T)(1.0) / cast(T)(1UL << 30);
            m -= 30;
        }
        if (m > 0)
            sum *= cast(T)(1.0) / cast(T)(1UL << m);
    }

    return sum;
}

// exp2: 2^x = e^(x ln2)
pragma(inline, true)
T exp2Fallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    return expFallback(x * cast(T)LN2);
}

// Splits finite x > 0 into m * 2^e; returns m.
private double splitLog(T)(T x, out int e) pure nothrow @nogc
{
    union DBits
    {
        double d;
        ulong u;
    }
    
    e = 0;
    static if (T.max_exp > 1024) // real wider than double: rescale into double's range
    {
        while (x > 0x1p+1000L) { x *= 0x1p-1000L; e += 1000; }
        while (x < 0x1p-1000L) { x *= 0x1p+1000L; e -= 1000; }
    }
    DBits b;
    b.d = x;
    if ((b.u >> 52) == 0) // subnormal double
    {
        b.d *= 0x1p54;
        e -= 54;
    }
    e += cast(int)(b.u >> 52) - 1023;
    b.u = (b.u & 0x000F_FFFF_FFFF_FFFF) | 0x3FF0_0000_0000_0000; // m in [1, 2)
    double m = b.d;
    if (m > 1.4142135623730951) { m *= 0.5; e += 1; }
    return m;
}

// dk * ln2 + log(1 + f) for f in [sqrt(2)/2 - 1, sqrt(2) - 1]
private double logKernel(double f, double dk) pure nothrow @nogc
{
    enum double ln2_hi = 6.93147180369123816490e-01,
                ln2_lo = 1.90821492927058770002e-10,
                Lg1 = 6.666666666666735130e-01, Lg2 = 3.999999999940941908e-01,
                Lg3 = 2.857142874366239149e-01, Lg4 = 2.222219843214978396e-01,
                Lg5 = 1.818357216161805012e-01, Lg6 = 1.531383769920937332e-01,
                Lg7 = 1.479819860511658591e-01;

    immutable double s    = f / (2.0 + f);
    immutable double z    = s * s;
    immutable double w    = z * z;
    immutable double t1   = w * (Lg2 + w * (Lg4 + w * Lg6));
    immutable double t2   = z * (Lg1 + w * (Lg3 + w * (Lg5 + w * Lg7)));
    immutable double R    = t2 + t1;
    immutable double hfsq = 0.5 * f * f;

    if (dk == 0)
        return f - (hfsq - s * (hfsq + R));
    return dk * ln2_hi - ((hfsq - (s * (hfsq + R) + dk * ln2_lo)) - f);
}

T logFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x != x)            return x; // NaN
    if (x < 0)             return T.nan;
    if (x == 0)            return -T.infinity; // +-0
    if (x == T.infinity)   return x;

    int e;
    double m = splitLog(x, e);
    return cast(T)logKernel(m - 1.0, e);
}

T log2Fallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum double LOG2E = 1.44269504088896340736;

    if (x != x)            return x;
    if (x < 0)             return T.nan;
    if (x == 0)            return -T.infinity;
    if (x == T.infinity)   return x;

    int e;
    immutable double m = splitLog(x, e);
    // m == 1 for powers of two, so those come out as the exact integer e
    return cast(T)(e + logKernel(m - 1.0, 0) * LOG2E);
}

T log10Fallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum double ivln10     = 4.34294481903251816668e-01,
                log10_2hi  = 3.01029995663611771306e-01,
                log10_2lo  = 3.69423907715893078616e-13;

    if (x != x)            return x;
    if (x < 0)             return T.nan;
    if (x == 0)            return -T.infinity;
    if (x == T.infinity)   return x;

    int e;
    immutable double m = splitLog(x, e);
    immutable double lm = logKernel(m - 1.0, 0);
    return cast(T)(e * log10_2hi + (e * log10_2lo + lm * ivln10));
}

// x^n for finite x > 0 and integer n >= 1, by square-and-multiply.
// Pure FP arithmetic (no casts to integers), exact while n < 2^mant_dig.
private T powSmallInt(T)(T x, T n) pure nothrow @nogc
{
    T r = 1;
    while (n >= 1)
    {
        T h = floorFallback(n * 0.5);
        if (n != h * 2)
            r *= x;
        x *= x; // may overflow/underflow, which is harmless here
        n = h;
    }
    return r;
}

T powFallback(T)(T x, T y) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    // Evaluate in double for the extra precision
    static if (is(T == float))
        alias FT = double;
    else
        alias FT = T;
    
    enum FT inf = FT.infinity;
    enum FT LN2 = 0.693147180559945309417232121458176568L;

    // --- IEEE 754 / C99 special cases --------------------------------
    if (y == 0 || x == 1) return 1; // even if the other one is NaN
    if (x != x || y != y) return T.nan;

    FT ax = fabsFallback(x);
    FT ay = fabsFallback(y);
    bool yInt = floorFallback(y) == y; // also true for +-inf
    bool yOdd = isOddInteger(y);

    if (ay == inf)
    {
        if (ax == 1) return 1; // pow(-1, +-inf)
        return ((ax < 1) == (y > 0)) ? cast(FT)0 : inf;
    }
    if (ax == inf)
    {
        bool negOdd = x < 0 && yOdd;
        if (y > 0) return negOdd ? -inf : inf;
        return negOdd ? copysignFallback(cast(FT)0, cast(FT) -1) : cast(FT)0;
    }
    if (x == 0) // +-0 base
    {
        if (y < 0) return yOdd ? copysignFallback(inf, x) : inf;
        return yOdd ? x : cast(FT)0; // keeps the sign of the zero
    }
    if (x < 0 && !yInt)
        return T.nan;

    // magnitude: |x| ^ y
    FT r = 0;
    bool done = false;

    // Small integer exponents: square-and-multiply is exact whenever the result is.
    if (yInt && ay <= 64)
    {
        r = powSmallInt(ax, ay);
        if (y < 0) r = 1 / r;
        done = (r != 0 && r != inf);   // on overflow/underflow use the general path,
    }                                  // which handles the range edges properly

    // General case: 2^(y * log2|x|)
    if (!done)
    {
        FT l = log2Fallback(ax);
        FT p = y * l;
        r = exp2Fallback(p);
        if (fabsFallback(p) < T.max_exp)           // skip when the result is inf/0/subnormal
            r *= 1 + fmaFallback(y, l, -p) * LN2;  // fold back the rounding error of y*l
    }

    return (x < 0 && yOdd) ? -r : r;
}

T hypotFallback(T)(T x, T y) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    if (x == T.infinity || x == -T.infinity ||
        y == T.infinity || y == -T.infinity)
        return T.infinity;
    
    if (x != x || y != y)
        return T.nan;

    x = fabsFallback(x);
    y = fabsFallback(y);
    if (x < y)
    {
        auto t = x; x = y; y = t;
    }
    
    if (x == 0)
        return 0;
    
    T r = y / x;
    return x * sqrtFallback(1 + r * r);
}

pragma(inline, true)
T modfFallback(T)(T x, ref T iptr) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    T i = truncFallback(x);
    iptr = i;
    return x - i;
}

T sinhFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum T sat  = 0.4 * T.mant_dig + 1;                       // ~22 for double: e^-2x is negligible
    enum T lnMax = T.max_exp * LN2;                           // log(T.max)
    enum T ovf   = (T.max_exp + 1) * LN2;                     // log(2 * T.max): beyond it, overflow
    enum T tiny  = 1 / cast(T)(1UL << (T.mant_dig / 2 + 2));

    if (x != x || x == T.infinity || x == -T.infinity) return x;
    T ax = fabsFallback(x);
    T h  = signbitFallback(x) ? -0.5 : 0.5;

    if (ax < sat)
    {
        if (ax < tiny) return x;                              // sinh(x) == x, keeps -0.0
        T t = expm1Fallback(ax);
        if (ax < 1)
            return h * (2 * t - t * t / (t + 1));
        return h * (t + t / (t + 1));
    }
    if (ax < lnMax) return h * expFallback(ax);
    if (ax <= ovf)                                            // exp(ax) overflows but sinh(ax) doesn't
    {
        T w = expFallback(0.5 * ax);
        return (h * w) * w;
    }
    return signbitFallback(x) ? -T.infinity : T.infinity;
}

T coshFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum T sat   = 0.4 * T.mant_dig + 1;
    enum T lnMax = T.max_exp * LN2;
    enum T ovf   = (T.max_exp + 1) * LN2;
    enum T tiny  = 1 / cast(T)(1UL << (T.mant_dig / 2 + 2));

    if (x != x) return x;
    if (x == T.infinity || x == -T.infinity) return T.infinity;
    T ax = fabsFallback(x);

    if (ax < 0.5 * LN2)                                       // avoid cancellation in e^x + e^-x
    {
        if (ax < tiny) return 1;                              // 1 + x^2/2 rounds to 1
        T t = expm1Fallback(ax);
        return 1 + (t * t) / (2 * (1 + t));
    }
    if (ax < sat)
    {
        T t = expFallback(ax);
        return 0.5 * t + 0.5 / t;
    }
    if (ax < lnMax) return 0.5 * expFallback(ax);
    if (ax <= ovf)
    {
        T w = expFallback(0.5 * ax);
        return (0.5 * w) * w;
    }
    return T.infinity;
}

T tanhFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum T sat  = 0.4 * T.mant_dig + 1;                       // tanh(x) == +-1 beyond this
    enum T tiny = 1 / cast(T)(1UL << (T.mant_dig / 2 + 2));

    if (x != x) return x;
    T ax = fabsFallback(x);
    if (ax >= sat)  return copysignFallback(cast(T) 1, x);    // also +-inf, before any exp() call
    if (ax < tiny)  return x;                                 // tanh(x) == x, keeps -0.0

    T z;
    if (ax >= 1)
    {
        T t = expm1Fallback(2 * ax);
        z = 1 - 2 / (t + 2);
    }
    else
    {
        T t = expm1Fallback(-2 * ax);                         // no cancellation for small ax
        z = -t / (t + 2);
    }
    return signbitFallback(x) ? -z : z;
}

T asinhFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum T big  = cast(T)(1UL << (T.mant_dig / 2 + 2));       // 2^28 for double
    enum T tiny = 1 / big;

    if (x != x || x == T.infinity || x == -T.infinity) return x;
    T ax = fabsFallback(x);
    if (ax < tiny) return x;                                  // asinh(x) == x, keeps -0.0

    T w;
    if (ax > big)                                             // log(2|x|), x*x would overflow
        w = logFallback(ax) + LN2;
    else if (ax > 2)
        w = logFallback(2 * ax + 1 / (sqrtFallback(x * x + 1) + ax));
    else
    {
        T t = x * x;                                          // no cancellation for small |x|
        w = log1pFallback(ax + t / (1 + sqrtFallback(1 + t)));
    }
    return signbitFallback(x) ? -w : w;                       // odd function
}

T acoshFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum T big = cast(T)(1UL << (T.mant_dig / 2 + 2));

    if (x != x) return x;
    if (x < 1)  return T.nan;
    if (x >= big)
        return (x == T.infinity) ? x : logFallback(x) + LN2;
    if (x == 1) return 0;
    if (x > 2)
        return logFallback(2 * x - 1 / (x + sqrtFallback(x * x - 1)));

    immutable T t = x - 1;                                    // exact; keeps precision near 1
    return log1pFallback(t + sqrtFallback(2 * t + t * t));
}

T atanhFallback(T)(T x) pure nothrow @nogc
    if (isFloatingPoint!T)
{
    enum T tiny = 1 / cast(T)(1UL << (T.mant_dig / 2 + 2));

    if (x != x) return x;
    immutable T ax = fabsFallback(x);
    if (ax > 1)  return T.nan;
    if (ax == 1) return copysignFallback(T.infinity, x);
    if (ax < tiny) return x;                                  // keeps -0.0

    T t;
    if (ax < 0.5)
    {
        immutable T y = ax + ax;
        t = 0.5 * log1pFallback(y + y * ax / (1 - ax));
    }
    else
        t = 0.5 * log1pFallback((ax + ax) / (1 - ax));        // 1 - ax is exact for ax >= 0.5
    return signbitFallback(x) ? -t : t;
}

pragma(inline, true)
T fmaFallback(T)(T x, T y, T z) pure nothrow @nogc
{
    return (x * y) + z;
}

T copysignFallback(T, R)(T mag, R sgn) pure nothrow @nogc
    if (isFloatingPoint!T && isFloatingPoint!R)
{
    immutable(bool) neg = signbitFallback(sgn);

    if (__ctfe)
        return signbitFallback(mag) == neg ? mag : -mag;

    alias L = SignLayout!T;
    Bits!T b;
    b.value = mag;
    if (neg)
        b.word[L.index] |= L.mask;
    else
        b.word[L.index] &= cast(L.Word) ~L.mask;
    return b.value;
}
